### ISSUE TITLE
Arming requires a code but none was given - Error 

### ISSUE THREAD

**Issue by adaminaus** [twrecked/hass-aarlo#1003]
Hoping this is just something i have done wrong but no real changes for years 
I can arm via the ARLO app and the status will change, same with google and IFTTT.
But if I try to ARM from the Card I get an error. 

Log details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 7:41:50 AM (6 occurrences)
Last logged: 7:55:12 AM

[140485315150752] Arming requires a code but none was given for alarm_control_panel.aarlo_holmes_house
[140485315289888] Arming requires a code but none was given for alarm_control_panel.aarlo_holmes_house

**Comment by twrecked** [comment]
Yeah... that happened to me and I've not tracked it down yet. Something flipped on an upgrade, you can fix it by reconfiguring and unchecking the "(Dis)Arm code reqiured" fields.

**Comment by adaminaus** [comment]
Thanks that has solved it

**Comment by adaminaus** [comment]
Thanks again
