### ISSUE TITLE
Entity Unavaliable

### ISSUE THREAD

**Issue by mike391** [twrecked/hass-aarlo#101]
Ive had added a new camera to my arlo account.  It showed up initially in HASS but now shows 'Entity unavailable'.  I tried removing aalo from my config and removing the entities.  I then installed aarlo again from HACS.   I then added my aarlo credentials back into my configuration.yaml.  My aarlo devices arent showing up anymore.  Is there a way to cleanly reinstall this component or anything else I can try?

**Comment by twrecked** [comment]
Are all your other cameras appearing?
Did you grant access to the HASS account in the Arlo app? 
Are you comfortable grabbing debug? You can add these lines to configuration.yaml and get a list of everything Arlo thinks is happening:

```yaml
logger:
    default: info
    logs:
      pyaarlo: debug
```

**Comment by mike391** [comment]
So I added the logging like you suggested.  It looks like its still only recognizing my original camera `Back Camera` . My new camera (`Front Camera`) is still not populating for some reason.  I double checked and i have allowed access to the arlo account home assistant uses. Im able to see the camera through the arlo webui no problem.

In case theres something I overlooked, ive attached the log (with username and passwords censored) here:
https://pastebin.com/8N5RLHTN

**Comment by twrecked** [comment]
It looks like they are both appearing as 'Back Camera'. Did you move one of the cameras? Can you check the naming in the HASS account?

**Comment by mike391** [comment]
Wierd... The arlo app shows the proper names. I did swap their places and renamed them at some point though.  I removed the front camera from arlo and added it again and restarted HASS. It seems to be picking up the camera now. I guess Arlo didnt propagate the name change properly? Good catch though, thanks for your help!
