### ISSUE TITLE
Arming/Disarming very patchy recently

### ISSUE THREAD

**Issue by gcorgnet** [twrecked/hass-aarlo#105]
Hi,

I used to have a pretty solid integration with my Arlo system using this. I recently upgraded to v0.5.5 (transitioning over the HACS at the same time) and since then I;ve noticed arming/disarming has been patchy.
It seems to work for a while after a HA reboot (which tells me my config is OK) but eventually stops working (my automations don;t seem to be able to arm/disarm either)

Is this a know issue? Is there something in the works?
Would love to get back to the level of stability I had before.

Cheers

**Comment by rccoleman** [comment]
This is already captured in https://github.com/twrecked/hass-aarlo/issues/68.
