### ISSUE TITLE
Alarm control panel doesn't work anymore

### ISSUE THREAD

**Issue by Tiippex** [twrecked/hass-aarlo#107]
'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)`

I think they changed something in the last update.

**Comment by twrecked** [comment]
What version of home assistant are you on? And what version of Aarlo? There was an issue with attributes but I thought it was fixed.

**Comment by Tiippex** [comment]
Homeassistant: 0.97.2
Aarlo: latest from the reconnect branch and I tested the master branch as well

**Comment by twrecked** [comment]
Can you try upgrading to v0.0.7-test02. There was definitely an issue with the Aarlo code getting it's constants from the wrong location. 

The 'testXX' branches are the same code as the 'reconnect' branches but with a scarier name. If you're not comfortable with test branches version 0.5.5 has the fix too.

**Comment by Tiippex** [comment]
I think that fixed the issue. To be honest: Im not sure if the latest version of aarlo fixed that already. my hassio didn't restart properly
