### ISSUE TITLE
Can't use Siren Service

### ISSUE THREAD

**Issue by degan6** [twrecked/hass-aarlo#109]
Reading through #78 and #87, I think I should see a service to turn on the siren in the Services page in HA.

But mine does not show any services for aarlo. Am I missing something? Is their another way to trigger the Siren, I use the custom Alarm competent. 

Aarlo Version V0.5.5
HA: 0.97.2
Hass.io: HassOS 2.12

**Comment by twrecked** [comment]
It should be there along with a `aarlo_set_mode`  option. It's missing from one of my machines. I'll take a look.

**Comment by twrecked** [comment]
Do you have the alarm panel enabled? Something like this:

```yaml
alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
```

The services should appear once that is enabled.

**Comment by degan6** [comment]
Hey thanks for the reply!

I am already using the manual alarm platform but was able to add aarlo as another platform too. 
I can create an automation to control the aarlo platfrom when arming the manual alarm, but I want to confirm how the siren works when Armed.

If the alarm control panel shows as armed for aarlo, and arlo sees motion will the siren go off by default or do I have to create an automation to do so? If so, is there a way to disable that functionality? I would like to the siren to sound 30 seconds after the alarm is triggered.

**Comment by twrecked** [comment]
The alarm won't go off, you will need to create an automation for this. All the alarm does is report the current mode and allow you to change it - changing the mode will affect how the cameras react, ie which report motion events and which don't,  but you have to configure that in the Arlo app.

Your automation can either turn the siren on for a short time or trigger the alarm. If you trigger the alarm the siren will sound for `trigger_time` seconds. You can change the volume with the `volume` option:

```yaml
alarm_control_panel:
  - platform: aarlo
    trigger_time: 30
    alarm_volume: 8
```

**Comment by degan6** [comment]
Got it! I'll set up an automation to trigger the aarlo alarm (really the siren) after my other alarm has been triggered for a seet amount of time.

Thank you for your help!
