### ISSUE TITLE
Support for Arlo lights

### ISSUE THREAD

**Issue by sebr** [twrecked/hass-aarlo#111]
Would love to see my arlo lights available in Hass.

Some prior art for investigation & implementation can be found at https://github.com/jeffreydwalter/arlo/issues/97

Thank you!

**Comment by twrecked** [comment]
I'll take a look. I'm just looking at getting the sirens going on newer cameras so I'll look into this after.

**Comment by sebr** [comment]
Thanks very much Steve! 🙌

**Comment by twrecked** [comment]
I picked up a light - Best Buy was having a sale on, a single light was down from $200 to $70. I've got the light on/off status and motion detection working and I can change modes on the base. Shouldn't take much to control the lights as well.

**Comment by sebr** [comment]
Thanks @twrecked ! I installed `0.0.7-light01` via HACS and I can see the lights in home assistant! However I can't appear to interact with them. The lights neither show the current state (on/off) or are picking up any state changes from the devices (on/off, motion events etc).

What can I do to debug or provide more info?

**Comment by sebr** [comment]
Okay strange... after enabling debug it works now!

**Comment by twrecked** [comment]
I just created `0.0.7-final`, I'd forgotten to turn on motion detection for the lights.

I think the brightness and colour settings should be easy, I just haven't had time to get them going yet.
