### ISSUE TITLE
Feature requested - Save video to file or URL

### ISSUE THREAD

**Issue by allenrong88** [twrecked/hass-aarlo#113]
I am not sure whether it is feasible or not. Currently it has service to save snapshot to file by using camera.aarlo_request_snapshot_to_file service. Is it possible to create the similar one of latest video recorded or URL then I can get video sent through via Telegram Chatbot please?

Thank you

**Comment by twrecked** [comment]
If you just want the URL of the last recorded video I think that would be quite simple. I could make it an attribute of the camera device. Would that work?

I think I could save the video to a file but I need to investigate the code a little more.

**Comment by allenrong88** [comment]
Thanks Steve.

I guess URL will be completely fine at start as remote path is one of the option Telegram can utilize to send video, not sure if it will work or not eventually, will see.

**Comment by twrecked** [comment]
I just created a version - 0.5.10 - that adds the URL to the attributes. I'll look at doing the save to file now.

**Comment by allenrong88** [comment]
Thanks so much Steve. Really appreciated! :) You are a legend!

**Comment by allenrong88** [comment]
Tried the latest release, works fantastic now! Great work!

**Comment by skynet01** [comment]
Hey @allenrong88 care to share how you got telegram video notification working? :)

**Comment by t9001** [comment]
@allenrong88 I could also use some help here - what's the code format for using the webhooks? Thanks!
