### ISSUE TITLE
Arlo (1. Gen) in Homebridge over HA

### ISSUE THREAD

**Issue by fastender** [twrecked/hass-aarlo#117]
You're doing a great job here. What's the status of the cameras in the HomeKit over HA (I have the first generation of cameras)?

**Comment by twrecked** [comment]
Sorry, I don't understand what you're asking. The component doesn't need or use HomeKit and I don't have a HomeKit to try it against.

**Comment by fastender** [comment]
I'm afraid I didn't express myself correctly.

My friend only uses Apple Home. So I included everything with https://www.home-assistant.io/components/homekit/.

But it is not possible to integrate the camera into the Home: https://www.home-assistant.io/components/homekit/#supported-components

I was wondering if another solution would be possible to integrate the camera into the home.

**Comment by twrecked** [comment]
Sorry, I meant to get back sooner.

Honestly, I don't know. Aarlo is compatible with the `stream` component so maybe you can use that to play the stream on a suitable device. I would look around on home-assistant.io to see if anybody has Homekit working with other cameras.

**Comment by fastender** [comment]
Many thanks, I sell my Arlos (1. Gen.) and buy now ultra & have fun now in 4k (Hope HomeKit-Support). U make really great work here with the new update. Many thanks.

**Comment by twrecked** [comment]
I'm going to move to #178
