### ISSUE TITLE
Blank/white snapshot in camera entities

### ISSUE THREAD

**Issue by rafuz** [twrecked/hass-aarlo#125]
From this morning I am getting an "all-white" image from cameras snapshots.
Example:

![image](https://user-images.githubusercontent.com/22271829/67394011-cd0a7600-f5a3-11e9-91f8-8102a6a1cdfa.png)

All other informations from the sensors are right, I can also see the registered videos.

**Comment by twrecked** [comment]
Which version of the software?

The latest has a `thumbnail_url` attribute against the camera state you should be able to cut/paste into a browser to see what it should be showing.

**Comment by rafuz** [comment]
Seems that the Amazon S3 host is not reachable from my zone right now:

**Comment by twrecked** [comment]
I'm assuming it's ok to close this one.
