### ISSUE TITLE
Install issues - No such file or directory: config

### ISSUE THREAD

**Issue by iditude** [twrecked/hass-aarlo#129]
Hello

I installed from HACS but getting an error message and I can't solve it. Can you help?

Is there a directory that needs creating manually?

Thanks

```2019-11-11 22:52:33 WARNING (SyncWorker_1) [pyaarlo] file not read
2019-11-11 22:52:35 WARNING (ArloEventStream) [pyaarlo] general exception [Errno 2] No such file or directory: '/config/.aarlo/packets.dump'
2019-11-11 22:52:42 WARNING (ArloEventStream) [pyaarlo] general exception [Errno 2] No such file or directory: '/config/.aarlo/packets.dump'
```

**Comment by twrecked** [comment]
Crap. It should create that directory automatically - it's directly under where you store your configuration - what system are you running on?

And you can stop it trying to write there by setting `packet_dump` to `False` in your config.

**Comment by iditude** [comment]
Hello,

I'm on a standard Home assistant in a virtual env on Raspberry Pi. 

I don't understand why the folder wasn't created. 

I tried creating it at the root of muy configuration (path config.aarlo and even creating an empty file packets.dump) but no success

Thanks

**Comment by twrecked** [comment]
Could it be a permission thing? Try 

```sh
sudo chmod a+rwx /config/.aarlo
sudo chmod a+rwx /config/.aarlo/*
```

and see if that helps. I know other people are using it on a Raspberry Pi.

**Comment by iditude** [comment]
Hello,

Still no luck, same error message. One thing that strikes me, the message indicates this folder starts with a slash '/'. This indicates it shouldn't be located were the Hass configuration is but at the root of the raspian distribution? 

Thanks

**Comment by twrecked** [comment]
I just noticed you said "virtualenv", I think I might have an idea what the issue is - it using "/config" as the default config directory when it should be using a value Home Assistant provides. I had a virtualenv environment here, I'll update it and give it a try. In the mean time does adding/setting the following line in your `aarlo` config make a difference:

```yaml
aarlo:
  conf_dir: /tmp/
```

**Comment by twrecked** [comment]
After testing on my virtualenv I think the problem is you have a `conf_dir` line in your `aarlo` configuration. Can you remove the line, it's not needed and the default is correct.

I'll update the README to show this line is not usually needed.

**Comment by iditude** [comment]
That was it. Thanks! 

Maybe it is worth updating the documentation?

Cheers
