### ISSUE TITLE
Mode Case Sensitivity (suggestion)

### ISSUE THREAD

**Issue by zemerick1** [twrecked/hass-aarlo#13]
Perhaps in the README, inform users that the default mode name 'Armed' in the app is not what is returned by the API. Instead, it is 'armed'. The API would not set the mode for me as I had `away_mode_name: "Armed"` in my configuration.yaml file. Once I changed it to `armed` everything worked fine.

**Comment by twrecked** [comment]
I changed the README last week but I agree totally about the case insensitivity and was planning to do this change this week.

And what's really annoying is it looks like "Armed" on the web page but is "armed" in the packets... Unless you create a mode then it's whatever case you use...

**Comment by zemerick1** [comment]
Exactly-- only custom modes are accurate. 'Disarmed' is the same way. . the API returns 'disarmed'.

**Comment by twrecked** [comment]
This branch fixes the issue - https://github.com/twrecked/hass-aarlo/tree/lower_case_alarm - by storing everything lowercase.

I'll test some more and merge tomorrow.

**Comment by twrecked** [comment]
Fixed by #16
