### ISSUE TITLE
Latest release says 0.6.3 but links to an init__.py that reads 0.6.2

### ISSUE THREAD

**Issue by rpitera** [twrecked/hass-aarlo#133]
I updated via HACS twice before I checked in the repo.

**Comment by twrecked** [comment]
Yep. My bad. Serves me right for pushing the fix before trying to get into work. I'll fix it up.

**Comment by twrecked** [comment]
I just bumped a revision to fix everything.

**Comment by rpitera** [comment]
No worries!  Thanks for all the hard work on this.  I love these cams.
