### ISSUE TITLE
ffmpeg on hass.io

### ISSUE THREAD

**Issue by ksheyman** [twrecked/hass-aarlo#139]
Hi, I have hassio installed via Docker and it would appear that it DOES support ffmpeg via rtsp protocol. Maybe this is new? Does this mean that this component would now support streaming via hass.io even though the documentation says that it doesn't? I'm considering purchasing an Arlo system and this would be a dealbreaker for me.

**Comment by twrecked** [comment]
It's working for me here. I just upgraded to `Home Assistant 0.103.5`, created a new container and was able to live stream from my cameras.

I guess I need to update the documentation...

**Comment by sbowater** [comment]
I have a clean "out-of-the-box" installation of HASSOS / Hass.io (0.103.5) on RPi and can confirm that camera streaming is working for me also without any additional config.

**Comment by damien67** [comment]
May I ask how did you guys enabled the streams?

I enabled ffmpeg: in my config yaml, but I am getting this in my log: 
WARNING (MainThread) [haffmpeg.core] Timeout while waiting of FFmpeg

I have not changed anything under the camera/aarlo section, which is setup as:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

Clicking the video only shows the last recording.

I am running HASS.IO 103.5 on an i5 Debian PC, with Aarlo 0.67.

**Comment by twrecked** [comment]
You need to add this to your `configuration.yaml` file:

```yaml
stream:
```

That is all that's needed, I don't even use the `ffmpeg_arguments` parameter any more.

**Comment by damien67** [comment]
Thank you so much for such prompt answer. 

I added the `stream:` component, tried with and without the `ffmpeg:` component, removed the `ffmpeg_arguments` config, and my aarlo-glance still shows me last recording when clicked and doesn't play the stream live. Restarted HA after each attempt of course.

This is my card configuration:
```
entity: camera.aarlo_living_room
image-click: play
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - captured_today
  - image_date
top_date: false
top_status: false
top_title: false
type: 'custom:aarlo-glance'
```

Weird...you make it sound so easy! :)

Also, all my battery icons are showing orange with a "battery strength" of 0%, but I know one is connected 100% of the time and the 2 others are over 50%.

**Comment by twrecked** [comment]
It's `image_click:` not `image-click`.

Somebody else was seeing the battery issue, I never tracked it down. What type of cameras are you using?

**Comment by damien67** [comment]
> It's `image_click:` not `image-click`.

Duh...sorry I wasted your time!

For the battery it is affecting my Arlo Baby (ABC1000) and my two Arlo Pro 2 (VMC4030P, connected to a VMB4500 station)
I don't think I had this issue before upgrading to the 0.67 version.
In my "state" page, one camera show `battery_level: 51`,`charging: false`, the other `battery_level: 100`,`charging: false`, and the baby `battery_level: 100`,`charging: false` (the baby is the one always plugged, the other 2 are on battery, percentages are all accurate).

Thanks for your help!

**Comment by twrecked** [comment]
For the battery, what is the `senor.aarlo_battery_level_living_room` showing? It's that value that gets put into the GUI card.

**Comment by damien67** [comment]
Makes a lot of sense now... I have not integrated the aarlo sensor component. 
I'll add it to my config and will let you know.

**Comment by twrecked** [comment]
I mentioned in another thread, I should probably work on improving the documents.

Basically, the lovelace card knows the entity naming format for aarlo devices and uses that to fill in the floating field information.

**Comment by damien67** [comment]
> I mentioned in another thread, I should probably work on improving the documents.
> 
> Basically, the lovelace card knows the entity naming format for aarlo devices and uses that to fill in the floating field information.

Yeah makes sense...

Just a quick note that the sensors entities are required for the Lovelace cards to display correctly would be helpful. Since I was seeing all the data correctly in the camera entity I didn't think twice and thought it was an issue. 

I think I am all setup and I shouldn't bother you again! Thanks again for your help and your work.

**Comment by twrecked** [comment]
It was no bother!

And I updated the Lovelace docs to show the sensor requirement.
