### ISSUE TITLE
Alarm Control Panel Entity Unavailable

### ISSUE THREAD

**Issue by alvaro-duarte** [twrecked/hass-aarlo#146]
Hi,

I just started using the aarlo component, installed through HACS, and everything looks to work just fine, but the Alarm Control Panel is the only thing that I am not able to make it work.

On the entities page the alarm_control_panel.aarlo_name-of-the-station appears as unavailable, and when creating an Alarm Panel on Lovelace I just get the message "Entity not available: alarm_control_panel.aarlo_name-of-the-station" (the name-of-station I am just using here, I have a different name). The correct name of the station is appearing and being detect on the entities, but shows as unavailable.

Any idea on what am I doing wrong and how can I possibly solve it?

Thanks and Regards

**Comment by twrecked** [comment]
Do you give admin access to the HA Arlo account?

**Comment by alvaro-duarte** [comment]
Hi,Thanks for the reply. Yes, I did so. Hass detects the base station, so it shall be working. The only thing is that on Hass it becomes unavailable.On Jan 8, 2020 17:12, Steve Herrell <notifications@github.com> wrote:Do you give admin access to the HA Arlo account?

**Comment by alvaro-duarte** [comment]
Here is a screenshot of what HA is showing for the entity... (hide the full name)

![image](https://user-images.githubusercontent.com/59612788/72052422-6d2f8b80-32c5-11ea-8061-a22e853ce259.png)

**Comment by alvaro-duarte** [comment]
Hi, Just another update, as I was now able to check the logs:

The log error shows the following:

```
Error while setting up platform aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/aarlo/alarm_control_panel.py", line 100, in async_setup_platform
    base_stations.append(ArloBaseStation(base_station, config))
TypeError: Can't instantiate abstract class ArloBaseStation with abstract methods supported_features
```

Hope this helps to have a better idea

Thanks

**Comment by twrecked** [comment]
You need to update your Aarlo installation. Home Assistant added the `supported_features` method which broke older Aarlo versions.

**Comment by alvaro-duarte** [comment]
> You need to update your Aarlo installation. Home Assistant added the `supported_features` method which broke older Aarlo versions.

Hi. Well, for some reason it did not update before... so sorted out.

However, now the issue is that I can see the Alarm Panel for one base station but not for the other (it gets blank and no information is shown). Any idea?

**Comment by twrecked** [comment]
Do they have different names? If you log into my.arlo.com with your HA account does everything appear correctly?

**Comment by alvaro-duarte** [comment]
Hi,Yes, they do have different names and on my Arlo everything looks just fine. The cameras related to all bases are showing ok on HA, however, the same thing is not happening with the base stations. For example, the siren switch I can only see it as an entity for one of the stations.Thanks

**Comment by twrecked** [comment]
What model base stations do you have? I have to enter the model numbers by hand into the code so it could be ignoring it.

**Comment by alvaro-duarte** [comment]
Hi,

This is the info for the one missing:
HW Version: VMB4500r2
Firmware: 1.15.0.1_3092_d878851

The one showing up is:
HW Version: VMB4000r3

Hope this helps.

Thanks

**Comment by twrecked** [comment]
Thanks for the info, I was missing that device.

I just pushed a fix - to v0.6.8 - it should appear on HACS shorty. Can you try it?

**Comment by alvaro-duarte** [comment]
Hi,

**Thank you** for the quick fix and for having a look into this.

Just updated from HACS, restarted HA and... I can now see the sirens for the base station that was not showing.

However, for some reason, the Alarm Panel for that base station keeps not working. All I get is a blank card. (for the other station it shows just fine)

Hope it helps

**Comment by twrecked** [comment]
Is there anything under `DEVELOPER TOOLS --> STATES` for the device? It will have a name like `alarm_control_panel.aarlo_*`.

**Comment by alvaro-duarte** [comment]
Yes, there's this:

![image](https://user-images.githubusercontent.com/59612788/72189239-a4ed1f00-33fc-11ea-940a-62353a12d1fb.png)

**Comment by alvaro-duarte** [comment]
Yes, there's this:

![image](https://user-images.githubusercontent.com/59612788/72189423-0f05c400-33fd-11ea-80b2-242b6a9c822b.png)

**Comment by twrecked** [comment]
That looks like it was recognised as an alarm. What does the working alarm look like?

Assuming they are the same, what does you alarm config look like. You might need to change the modes to match the names you are using.

```yaml
alarm_control_panel:
  - platform: aarlo
    home_mode_name: "Armed Home"
    away_mode_name: armed
```

**Comment by alvaro-duarte** [comment]
The working alarm looks like this:

![image](https://user-images.githubusercontent.com/59612788/72192763-1336df00-3407-11ea-9d7f-8feec89c5575.png)

I will try now to change the configuration and see if I can come up with something. Thanks for your time

**Comment by alvaro-duarte** [comment]
I tried your suggestion on the configuration and now it shows the Alarm Panel.

I had "Armed Home" for that specific base station on my.arlo.com, and after changing to that on HA, it did not work either. To make it work I had to place it as "Armed-Home" on my.arlo and HA..

Now it looks just fine. Thanks

**Comment by twrecked** [comment]
Glad it's working.

But I will be improving the documentation so hopefully this will happen less to people going forward.
