### ISSUE TITLE
javascript logs

### ISSUE THREAD

**Issue by Siege36** [twrecked/hass-aarlo#153]
Would it be possible to move the javascript log commands to operate under a flag? With 5+ cameras the "updating" messages inundate the console.

**Comment by twrecked** [comment]
Sure. I forgot to remove that one. It was used when I was optimising the card.

**Comment by twrecked** [comment]
Should be fixed by https://github.com/twrecked/lovelace-hass-aarlo/pull/19

Can you update and try?

**Comment by Siege36** [comment]
awesome, can confirm they have been removed.
