### ISSUE TITLE
Support for built-in light in Arlo Baby

### ISSUE THREAD

**Issue by cafedo** [twrecked/hass-aarlo#158]
Thanks a ton for this integration and specifically for supporting Arlo Baby!

Is it possibile to support the built-in light that any Arlo Baby has?

**Comment by twrecked** [comment]
Can you operate the light from the webgui?

**Comment by cafedo** [comment]
Yes I can; like the IOS app thought the web page (and its flash control) I can switch the light on/off, change the led color and schedule the automatic switch-off of the light after X minutes.
I 've noticed that when I click on the switch on/off button an xhr call starts: do you need some info?

**Comment by twrecked** [comment]
Does it appear as it own entity on the GUI? Or is it a button overlayed on the camera?

And what is the model number of the Arlo baby?

**Comment by cafedo** [comment]
It appears as a radial button overlayed on the camera.
Thought the info menu I can see the serial number of my Arlo Baby and the hardware revision (which is 6), but I can't see any model number. Can you please tell me where I can get the model number?

**Comment by cafedo** [comment]
Maybe is it this the model number? ABC1000-100EUS

**Comment by twrecked** [comment]
I found the commands to turn it on/off. I just never implemented them.  I'll probably make it appear as a separate `light` entity.

**Comment by cafedo** [comment]
Ok, yes I agree in making it appear as an independent light entity. When do you plan to release this feature?

PS: what about the possibility to change also the color? Is a goal impossibile to reach?

**Comment by m14t** [comment]
I'd love to see this too.

In case it's helpful here's the JSON payload I see in the HTTP `POST` to `https://my.arlo.com/hmsweb/users/devices/notify/XXXXXXXXXXXXX` when turning the light on:
```json
{
    "from": "XXXXXX-123-12345678_web",
    "to": "XXXXXXXXXXXXX",
    "action": "set",
    "resource": "cameras/XXXXXXXXXXXXX",
    "transId": "web!xxxxxxxx.xxxxx!xxxxxxxxxxxxx",
    "publishResponse": true,
    "properties": {
        "nightLight": {
            "enabled": true,
            "brightness": 255,
            "mode": "rgb",
            "rgb": {
                "red": 66,
                "green": 69,
                "blue": 255
            },
            "sleepTime": 0,
            "sleepTimeRel": 0
        }
    }
}
```

A few other details:
- `sleepTime` is a unix timestamp in seconds UTC for a time to turn the light off

Baby is stirring, but if any other info would be useful, I could help more later 😂

**Comment by twrecked** [comment]
That's great info, thanks. The first attempt will just turn the light on and off. I plan to add colours to the "ordinary" Arlo lights so I'll do them at the same time.

Can you capture some events for me? I need to know what is coming back from Arlo when you change the light settings.

Add this to your config and the events will be put into `/config/.aarlo/packets.dump`:

```yaml
aarlo:
    # current config here
    packet_dump: True
```

I'm expecting some events will contain `nightLight` in them.

**Comment by m14t** [comment]
I'm not sure I 100% follow what was asked, but what I did was:
1. Enabled these lines
2. Restart HomeAssistant
3. Ran `tail -f /config/.aarlo/packets.dump`
4. Logged into https://my.arlo.com
5. Turned the light off
6. Saw json similar to:
    ```
    {
      "action": "is",
      "from": "XXXXXXXXXXXXX",
      "properties": {
        "nightLight": {
          "brightness": 207,
          "enabled": False,
          "mode": "rgb",
          "rgb": { "blue": 0, "green": 5, "red": 255 },
          "sleepTime": 0,
          "sleepTimeRel": 0
        }
      },
      "resource": "cameras/XXXXXXXXXXXXX",
      "to": "XXXXXX-123-45678901_web",
      "transId": "web!x0xxx123.4x5x6!7890123456789"
    }
    ```
7. Turned the light on
8. Set the lights to a mostly blue color
9. Saw json similar to:
    ```
    { 'action': 'is',
      'from': 'XXXXXXXXXXXXX',
      'properties': { 'nightLight': { 'brightness': 207,
                                      'enabled': True,
                                      'mode': 'rgb',
                                      'rgb': {'blue': 255, 'green': 14, 'red': 0},
                                      'sleepTime': 0,
                                      'sleepTimeRel': 0}},
      'resource': 'cameras/XXXXXXXXXXXXX',
      'to': 'XXXXXX-123-45678901_web',
      'transId': 'web!x0xxx123.4x5x6!7890123456789'}
    ```

**Comment by twrecked** [comment]
Sorry for the garbled message but I had to dash out of the house.

But the captures are perfect, I can map those into the existing HA light type. I'll look at implementing something early this week.

I also think I'll add the light button to the Lovelace card too.

**Comment by twrecked** [comment]
@cafedo  I missed your comment - sorry. Yes, changing colours is a goal, I just keep running out of time!

**Comment by twrecked** [comment]
Is anybody ok manually installing a branch? https://github.com/twrecked/hass-aarlo/tree/arlo-baby-light 
This includes provisional Arlo Baby light support. If not, I can create a test release tomorrow.

**Comment by sebr** [comment]
@twrecked I can switch on the light but can't switch it off - I think because the state never shows the light as on

**Comment by twrecked** [comment]
I'm not parsing the return packet correctly I'll try and force the packets you sent into my system. In the meantime I just pushed a small update with some extra debug.

Enable debug with the following and look for nightlight in the output log `/config/home-assistant.log`

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.light: debug
    pyaarlo: debug
```

**Comment by sebr** [comment]
Working great so far @twrecked ! Thanks mate!

Would be awesome to get the colour picker and brightness level too. I'll give it a shot!

**Comment by twrecked** [comment]
The colours should work, I implemented the ArloLights and just never had the time to convert what Home Assistant sends to what Arlo expects.

I can also implement the timer but it would be a service call, the Arlo light doesn't have a concept of it.

**Comment by sebr** [comment]
@twrecked this issue can be closed now!
