### ISSUE TITLE
Alarm control panel not showing correct status in GUI

### ISSUE THREAD

**Issue by Bacon-Ranch** [twrecked/hass-aarlo#159]
Hello, I have had this working for a few weeks but now have a small issue. I had 2 Arlo Pro bases and 1 light bridge. I have a unique account for Hassio and share devices so eveything is combined to the 1 account. I recently added a new Ultra Smart base and 3 cameras and added another light bridge to 1 of my previous 2 Arlo pro bases. So, in total now that is 5 Alarm Control Panels in the GUI. 4 of them work but the new light bridge does not update the status but does actually Arm when pressed, just doesnt show as Armed in HA. I have removed the device, re installed, upgraded firmware, rebooted. restarted Hassio, removed from Hassio, etc... no change. It seems to me it was working for a couple days as the bridge with just 1 light and it stopped working when I added 2 more lights to that bridge. Seems like it should not be related but worth mentioning.

**Comment by twrecked** [comment]
I have a similar number of alarm control panes so that shouldn't be the problem.

Are the mode names the same across all the devices?

**Comment by Bacon-Ranch** [comment]
Hi Steve,

Yes, the names are all the same consistently.....all caps.

Thank you for making this and responding!


On Feb. 1, 2020 10:36 a.m., Steve Herrell <notifications@github.com> wrote:

I have a similar number of alarm control panes so that shouldn't be the problem.

Are the mode names the same across all the devices?

**Comment by Bacon-Ranch** [comment]
I'll try removing the light bridge all together, reboot everything, wait a day or 2 and start from scratch on that bridge and see if it operates as intended.

**Comment by twrecked** [comment]
You should't have to reinstall anything but, before you try, do you have admin access on your HA Arlo account? Not having that causes strange issues.

**Comment by Bacon-Ranch** [comment]
Hello,

Yes, I do have admin access on the HA account...none the less, I have removed the light bridge and decided to re install it on the new ultra smart base .... and it all works now. My HA has done some weird things lately, thinking the SD card is saying bye but also think that would happen abruptly....anyways, all sorted. Will mark as close when I am on a PC!

Thank you,
Mark

On Feb. 2, 2020 10:39 a.m., Steve Herrell <notifications@github.com> wrote:

You should't have to reinstall anything but, before you try, do you have admin access on your HA Arlo account? Not having that causes strange issues.

**Comment by twrecked** [comment]
That's great news. You shouldn't have had to reinstall but I'm glad it's working now.

**Comment by Bacon-Ranch** [comment]
Hi Steve,

Was working great, now not so much. Took a step back. None of my 5 alarm panels are showing the correct armed or disarmed status. It happened earler, I had rebooted Hassio and it was fine for a bit, now its  not updating status at all.

________________________________

**Comment by twrecked** [comment]
I got an email saying it wasn't working but I can't find the comment. [Deleted?] One more thing to try is adding these options to your config:

```yaml
aarlo:
  refresh_devices_every: 2
  stream_timeout: 120
```

We're using the web interface and I don't think it was designed to held open for hours and those options will help with that.

**Comment by Bacon-Ranch** [comment]
will add that. Yes, I replied with an update that was a step back...and then deleted because I am having some odd behaviour. None of the alarm panels were updating status....then I woked out that it was Wink not updating lock status which is in the automation recipe.

________________________________

**Comment by twrecked** [comment]
Ok to close this?

**Comment by twrecked** [comment]
Should be working.
