### ISSUE TITLE
Geofencing using "home mode: scheduled" shows armed_away always

### ISSUE THREAD

**Issue by timdonovanuk** [twrecked/hass-aarlo#163]
Hi,

I feel like this is probably my fault with a missconfiguration/understanding but:

I have my Arlo set to Geofencing mode with:

Away mode: Armed
Home mode: Schedule

In HA my alarm_control_panel.aarlo_arlo_hub = armed_away, even if, due to sheduling, it is disarmed.

If I manually set my Arlo to disarmed, HA quickly updates to reflect this, so I know the integration is working.

Thanks.

**Comment by twrecked** [comment]
Sorry for the delay getting back...

I'll take a look at this. I'm not sure how good the recognition of scheduling is. I'll take a look.

**Comment by joch** [comment]
I’m seeing the same thing with the following configuration:
```
home_mode_name: armed
away_mode_name: vacation
```
It always says armed_away, even though it’s actually in “armed home” mode.

**Comment by twrecked** [comment]
@joch Yours is a slightly difference issue but I think it's quite easy to fix - I should prefer custom alarm modes before default ones.

**Comment by twrecked** [comment]
@timdonovanuk It's nothing you're doing wrong, the code doesn't currently parse out the schedules. I'll see how much work is involved in this.

**Comment by twrecked** [comment]
It should be fixed by this:

https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.12

**Comment by twrecked** [comment]
See previous comment.
