### ISSUE TITLE
Feature Request: last thumbnail and video url for Arlo baby 

### ISSUE THREAD

**Issue by allenrong88** [twrecked/hass-aarlo#173]
Firstly thanks Steve for your amazing work, I have been using it for my entire Arlo systems without any issue at all.

Would you be able to do exactly the same features by getting url for last thumbnail and video, which are currently on Arlo but not on Arlo baby please?

Thank you

**Comment by sebr** [comment]
@allenrong88 I already see these in my Arlo baby device attributes:

<img width="430" alt="Screen Shot 2020-03-04 at 3 38 54 pm" src="https://user-images.githubusercontent.com/81972/75845770-43f72b80-5e2e-11ea-8c60-5ad7d2eb706a.png">
