### ISSUE TITLE
Video Playback does not work from Computer but does from Mobile App

### ISSUE THREAD

**Issue by ddjobe** [twrecked/hass-aarlo#174]
I am running HA on a rPi4.  My HA version is 106.2, Aarlo version Installed: v0.6.14 and Lovelace Hass Aarlo Installed: v0.6.14.  On my computer, when I click on either the card to stream or click on a saved clip, the video will not play back.  I can hear the audio of the clip.  When I do the same actions in the HA App on my iPhone, everything works as expected.

**Comment by twrecked** [comment]
What OS and browser are you using on your computer? And do the library recordings work?

**Comment by ddjobe** [comment]
I have tried on MacOS Catalina using both Safari and Chrome.  I have also tried on Windows 10 using Chrome and Firefox.  It does not work for direct streaming or when I try to view library recordings.

**Comment by twrecked** [comment]
Direct streaming could be the cameras - do you have Arlo Q?

But the library usually works, it streams mp4 files directly from Arlo. Can you turn on debug and see if any error are coming from Home Assistant or Aarlo?

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```

**Comment by ddjobe** [comment]
I apologize for my tardy reply.  I do not have Arlo Q.  Both of my Cameras are Arlo Pro 3.

I have turned on the debug commands you provided and restarted HA.  I'm not sure where to pull the logs.

**Comment by ddjobe** [comment]
Please let me know where and how to pull the logs and I'll get those sent to you.

**Comment by ddjobe** [comment]
I just updated to latest aarlo version.  I still cannot view camera footage.

**Comment by twrecked** [comment]
Sorry. Got a bit tied up at home. I'll take a look at this tomorrow.

**Comment by twrecked** [comment]
For the Arlo debug look under your configuration directory, there will be a file called `home-assistant.log`, that is where Arlo will put it's debug. You will need to look for `backTrace` or any lines with `pyaarlo` showing an error. The easiest way would be to open the file, start streaming from the library, and then reopen the file and see what changed.

But it's working from the mobile app which is odd. From Windows or MAC can you try browsing from an icognito tab? And can you try browsing with chrome and the debugging window enabled - CTRL+SHIFT+I - to see if we're getting any network errors.

**Comment by ddjobe** [comment]
Attached is a log.  Not sure if the Trackback is related to Arlo.
[Arlo Debug.txt](https://github.com/twrecked/hass-aarlo/files/4384405/Arlo.Debug.txt)

I got this out of the Chrome debug.
Failed to load resource: the server responded with a status of 404 (Not Found)
load_resource.ts:17 
Uncaught (in promise) https://jobehome.duckdns.org/local/aarlo-glance.js
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: https://cdn.jsdelivr.net/npm/hls.min.js.map

**Comment by ddjobe** [comment]
Good morning!  Anything found in the log and debug?

**Comment by twrecked** [comment]
There was nothing in either of the logs. The Arlo debug just shows a normal startup. The Chrome debug shows some errors, but I see the same ones and a quick google show it's the debug tools, not the `aarlo-glance` card causing the problem. I guess we have to head back to basics, can you paste in your `aarlo` and `camera` debug - less any sensitive information obviously. These pieces:

```yaml
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  packet_dump: True
  recent_time: 120

camera:
  - platform: aarlo
```

Can you also send me the `aarlo-glance` card configuration for one camera.

**Comment by ddjobe** [comment]
Here you go!  I believe this is what you wanted.  I pulled all pieces of my configuration.yaml related to aarlo.

# Arlo Cameras
aarlo:
  username: !secret arlo_usr
  password: !secret arlo_pwd
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    trigger_time: 30
    alarm_volume: 8

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

media_player:
  - platform: aarlo

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    siren_volume: 1
    siren_duration: 10


    cards:
      - entity: camera.aarlo_driveway_north
        image_click: play
        name: Driveway North
        show:
          - motion
          - sound
          - snapshot
          - battery_level
          - signal_strength
          - captured_today
          - image_date
        top_date: true
        top_status: false
        top_title: false
        type: 'custom:aarlo-glance'

**Comment by ddjobe** [comment]
Good afternoon, Steve.  Just checking in on this...

**Comment by twrecked** [comment]
Sorry. Crazy busy. Of course everything works at this end.

I'm wondering if it's the cameras. They are the only difference between our systems. But I don't know why. Is it a h264/h265 thing? It's a bit out of my comfort zone.

Do you have a camera pointing somewhere innocuous? Or could you point one somewhere dull - outside wall or tree - and share it with me for a short time? I could try streaming here.

**Comment by ssilence5** [comment]
Just to add to the above, I noticed today that my live streaming works fine. When I try to play back from the library it just gives me audio, no video. However, it works perfectly fine in the app. I have tried it with Chrome, Firefox and IE/Edge. I see the following in Firefox logs when I try to do playback of a capture video:

```
HTTP “Content-Type” of “text/html” is not supported. Load of media resource http://192.168.55.2:8123/lovelace/null failed. Security
Cannot play media. No decoders for requested formats: text/html
```
I am thinking this is a h264/h265 thing. Is the video format for live stream different from playing back something from the library. I know I can't play videos from the my.arlo.com library since they are MP4 h265 encoded, but can livestream, so that matches what I am seeing in the HASS plugin.

**Comment by twrecked** [comment]
@ssilence5 
Do the library recordings play on my.arlo.com (or is that what you meant by the app)?

Try changing your user agent, it might break streaming but it might get the libraries to play video.

```yaml
aarlo:
  user_agent: linux
```

**Comment by ssilence5** [comment]
@twrecked 
The Library Recordings do not play on my.arlo.com. My understanding is that since i have a 2K camera they are encoded in h264/h265 and won't play directly in the browser. They will play fine in the Arlo app and if I download them will play fine in VLC. 

As for the hass-aarlo, they will play fine on the IOS Home-Assistant App, but that is the only place.

**Comment by ddjobe** [comment]
@ssilence5, thanks for chiming in.  I only have 2k cameras so this seems to be the common denominator.  Also, I have an interesting find.  I can stream from the library recordings on my Mac in Safari, but not in Chrome.  On my Windows computer, I cannot stream from any browser.

**Comment by ddjobe** [comment]
I just found this, https://kb.arlo.com/000062189/Which-devices-are-supported-for-HEVC-4K-or-2K-playback.  This article points to, https://caniuse.com/#feat=hevc, which shows only Apple devices have native playback.  For MacOS, you have to be on High Sierra or later. This is a general Apple article for supported devices, https://support.apple.com/en-us/HT207022.

Please review.  I think this confirms it is a codec issue and cannot be resolved by @twrecked.

**Comment by ssilence5** [comment]
I tend to agree, it is a codec issue. I am definitely not a video guy, but is there anything that can be done to stream playback through ffmpeg where it will create a replacement video in an appropriate format? Might be to much to ask or take to long/to much processing.

**Comment by twrecked** [comment]
Closing because I believe it's a codec issue. Although, try the latest beta for direct streaming.
