### ISSUE TITLE
Snapshot reverting to previous image

### ISSUE THREAD

**Issue by jason0x43** [twrecked/hass-aarlo#181]
I just migrated from a Home Assistant Core install to full Home Assistant in a VM, and I'm noticing some odd behavior with this integration, and/or with lovelace-hass-aarlo.

If I manually take a snapshot by clicking on the snapshot button in a lovelace-hass-aarlo card, or via the `aarlo.camera_request_snapshot` service, a new snapshot shows up in the aarlo card. After a few seconds, though, the snapshot reverts to the previously displayed image.

Debug logs for pyaarlo and custom_components.aarlo show the snapshot being taken, but don't show any new messages when the view in the card reverts, so it doesn't look like the integration is re-requesting an old snapshot. However, a chrome network log shows the UI first requesting a data URL containing the new snapshot (at which point the new snapshot is displayed), followed a couple seconds later by a request to `https://arlolastimage-z2.s3.amazonaws.com/d2c5c94b0f8541e7a8a14567dbcdf15a/9Z2MZ-100-47555873/52M18571AA93C/lastImage.jpg?...`, after which the previous image is displayed.

Are there any known issues running this in a supervised Home Assistant install, or am I missing something obvious?

**Comment by twrecked** [comment]
It's happening to me too. They removed (are removing) the camera_image service so I have to get the glance card image another way and I've introduced a bug. I'll take a look at it.

**Comment by jason0x43** [comment]
Good to know it's not just me. 😄

**Comment by twrecked** [comment]
Should be fixed by #183 and in this release https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.16

**Comment by jason0x43** [comment]
That seems to have done the trick!
