### ISSUE TITLE
No sound for live stream

### ISSUE THREAD

**Issue by jason0x43** [twrecked/hass-aarlo#184]
This may not be a problem, but I've been wondering for a while, and didn't see anything in the documentation.

When I play a live stream from my Arlo Pro 2's, there's no sound. However, when I play one of the recorded clips (which I just tried for the first time yesterday), there is sound. Should there be audio from a live stream?

**Comment by twrecked** [comment]
Audio isn't supported in the stream component - see [here](https://community.home-assistant.io/t/amcrest-camera-no-audio/112776/6)

Longer answer: the library streams mp4 files directly from Arlo and includes the sound. Streams are converted to HLS by Home Assistant and audio is not included.

**Comment by jason0x43** [comment]
Interesting. In `components/stream/worker.py`, it kind of looks like they're intentionally stripping the audio out of an incoming stream. 

I don't suppose live streams could (optionally) come directly from Arlo as well? Aside from providing audio, it would be a bit more efficient (for clients that could handle the stream directly).

**Comment by twrecked** [comment]
It's very possible to do it - the Arlo web site does it - but you can't stream RTSP directly to a browser and have to go via a proxy, see [here](https://stackoverflow.com/questions/41965793/rtsp-h-264-in-google-chrome-browser/52495924) for some extra details.

I did start looking into it but then the `stream` component appeared and that was easier.

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo/issues/151#issuecomment-659567535

Can you try this, Arlo is changing their streaming.

**Comment by jason0x43** [comment]
That works! Very nice. :)

**Comment by twrecked** [comment]
Closing because I'm assuming it's working now.

**Comment by jason0x43** [comment]
Heh, and now the stream component supports audio (as of 0.115).
