### ISSUE TITLE
Camera is stuck in "taking snapshot" state

### ISSUE THREAD

**Issue by jason0x43** [twrecked/hass-aarlo#189]
I run an automation that updates a couple of cameras every 30 seconds, similarly to how iOS Home behaves with visible camera tiles. Sometimes, one of the cameras (it varies) will become stuck in the "taking snapshot" state. This persists across UI refreshes and even HA restarts, and on different machines. When the camera is opened in the iOS Home app and Home's screenshot updates, the state resets in HA (back to "idle"), and HA's snapshot updates resume.

I'm not seeing anything obvious in the logs when a camera is stuck in the "taking snapshot" state. My snapshotting automation continues to run, and no errors are reported. I haven't increased the log level to 'debug' yet, though, so that may show something.

I'm using hass-aarlo 0.6.17 and lovelace-hass-aarlo 0.0.17 on HA 0.107.1.

**Comment by twrecked** [comment]
Some quick background...

The snapshot functionality is buggy at the webgui/backend level. For example, I have a camera that doesn't update from the web interface ever. It's really annoying...

...but I'm working on some fixes that should help with this - notably configurable timeout and better state updates. Give me a day or two.

**Comment by Swiftnesses** [comment]
None of my gen.1 cameras update at night (used the component since day 1) :-(

**Comment by twrecked** [comment]
@Swiftnesses I managed to get one unstuck today. I live streamed from it then the snapshot started working. I just think the snapshot on the older cameras is flaky.

**Comment by twrecked** [comment]
I have some extra timeout code checked into the latest beta releases that will hopefully deal with the issue. The snapshot still might not work - because of Arlo, not me - but it should make a better attempt at recovery.

**Comment by jason0x43** [comment]
I haven't seen this behavior in a while, so this issue can be close as far as I'm concerned.

**Comment by twrecked** [comment]
Thanks for the update!
