### ISSUE TITLE
Upgrade to 0.107.2 seems to break aarlo

### ISSUE THREAD

**Issue by MechEng70** [twrecked/hass-aarlo#190]
Here is the error:
2020-03-20 10:43:12 WARNING (SyncWorker_8) [pyaarlo] failed to log in
2020-03-20 10:43:12 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 183, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    for device in self._devices:
TypeError: 'NoneType' object is not iterable
2020-03-20 10:43:12 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
2020-03-20 10:43:12 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.sensor: Unable to set up component.

Restarted the HomeAssistant and same result.

**Comment by BlackVQ35HR** [comment]
I can confirm the same problem

**Comment by twrecked** [comment]
They've changed the authentication mechanism... My 106 is broken too.

**Comment by sbowater** [comment]
> They've changed the authentication mechanism... My 106 is broken too.

Same here (0.106)

**Comment by Swiftnesses** [comment]
;-(

**Comment by codycodes** [comment]
+1. Thank you for this amazing component btw! Glad an issue is already posted.

**Comment by sbowater** [comment]
I tried reverting to the core HA Arlo integration and, not surprisingly, it is also broken.

**Comment by twrecked** [comment]
This might fix it #191 , it's in release [0.6.18](https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.18) and will appear shortly in HACS.

This a quickie fix, it works for me but I have to see if anything else has changed but most things seems to work for me.

**Comment by MechEng70** [comment]
Working for me!  Thanks.

**Comment by twrecked** [comment]
Excellent. Takes a little longer to start up but it gets there. I'm hoping this lets the event stream stay connected longer.

**Comment by Swiftnesses** [comment]
Let us donate you mad man 🥇

**Comment by codycodes** [comment]
Working great here as well. Thanks for the quick response! If 2fa works I'm hoping to use home assistant to completely control when the cameras record. Would be happy to donate for all your hard work!

**Comment by sbowater** [comment]
Appears to work for me too.  I do see this warning in the log during startup...

Log Details (WARNING)
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:45
First occurred: 3:54:20 PM (1 occurrences)
Last logged: 3:54:20 PM

event loop failed to start

**Comment by twrecked** [comment]
@sbowater are you seeing notifications come in - motion detection etc - if not, I'd restart.

**Comment by sbowater** [comment]
> @sbowater are you seeing notifications come in - motion detection etc - if not, I'd restart.

I restarted and I do still have the warning in the log, however, I am receiving notifications (e.g., motion detected on cameras) so all appears to be fine.  Thanks!

**Comment by BlackVQ35HR** [comment]
Problem solved for me as well. Thanks for the fix

**Comment by MechEng70** [comment]
FYI updated to 0.107.3 and all is still good.  thanks again!

**Comment by twrecked** [comment]
@sbowater  I found why that message is coming out. It doesn't affect anything but it does slow down the start up. I'm merging in a fix later.
