### ISSUE TITLE
pyaarlo is not logging in after updating to 0.6.18

### ISSUE THREAD

**Issue by rpitera** [twrecked/hass-aarlo#192]
Was having no problems in 0.107.x with 0.6.17 but when I got the notification to update to 0.6.18 I went ahead and updated.  I'm now unable to setup AArlo at all and the only thing I get from debug is the following:

```
2020-03-20 19:26:25 DEBUG (SyncWorker_0) [pyaarlo] Cfg started
2020-03-20 19:26:25 DEBUG (SyncWorker_0) [pyaarlo] starting
2020-03-20 19:26:25 DEBUG (SyncWorker_0) [pyaarlo] custom connections 5:10
2020-03-20 19:26:25 DEBUG (SyncWorker_0) [pyaarlo] login failed
2020-03-20 19:26:25 WARNING (SyncWorker_0) [pyaarlo] failed to log in
2020-03-20 19:26:25 INFO (SyncWorker_0) [pyaarlo] pyaarlo starting

```
Downgraded to 0.6.17 but same error.  Reinstalled 0.6.18 and then updated HA from 0.107.2 to 0.107.3 (since I had to restart anyway) and still get the same error.

Not sure what is going on because until I updated, everything Arlo was working just fine for me.

**Comment by rpitera** [comment]
Additional troubleshooting:
Just verified that the HA account I made for aarlo logins still works.  So it's not the account itself.

**Comment by twrecked** [comment]
it's probably related to this #190 

Do you set the `host` variable in your config?

**Comment by rpitera** [comment]
Yes.  I should have included my aarlo config with my initial findings; I am sorry for not including it.

```
aarlo:
  host: https://arlo.netgear.com
  username: !secret arlo_user
  password: !secret arlo_pass
  verbose_debug: True
```

Should I remove or change it?

**Comment by twrecked** [comment]
Can you try removing it for now? Arlo updated the login mechanism so I had to push a hasty fix.

If removing it doesn't work I can push a fix later.

**Comment by rpitera** [comment]
Took a chance that was what you were going to suggest and I did so and restarted.  Everything back now.  I feel like I should have been able to figure this out for myself from looking at the updated docs, but I panicked a bit.  (Sorry; since the pandemic, panic has sort of been my default mode. )

Thanks for being there again, Steve.  If you agree I think we can close this.

**Comment by twrecked** [comment]
Just keep an eye on it. I don't think you need the `host` variable anymore, it was introduced a while back to help with backward compatibility when Arlo moved websites.

I'll tidy the login changes tomorrow and you'll be able to use the `host` variable if you really need to.
