### ISSUE TITLE
Feature request: Two-step verification 

### ISSUE THREAD

**Issue by friendodevil** [twrecked/hass-aarlo#193]
Feature request : two-step verification / authentication

By the end of the year, Arlo will require all users to enable two-step verification. Setting up Arlo two-step verification in [this link](https://kb.arlo.com/000062288/What-is-two-step-verification-and-how-do-I-set-it-up)

![2020-03-21_LI](https://user-images.githubusercontent.com/40683291/77231324-d293d880-6ba2-11ea-97e6-34f0e02ec762.jpg)

**Comment by twrecked** [comment]
Duplicate of #177

**Comment by twrecked** [comment]
Thought I'd concentrate it in one place...
