### ISSUE TITLE
Unable to set custom mode

### ISSUE THREAD

**Issue by tyr84** [twrecked/hass-aarlo#195]
when trying to run the service _aarlo.alarm_set_mode_ I get this error:

  _File "/config/custom_components/aarlo/alarm_control_panel.py", line 407, in async_alarm_mode_service
    _LOGGER.info("{0} setting mode to {}".format(entity_id,mode))
ValueError: cannot switch from manual field specification to automatic field numbering_

The error message pretty much says it all

**Comment by twrecked** [comment]
Fixed in:
  https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.89-beta.3
  https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.18.1

**Comment by twrecked** [comment]
Closing. Reopen if not fixed!
