### ISSUE TITLE
Videodoorbell camera not working from last firmware update

### ISSUE THREAD

**Issue by jools4473** [twrecked/hass-aarlo#211]
Hi... Recently Arlo updated cameras and basestation firmwares in order to basestation be able to manage videodoorbell (not as a separated device) (it happens this week)
Since that its extrange because I cannot see the camera as an entity in HA but I can access the sensors like last motion, battery level, etc. 
I tried to restart all devices, review permissions, ... but video doorbell dont appears as a camera entity ...

Regards
![Captura](https://user-images.githubusercontent.com/50532576/78257768-aea09300-74d0-11ea-99a2-f0da28fa0494.PNG)

**Comment by twrecked** [comment]
Can you send me the model number of the doorbell? I wonder if it changed and I no longer consider it a camera. Go to "Developer Tools/States" and look for "sensor.aarlo_signal_strength_timbreentreda", it should have a `model:` field.

**Comment by jools4473** [comment]
Hi... its model: AVD1001B

thanks by the quick reply

**Comment by twrecked** [comment]
They changed the model number! I'll fix it and create a new release.

**Comment by twrecked** [comment]
It should be fixed by these PRs #212 #213 

It's in release [0.6.18.6](https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.18.6) and [0.6.89.beta.5](https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.89-beta.5)

**Comment by jools4473** [comment]
Now its working. Thanks!

**Comment by twrecked** [comment]
Excellent!

**Comment by twrecked** [comment]
Can I ask a favour? I need some help with this bug: #217 

Can you check the value of the device_id and parent_id for the camera device of the door bell. I don't need the actual values I just need to know if they are different or identical. You can find it under:

   `Developer Tools > States > camera.aarlo_your_doorbell_name`


Thanks!

**Comment by jools4473** [comment]
Hi,
It looks are different:

model_name: AVD1001B
brand: Netgear Arlo
battery_level: 91
battery_tech: Rechargeable
brightness: 0
flipped: false
mirrored: false
motion_detection_sensitivity: 80
signal_strength: 3
unseen_videos: 0
recent_activity: false
image_source: 'capture/04-04 21:14'
charging: true
charger_type: VAC Charger
wired: true
wired_only: false
time_zone: America/Santiago
attribution: Data provided by my.arlo.com
device_id: A2G19BK6A5F93
model_id: AVD1001B
parent_id: 4R03717EA6016
friendly_name: TimbreEntrada
siren: false

Regards
------ Mensaje original ------
De: "Steve Herrell" <notifications@github.com>
Para: "twrecked/hass-aarlo" <hass-aarlo@noreply.github.com>
CC: "jools4473" <jools44@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 06/04/2020 17:22:23
Asunto: Re: [twrecked/hass-aarlo] Videodoorbell camera not working from 
last firmware update (#211)

**Comment by twrecked** [comment]
I just re-read your email, you've already moved the doorbell to a base station. Sorry to bother you but thanks for the info!

Is it optional? Or can you still have the doorbell as its own base station?

**Comment by jools4473** [comment]
Yes i Think is optional and you can maintain doorbell independent of the base station.

I did because here in Chile we don’t have Arlo smart plans and thought with that change I could record video when motion is detected.. but until now it doesn’t record anything ... trying to figure how do that using node red


Regards

**Comment by twrecked** [comment]
That makes sense. I'll be pushing code to hide the alarm device when you don't use a doorbell as a basestation.

hass-aarlo provides a start recording service, can you hook that into node-red? You could certainly use an automation to hook into that.
