### ISSUE TITLE
missing import of HomeAssistantError in  __init__.py

### ISSUE THREAD

**Issue by jwws** [twrecked/hass-aarlo#214]
__init__.py lacks a definition for HomeAssistantError, leading to "NameError: name 'HomeAssistantError' is not defined" if a situation like an undefined camera name occurs in __init__.py:244 (or 247).

Adding "from homeassistant.exceptions import HomeAssistantError" clears that up to expose the actual error details.

**Comment by twrecked** [comment]
Annoyingly enough I just fixed that error my `hass-virtual` code. I'll check in a fix later.

**Comment by twrecked** [comment]
Fixed by PRs #215 #216

In latest releases.

**Comment by twrecked** [comment]
This is fixed. Closing now.
