### ISSUE TITLE
PyAarlo Error 2217 After Adding Video Doorbell To Basestation

### ISSUE THREAD

**Issue by MatthewGreen** [twrecked/hass-aarlo#217]
Hey!

After adding an Arlo Video Doorbell to my setup yesterday I've started seeing this error appear:

```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:136
First occurred: 10:19:18 AM (10 occurrences)
Last logged: 11:49:11 AM

error in response={'data': {'error': '2217', 'message': 'The device does not exist.', 'reason': 'Invalid uniqueId recieved.'}, 'success': False}
```

I've added the Video Doorbell to the Arlo Basestation and not as an independent device which I think is why this error is being thrown maybe? Oddly enough the Doorbell appears as a sensor and binary sensor just fine. It does however appear as an alarm control panel too which it should not since it's under the Basestation and not independent.

**Comment by twrecked** [comment]
I probably don't handle that setup correctly. The code current - wrongly... - assumes a doorbell is a separate device and automatically makes it a base station.

What version of the code are you on?

**Comment by MatthewGreen** [comment]
I'm on **v0.6.18.7** via HACS.

**Comment by twrecked** [comment]
Can you check the value of the device_id and parent_id for the camera device of the door bell. I don't need the actual values I just need to know if they are different or identical. You can find it under:

     Developer Tools > States > camera.aarlo_your_doorbell_name

Thanks!

**Comment by MatthewGreen** [comment]
Sure thing! Thanks for the Breadcrumbs too 👍 

Here are the details:
```
device_id: A2G19BKMA75B4
model_id: AVD1001B
parent_id: 4R05817FB10B8
```

**Comment by twrecked** [comment]
That could be the key to the fix. I just need to see what a system where it's a base too does! I know somebody who might be able to help!

**Comment by twrecked** [comment]
Is it optional? Can you still have the doorbell as its own base station?

**Comment by MatthewGreen** [comment]
Correct! During setup it strongly encourages you to use your existing base but does provide an albeit fine print option of it being its own base.

You lose the local storage option though if you set it up as its own base.

**Comment by twrecked** [comment]
Thanks. I might push a tentative fix and see if I break other people's installs. My theory is the parentid will be missing or the same as the deviceid if you use the doorbell as a base station.

**Comment by twrecked** [comment]
Fixed (hopefully!) by #218 ; try v0.6.18.8

**Comment by MatthewGreen** [comment]
Thanks so much! I don't see the error in the Logs anymore at this point. A few things that I've noticed that I wanted to point out though:

1. The Entity with ID: alarm_control_panel.aarlo_front_doorbell (my Video doorbell is named Front Doorbell) shows up still but has a state of unavailable. I think that the Alarm Control Panel for this "nested" Doorbell should not show up at all. Not sure if this is just a remnant from my config. As far as I can tell you catch this in your [init](https://github.com/twrecked/hass-aarlo/blob/bc5587fada34490a1dffeff4333bd2fe8f18656b/custom_components/aarlo/pyaarlo/__init__.py#L79-L82) by checking that if it's a Doorbell with no parent id or a parent id equals to the device id then set it up as a Basestation and if not, only append it to the Doorbells array.

1. I'm not sure if the [version](https://github.com/twrecked/hass-aarlo/blob/bc5587fada34490a1dffeff4333bd2fe8f18656b/custom_components/aarlo/pyaarlo/__init__.py#L26) should be bumped for this change.

Thank you so much! I really appreciate the quick fix!

**Comment by twrecked** [comment]
1. This is a home assistant "feature", my test system ends up with all sorts of orphan devices.  And I don't think you can remove them from the GUI.

2. Yes. I forgot! My real job was happening too! I'll fix it in the next release.

**Comment by MatthewGreen** [comment]
Thanks for the help man! Enjoyed the little troubleshooting session!
