### ISSUE TITLE
The duration of the video recording is not working

### ISSUE THREAD

**Issue by raelix** [twrecked/hass-aarlo#219]
Hi @twrecked, thanks a lot for this great component, I'm trying without success to set a different value for the duration of the video recording for my Arlo Ultra.

I tried both domains, aarlo and camera but without success, the saved videos are always equal to 31 seconds. 

The strange thing is that if I open the stream from my.arlo.com and I launch the aarlo_start_recording it works until I'm watching the stream, so the issues seems related to a keep alive on the stream connection, is there something that I can try? Any suggestions?

+ After two days of retries, seems that only if there is an active connection to the rtsp stream, the recording works as expected, do you think is there a possible workaround for this?

Thanks in advance

**Comment by twrecked** [comment]
The webgui and my code work differently, I just call the record function but on the GUI you can only do it from the live stream.

I can modify the code to do a stream start in the background and then start recording when the stream starts. The current mechanism for stopping would work fine. I'll also add an `aarlo_start_stream` and `aarlo_stop_stream` service. But you'd still need something reading from the stream to keep it active...

A workaround for now might be to call `camera.record` and push it to a file you don't care about and call `aarlo_start_recording` after that.

**Comment by raelix** [comment]
This would be fantastic!!!!! This feature could potentially allow the user to record for a long time after motion (also 24h) and do some advanced ML analysis. 

Is there something I can help you to test this? 

When you say something reading from the stream to keep it active, I think about a (possible) fake connection that every x seconds keeps the connection open, unfortunately i don't know if this requires ffmpeg or something similar that can impact on the performances. 

One more consideration (I don't know if you ever face this issue) is that with the Arlo Ultra when I take a snapshot, it is low quality (640x320), instead if there is a recording/stream it is in high quality (1920x1072). 

Do you think that the camera.record is not affected by this mechanism of checking alive connection?

Thanks you so much for your reply and for the big effort you make to maintain this component.

**Comment by raelix** [comment]
Hi @twrecked do you have any idea why the arlo ultra takes low quality snapshot if it's not recording, instead pro 2 high quality always?

thanks in advance

**Comment by twrecked** [comment]
It's an Arlo thing! Or the way I'm using it...

The call I make is different if the device is streaming/recording or not. If streaming it just pulls a frame out of the stream, if idle it wakes up the camera and takes a lower res picture.

I could probably enhance it to start the stream and take a snapshot. Make it optional.

**Comment by twrecked** [comment]
Fixed in 0.6.18.17 by PR #247 .

I'm looking at the improved snapshot for the 0.7 release but I'm closing this because the original bug is dealt with.
