### ISSUE TITLE
Aarlo Baby Light not controllable from frontend

### ISSUE THREAD

**Issue by Beertje135** [twrecked/hass-aarlo#221]
The state of the light is visible in home assistant, but I can't control it from there. E.g. If I turn it off after 1 sec the switch gets reset to the on state (or visa versa). If I click to see more info that doesn't do anything. Only when going to development tools and clicking the "i" will give me the more info view.

**Comment by Beertje135** [comment]
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:273
First occurred: 10 april 2020 16:21:15 (15 occurrences)
Last logged: 7:29:41

error in response={'data': {'error': '2016', 'message': "We are sorry, but you don't have permission to perform this action.", 'reason': 'No Such Permissions'}, 'success': False}
event loop timeout
request-error=ConnectionError
error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}

**Comment by sebr** [comment]
It’s working here for me - does the user which you are using to log into Arlo with HA have admin permission on the account?

**Comment by Beertje135** [comment]
I checked the admin access. This seemed to be the problem. I created a dedicated account for arlo before migrating to this plugin. I switched to the main account and everything works great!!
Sorry for the trouble and thanks for the reply.
