### ISSUE TITLE
invalid config imap_host

### ISSUE THREAD

**Issue by rick044** [twrecked/hass-aarlo#223]
After updating to the latest version of home assistant with no other change I now get

Invalid config for [aarlo]: [imap_host] is an invalid option for [aarlo]. Check: aarlo->aarlo->imap_host. (See /Users/dick/.homeassistant/configuration.yaml, line 63). Please check the docs at https://github.com/twrecked/hass-aarlo/blob/master/README.md

All was working fine before that

**Comment by twrecked** [comment]
Can you tell me what version of Home Assistant and Aarlo you are using?

**Comment by rick044** [comment]
Hi Steve,
thanks for your reply. I am using Home Assistant 0.108.3 and Aarlo v0.6.18.8
(through HACS).

**Comment by twrecked** [comment]
`imap_host` is only available in the beta releases and only needed for 2FA.

Try [0.6.89-beta.6](https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.89-beta.6) if you needed 2FA.

I'll update the README to make this clearer.

**Comment by rick044** [comment]
Thank you Steve. My mistake. Appreciate that.

**Comment by twrecked** [comment]
I'll close it. But are you using 2FA?

**Comment by rick044** [comment]
Yes, using 2fa. Its working now, I believe it was because I installed it
via HACS over top my manual beta download

**Comment by twrecked** [comment]
The naming of the releases is confusing at the moment - apologies for that.

So you're warned, in the next week or two I will be changing some configuration names:

`imap_host` --> `tfa_host`
`imap_username` --> `tfa_username`
`imap_password` --> `tfa_password`

I'm adding a new option for getting the code, a rest-api solution, and got tired of adding new parameters.
