### ISSUE TITLE
Doesn’t Aarlo support Arlo Go?

### ISSUE THREAD

**Issue by Golab** [twrecked/hass-aarlo#225]
Hello I own a Arlo Go, I have now installed and setup aarlo all my devices is showing up but not my Arlo Go, so my question is doesn’t Aarlo support Arlo Go Camera?

**Comment by twrecked** [comment]
It supports go. Does your second account have admin access?

**Comment by Golab** [comment]
You can close this ticket all worked again when I did a deep clean on all settings and reinstalled your add-on again
