### ISSUE TITLE
Extremely slow update on last video URL for Arlo baby

### ISSUE THREAD

**Issue by allenrong88** [twrecked/hass-aarlo#226]
Hi Steve,

Since you fixed the last video url to Arlo baby camera for me a while ago, and it still works as expected. The only issue I have found out since day 1 was that it sometimes takes 4-5 mins or even longer to get the URL updated when motion is detected. My normal Arlo Pro 2 system works like a charm, it updates itself as soon as motion is detected, however it does not happen to Arlo baby. 

Would you be able to re-visit it to see if we can get the experience a bit better please?

Thank you

**Comment by allenrong88** [comment]
I am using the latest Hass.io and the latest Aarlo component of course. 

Thx

**Comment by twrecked** [comment]
Do you still have this in your config:

```yaml
no_media_upload: True
```

**Comment by allenrong88** [comment]
Yes I do still in my config.

**Comment by twrecked** [comment]
Ok. I can tweak the update code, things may be happening too fast.

**Comment by allenrong88** [comment]
Cool, thanks Steve. 

As I mentioned earlier, video url bit on my Arlo Pro 2 works perfectly, maybe make Arlo baby align with the normal Arlo Pro?

Thx

**Comment by twrecked** [comment]
The code is the same for both. The problem is the Arlo Baby doesn't send a media upload notification so I have to manually ask for the new videos. I guess the timing on this is wonky.

**Comment by allenrong88** [comment]
Right~ That actually makes sense. Did not realize that Pro and Baby actually work so differently.

Happy to do further testings once your code is modified.

Thx again Steve.

**Comment by twrecked** [comment]
It's a bit of a pain and one of those things I had to work out the hard way because I don't have a Baby Arlo camera.

What version of Aarlo are you using?

**Comment by allenrong88** [comment]
v0.6.18.9, should be the latest one I can get from HACS.

**Comment by twrecked** [comment]
Can you try 0.6.18.10, it has PR #227 in it.

What this does is make more media update attempts when the recording stops.

**Comment by allenrong88** [comment]
Thx Steve. I will give it a shot and let you know how it goes.

**Comment by allenrong88** [comment]
Tried the build couple of days, still sitting around 3-4 mins so far. Thx

**Comment by twrecked** [comment]
I'm missing a state. I'll get a patch done.

**Comment by allenrong88** [comment]
Oh nice. Thx Steve like always!

**Comment by twrecked** [comment]
Can you try 0.6.18.16; it has PR #246 ?

**Comment by allenrong88** [comment]
Sure, I will give it a shot tonight. I assume the future release since 0.6.18.16 like 0.6.18.17 will include the fix you put in place? Thx

**Comment by twrecked** [comment]
Yes they will include it.

Did it work?

**Comment by allenrong88** [comment]
Thx Steve. It does work a lot better now. Happy to close the case and I will keep eyes on it.
