### ISSUE TITLE
Arlo Ultra spotlight is not shown in Home Assistant

### ISSUE THREAD

**Issue by chris-chensy** [twrecked/hass-aarlo#228]
Hello,

Thanks for making the great package for Home Assistant (HA). I have three Arlo Ultra cameras. The stream and snapshot functions are working nicely. However, when I integrate the light from the aarlo platform, only the arlo baby light shows up. None of my Arlo Ultra spotlights appears in HA. Could you please look into his and see if it is possible to include it?

Cheers,
Chris

**Comment by twrecked** [comment]
Do you have the model number? I need to explicitly tell the system they have lights.

**Comment by chris-chensy** [comment]
> Do you have the model number? I need to explicitly tell the system they have lights.
Hello twrecked,

Thanks for the prompt response. On the support page, it shows arlo ultra model VMC5040. I cannot find this in my arlo app thought. Hopefully there is only one model for ultra cameras as it’s fairly new. My base station has the model number VMB5000r4. I hope this helps.

Cheers
Chris

**Comment by twrecked** [comment]
I don't have an Arlo Ultra so we might have to try a couple of builds to get this working... I've just created [0.6.18.11](https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.18.11) and it treats the light the same at the Arlo Baby system. Can you let me know if it works?

If it doesn't work I'll try a build where I treat it as a straight light type.

**Comment by chris-chensy** [comment]
> I don't have an Arlo Ultra so we might have to try a couple of builds to get this working... I've just created [0.6.18.11](https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.18.11) and it treats the light the same at the Arlo Baby system. Can you let me know if it works?
> 
> If it doesn't work I'll try a build where I treat it as a straight light type.

Thanks for the prompt update. I have updated the build to [0.6.18.11] and restarted the HA system, but I still cannot see the light from Arlo Ultra. In fact, the spotlight on Arlo Ultra only had the function of on/off in the arlo app. Unlike the Arlo baby light, it doesn't let you adjust the light intensity/color, etc.

**Comment by twrecked** [comment]
It's probably a standard light then. It should have appeared in your device list you just wouldn't have been able to operate it. Give me an hour or two, we'll try the other way.

**Comment by sebr** [comment]
I have an ultra @twrecked - do you want me to take a look and wire it up?

**Comment by chris-chensy** [comment]
> It's probably a standard light then. It should have appeared in your device list you just wouldn't have been able to operate it. Give me an hour or two, we'll try the other way.
> 
> edit: My apologies, that build was wrong. I'm running a 0.6.xxx build because I'm got a whole new build coming along and 0.6.18.11 was packaged from the wrong thing. Can you try 0.6.18.12.

I have just tested the build .12. I can see all my lights shown on the state list. However, when I send the turn on service, it doesn't do anything...

When I turn on the light in the app, the light states do not get updated either. It kept saying off all the time. I did a little test about the light. It seems the light is only accessible when the camera is streaming. When I stopped streaming, the light went off automatically. I'm not sure if this affects the functioning in HA.

**Comment by twrecked** [comment]
Should be fixed by #232 ; many thanks to @sebr 

Can you try build .13

**Comment by chris-chensy** [comment]
> Should be fixed by #232 ; many thanks to @sebr
> 
> Can you try build .13

Much appreciated, @twrecked @sebr! 

It's worth pointing out that the spotlight cannot be turned on until the camera starts streaming. I can toggle the light switch anytime. If the camera is not streaming or recording, the light would not be on even the state becomes on. Maybe this is limited by the hardware. 

The current function fits my purpose perfectly. I just want the light on when the camera is recording. Good work guys!

**Comment by chris-chensy** [comment]
> Should be fixed by #232 ; many thanks to @sebr
> 
> Can you try build .13

after updating to .7 alpha, all the arlo ultra lights became unavailable. Restarting HA does not help... It worked in the .6 versions since you fix it earlier. Could you please have a look? The state is shown below.
![image](https://user-images.githubusercontent.com/62833257/87246310-f9e31e00-c48f-11ea-9137-74913f4ff1b4.png)

**Comment by twrecked** [comment]
I'll take a look. I might have merged things wrong.

**Comment by chris-chensy** [comment]
> I'll take a look. I might have merged things wrong.

Thank you for the fast response!

**Comment by twrecked** [comment]
That's the issue. I'd missed some code in the light component during a merge. I'm making sure the code still runs and I'll upload a fix.

**Comment by twrecked** [comment]
It's fixed in the master branch by #280 

I'll get a new alpha release out later.

**Comment by twrecked** [comment]
Closing because I'm assuming it's working now.
