### ISSUE TITLE
Invalid Option request_timout

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [twrecked/hass-aarlo#229]
Hi,

I just followed through some of the options for avoiding lockout issues on the front page.

When I try and set request_time, I get the following warning while checking my config:

`Invalid config for [aarlo]: [request_timout] is an invalid option for [aarlo]. Check: aarlo->aarlo->request_timout. (See /config/configuration.yaml, line 131). `

**Comment by twrecked** [comment]
It's request_timeout - you missed an E in your config.

**Comment by danieledwardgeorgehitchcock** [comment]
Ah! thanks!

I copied the entry from the following section:

[request_timout](https://github.com/twrecked/hass-aarlo#best-practises-and-known-limitations)

**Comment by twrecked** [comment]
Damn my fingers... I'll fix the docs.
