### ISSUE TITLE
Entity id already exists error

### ISSUE THREAD

**Issue by tnunamak** [twrecked/hass-aarlo#248]
Hi there, thanks for the plugin!

I just refactored my entire HA configuration, so I don't know exactly what happened but now all of my aarlo entities are producing this error:

```
2020-05-14 03:30:30 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.aarlo_arlo_cameras. Platform aarlo does not generate unique IDs
```

I noticed that there was a fix deployed to address this at some point, but I have the latest version of the plugin so maybe there's something different going on in my case.

Any ideas? If there's a simple way to reset everything to a blank slate, that would be fine.

**Comment by twrecked** [comment]
Can you paste you sensor configuration in here?

**Comment by tnunamak** [comment]
Sorry, this was a configuration mistake on my end. I think the culprit was declaring the alarm_control_panel as a sensor.
