### ISSUE TITLE
HA 110 BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by dlo747** [twrecked/hass-aarlo#255]
Running Hassio 110, released 5/20/20.

Keeps throwing error code 
`BinarySensorDevice is deprecated, modify ArloBinarySensor to extend BinarySensorEntity`

Thank you in advance

**Comment by dlo747** [comment]
Same issue as #249 

Will close this one out

**Comment by twrecked** [comment]
You probably saw in the other but fixed with PR #256 and in release 0.6.19.

Thanks for opening (and closing) this. With my real job it can pain keep tracking of all these HA changes.
