### ISSUE TITLE
Don't add unsupported entities?

### ISSUE THREAD

**Issue by Swiftnesses** [twrecked/hass-aarlo#26]
Howdy,

As you know, HA is a state machine animal, could we possibly not add unsupported entities on older cameras, i.e. sound...?

**Comment by twrecked** [comment]
It should do that.

Can you tell me which camera model is having issues? Because of a Home Assistant chicken/egg startup issue I have to hard code capabilities into the source code.

**Comment by Swiftnesses** [comment]
I'm a numpty, ignored the fact I was using the custom glance and hadn't modified the entities, geez...
