### ISSUE TITLE
Temporary disable Aarlo integration

### ISSUE THREAD

**Issue by sabbrowne** [twrecked/hass-aarlo#261]
Hi this is really an issue more a possible enhancement. 
I often need to log into to the my.arlo to make config changes to cameras etc.
But each time I login to my.arlo website or use the mobile app I get logged out too quickly to make the changes as the Aarlo integration logs in regularly for status checks and therefore logs me out of the app or my.arlo
Is there a way to temporarily stop HA from login? At the moment I have to remove integration from configuration.yaml file... make the changes in Arlo app or my.arlo... then restore configuration and restart HA.
Or perhaps I am missing a simple way that already exists. If not it would be great to set up a lovelace card to use input select command (ie Status to disable/enable) to stop Aarlo login for a defined time.

By the way great work on your current Aarlo integration... It's rock solid

Regards Shane

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo/blob/master/README.md#creating-a-login

**Comment by steleary** [comment]
Shane, it is recommended to create a second login for your HA integration.

**Comment by sabbrowne** [comment]
Thanks folks...
I have did create a second account, which was successful, but for some strange reason it is not linked to my main Arlo account and therefore no devices evident.
To create the account I used the original/main Arlo app method sending email link to another user to access and control... I then clicked link in email... I had to create new account... but then the new account is not linked... This method seams very flakie to me... I have tried several versions of doing this but the account never see my devices...
Anyway I'll try again... sigh :-)
Cheers

Shane

**Comment by Siege36** [comment]
After creating your secondary account, you will need to log in to your main account and give your new account access to your devices before they will show up.

**Comment by sabbrowne** [comment]
Siege36. Yes that did the trick. Thanks
I am sure i did the same before.... but didnt work.. Perhaps Arlo servo was broken :(
