### ISSUE TITLE
cannot get my config to work

### ISSUE THREAD

**Issue by staticgroup** [twrecked/hass-aarlo#266]
hey team, 
this is the config I have setup:
`aarlo:
    username: passord@staticgroup.com.au
    password: passowrd
    refresh_devices_every: 2
    stream_timeout: 120
    alarm_control_panel:
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
binary_sensor:   
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity`

This is the error log I get :
Invalid config for [aarlo]: [sensor] is an invalid option for [aarlo]. Check: aarlo->aarlo->sensor. (See /config/configuration.yaml, line 51).
Invalid config for [binary_sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 67). Invalid config for [aarlo]: [sensor] is an invalid option for [aarlo]. 
Invalid config for [binary_sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 67). Invalid config for [arlo]: [refresh_devices_every] is an invalid option for [arlo]. Check: arlo->arlo->refresh_devices_every. (See /config/configuration.yaml, line 51). 
Component error: monitored_conditions - Integration 'monitored_conditions' not found.

**Comment by sebr** [comment]
This is likely a problem with YAML syntax/indentation. If you can try edit your post and use the `< >` icon in the editor toolbar to preserve whitespace it would make it easier to help you.

**Comment by sconnery** [comment]
I assume you mean in the hassio editor
________________________________

**Comment by sebr** [comment]
no, here in github

**Comment by sconnery** [comment]
I dont believe it is as there is no errors in editors.

________________________________

**Comment by sebr** [comment]
Regardless, if you want some help you'll need to paste your config here in a formatted way, otherwise it's impossible to debug and help you

**Comment by sconnery** [comment]
Ah thats a valid point ! Sorry ill review
________________________________

**Comment by staticgroup** [comment]
thank you @sebr I updated the code in the wrapper as requested.

**Comment by sebr** [comment]
Hey Steven @staticgroup,

1. Please go and change your username/password immediately :)
2. Please use three backticks to use a code block see here https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by staticgroup** [comment]
omg cant believe i did that
thanks for the call out!

**Comment by staticgroup** [comment]
got most of my config to work , now just trying to get the doorbell to register so i can add it

**Comment by staticgroup** [comment]
I figured out my final issue (was the account I was using) was a good learning experience
