### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by chavez7** [twrecked/hass-aarlo#267]
I tried to update to version 0.110, doing the check first, and a lot of errors came. including this:

Platform error alarm_control_panel.aarlo - cannot import name 'AlarmControlPanelEntity' from 'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)

**Comment by twrecked** [comment]
Which version of Aarlo are you on? The latest needs 0.110 to run and that error is indicating your Home Assistant is 0.110.

Steve

**Comment by RichmonS** [comment]
I have gotten the same message on my logs today.  I also see that my camera feeds are no longer displaying on my lovelace:

Supervisor Version 226
HassOS 4.8
Home Assistant 110.4

**Comment by RichmonS** [comment]
> I have gotten the same message on my logs today. I also see that my camera feeds are no longer displaying on my lovelace:
> 
> Supervisor Version 226
> HassOS 4.8
> Home Assistant 110.4

I appears that a reboot made the error go away.  I am going to see if the error comes back.

**Comment by twrecked** [comment]
Any updates?

**Comment by twrecked** [comment]
Closing because I'm assuming it's working now.
