### ISSUE TITLE
Door Bell Button work as a Switch

### ISSUE THREAD

**Issue by jaburgeson** [twrecked/hass-aarlo#269]
Curious, is there is a way to make the Video Door Bell button work as a Switch instead of the Binary Sensor?

**Comment by twrecked** [comment]
Anything is possible. What are you hoping to do? The doorbell doesn't provide an on/off mechanism I can control.

**Comment by twrecked** [comment]
Closing because there is no way to make the doorbell a switch. There is no way for me to turn it on or off.
