### ISSUE TITLE
Configuration error: binary sensor 'connectivity' not allowed?

### ISSUE THREAD

**Issue by rex** [twrecked/hass-aarlo#275]
Having an issue getting aarlo set up. Using the documented config to try and get started, but I'm seeing an error when checking the configuration:

```
Invalid config for [binary_sensor.aarlo]: value is not allowed @ data['monitored_conditions'][4]. Got 'connectivity'. (See ?, line ?). 
```

Here is the relevant excerpt from my `configuration.yaml`:

```yaml
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity
```

I can get past it by commenting it out, but I would rather be monitoring connectivity state if possible. Is this an error anyone else is seeing? 

I am running the latest stable version `v0.6.19.1`. 

Help?

**Comment by twrecked** [comment]
It's not available in 0.6 stream. Try the latest 0.7, it should appear on HACS because I had to mark it a non pre-release.

I will be moving 0.7 out of alpha in the next week or two.

**Comment by rex** [comment]
@twrecked Not a problem, thank you for responding so quickly! And thank you for all the work you have done/are doing on the aarlo component. You make a lot of people's lives easier :) 

Just curious, will _streaming_ ever be possible with the `aarlo` integration? Or are there limitations that only allow recent videos to be viewed?

**Comment by twrecked** [comment]
What cameras do you have?

**Comment by rex** [comment]
@twrecked I have 6 of the original Arlo Pro cameras. At some point might upgrade to the nicer ones but the normal 720p ones work for my purposes.

**Comment by twrecked** [comment]
I have the same cameras. Streaming should work for you. You need to enable the streaming component, add this to `configuration.yaml`:

```yaml
stream:
```

And then configure the lovelace card to stream either by clicking on the image or adding a play button. Either of these options will do it:

```yaml
show:
  - play

image_click: play
```

**Comment by rex** [comment]
@twrecked Sorry for the delay. Your instructions worked perfectly, and I now have your awesome Arlo cards running like a champ on a new lovelace board! 

This is actually my first foray into doing anything custom with lovelace, and I'm already addicted. Thank you for walking me through this and getting me set up!

**Comment by twrecked** [comment]
Glad it's working. I'll close this.
