### ISSUE TITLE
Unique ID's Based on Serial Number, Rather Than Device Name?

### ISSUE THREAD

**Issue by MizterB** [twrecked/hass-aarlo#279]
I see that the code currently generates unique IDs for entities based on a device's name.  Would it be possible to change this to the device's serial number?  The serial number is displayed in the Arlo web UI under Device Info - if the API isn't already grabbing this value, I suspect it wouldn't be hard to add.

I believe it would be preferable to have the unique ID truly tied to a unique value that does not change.  A device's name can change regularly.  In my case, a camera might not always be moved back to its original position after charging, and may be renamed accordingly.  However, changing a name then affects entity_ids, which breaks other elements of automation, Lovelace, etc.

**Comment by twrecked** [comment]
I have a branch that does this - [here](https://github.com/twrecked/hass-aarlo/tree/device_id).

It's probably out of sync but I'll look to see how much work it is to get it into 0.7.

**Comment by MizterB** [comment]
Sounds great.  Thank you!

**Comment by sebr** [comment]
@twrecked since this will be a breaking change (HA will create new entities and the existing ones will be orphaned), wdyt about updating the integration's version number to `1.0.0` ?

**Comment by twrecked** [comment]
@sebr It was configurable with the default set to the current mechanism.

**Comment by twrecked** [comment]
There is some code for this in 0.7.0.alpha.8, look up `serial_ids` in the docs.

**Comment by twrecked** [comment]
Closing because I'm assuming it's working now.
