### ISSUE TITLE
Sound binary sensor not working anymore

### ISSUE THREAD

**Issue by blair287** [twrecked/hass-aarlo#281]
The sound binary sensor is showing unavailable config hasn't changed and sound is listed under binary sensor but home assistant shows unavailable with red !

Was working until updated to latest version.

Rolling back to version before current it is working ok

**Comment by twrecked** [comment]
Just double checking - 0.7 didn't work but latest 0.6 does?

**Comment by dermotduffy** [comment]
FWIW: I am seeing the same behavior, 'binary_sensor.aarlo_XXX' is now showing. as unavailable ("This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device. If the entity is no longer in use, you can clean it up by removing it.").

**Comment by twrecked** [comment]
I can see the issue. I have to use `device_type` not `model_id` to check for Arlo Q cameras.

I'll check in a fix.

One question, can you paste the model ID of your Arlo Q cameras?

**Comment by twrecked** [comment]
Should be fixed with #282 

I'll create a new release later today.

**Comment by blair287** [comment]
> Should be fixed with #282
> 
> I'll create a new release later today.

Thanks :)

**Comment by twrecked** [comment]
I just released 0.7.0.alpha.8 which should fix this.

**Comment by twrecked** [comment]
Closing because I'm assuming it's working now.
