### ISSUE TITLE
Mode schedule is unrecognised

### ISSUE THREAD

**Issue by Spiff1** [twrecked/hass-aarlo#288]
In an automation I can set any custom mode but I would also like to have the possibility to set the default mode 'schedule'. For some reason i get an error in the log file saying 'Mode schedule is unrecognised' 
Is it not possible to activate the schedule mode or am I doing something wrong?

In configuration.yaml:
```
alarm_control_panel:
  - platform: aarlo
    home_mode_name: 'Schedule'
```

**Comment by twrecked** [comment]
We should be able to handle that but the code might not have been too well exercised. We need to make sure it's actually called `Schedule`. Can you turn on logging:

```yaml
logger:
  default: info
  logs:
    pyaarlo: debug
    custom_components.aarlo: debug
```

You'll need to restart `home assistant` and look for something like this in the logs:

```log
2020-07-28 23:38:47 DEBUG (ArloBackgroundWorker) [pyaarlo] schedule.1<=S=>schedule.1
```

You have to use the name on the right of the `<=S=>`.

**Comment by twrecked** [comment]
One more thing. If you find the name and don't want to keep restarting you can test the name using the `aarlo.alarm_set_mode` service.

**Comment by Spiff1** [comment]
Thanks, I found the log entry and it was like your example, changing the configuration to 'schedule.1' solved the issue and it is now possible to activate the schedule mode in Arlo,
```
alarm_control_panel:
  - platform: aarlo
    home_mode_name: 'schedule.1'
```

Thanks for the help and support.

**Comment by twrecked** [comment]
Glad it's working.

I'll close this for now.

**Comment by Spiff1** [comment]
Hello again

I just upgraded my base station to Arlo 3 pro and I have issues with setting the schedule mode again. No problem to sed disarm, arm and my custom armed mode bus schedule don't work.

In the log file the name seems so have changed to "Arm camera M-F 8-5" but if I use that mode name in the configuration.yaml Arlo change mode to something unknown but not to the schedule mode.

2020-10-27 21:06:57 DEBUG (ArloBackgroundWorker) [pyaarlo] schedule.1<=S=>Arm camera M-F 8-5

Any tips?
