### ISSUE TITLE
Is Arlo Q support still possible?

### ISSUE THREAD

**Issue by jerryzou** [twrecked/hass-aarlo#290]
Big thanks for all the amazing things from hass-arrlo. Love it!

Apart from some Arlo 2 cameras, I've got an Arlo Q plus and it worked really well with hass-aarlo early versions. I remember the streaming stopped working because of a certain update from Arlo's end. Though the snapshot still worked and was very useful for the deepstack add-on.

Because 0.7 alpha has started using straming for snapshot, Arlo Q could not take snapshot anymore. Just wondering -
1. Is it possible to make streaming work again for Arlo Q?
2. If not, is it possible to make only Arlo Q take snapshot the old way?

**Comment by twrecked** [comment]
My plan is to fix snapshot this week. I was playing around with the back end and got streaming+snapshots working great and then all of a sudden, it stopped working.  It looks like Arlo changed something at their end. I've got to play some more and see what works best but I'm thinking of making it all configurable so people can work out what works best for them.

Also, you can see if [this](https://github.com/twrecked/hass-aarlo/issues/151#issuecomment-659567535) gets your streaming working again.

**Comment by jerryzou** [comment]
Thanks a lot for taking a look into this.
Here is how it went with the workaround you mentioned:

-I'm running latest versio of hassos + homeassistant on pi4b
-updated aarlo to 0.7.0 alpha 8.1
-updated card to 0.1.3
-added user_agent: linux to aarlo conf
-added play_direct: true to 4 alro 2 card entities and 1 arlo q entity

The test result seemed to be quite strange. Out of 10 streaming tests on each cam, it succeeded only 1 time on the arlo q and 1 time on one of the arlo 2 cams. Then I did 10 snapshot tests on each cam. All worked on arlo 2 but not once on arlo q. It showed the "Taking Snapshot" message for a long time but the image didn't update. Though the image on the card actually update itself once in a while automatically...

Just in case of network issues, I restored the configuration and switched the aarlo back to 0.69.1. Everything worked again and it acturally responded quite fast.

Please let me know if you'd like me to do more test. Wish I could help while you're trying to crack the devil. :)

**Comment by twrecked** [comment]
I reverted the snapshot changes in beta.1 hopefully that fixes that issue.

The streaming is annoying, it's not working for me at the moment either. I guess I'll have to revisit the lovelace card. Behind the scenes it looks like everything is working but the video isn't appearing.

**Comment by twrecked** [comment]
Turns out the streaming might have been the dashjs player version I was using. Lovelace 0.1.4 fixes it for me.

If you don't mind playing: aarlo:0.7.0.beta.1 + aarlo-glance:0.1.4 and `user_agent: linux` might work now.

**Comment by jerryzou** [comment]
Will give a go and report back shortly.

**Comment by jerryzou** [comment]
- I've updated to aarlo:0.7.0.beta.1 + aarlo-glance:0.1.4 via HACS and set the user_agent to linux
- restarted HA
- the aarlo-glance card didn't load correctly showing:

Custom element doesn't exist: aarlo-glance.
type: 'custom:aarlo-glance'
entity: camera.aarlo_living_room
name: Living Room
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - signal_strength
  - captured_today
  - image_date
top_title: true
top_status: false
top_date: true
image_click: play
play_direct: true

- reinstalled aarlo-glance 0.1.3
- the card worked again

**Comment by jerryzou** [comment]
Sorry I forgot to mention the snapshot works fine now. :)

**Comment by jerryzou** [comment]
Turns out I'll have to load dashjs via https because my HA instance is under https
- manually edited http://cdn.dashjs.org/v3.1.1/dash.all.min.js to https://cdn.dashjs.org/v3.1.1/dash.all.min.js
- the card loaded successfully
- the streaming worked great (faster than before, only took 2-3 seconds to start playing) for all the arlo 2 cams. Though sadly, it didn't work for the arlo q plus (the streaming wouldn't start at all)
- snapshot on all cams worked great

**Comment by twrecked** [comment]
I'll definitely update the dash url. I was trying on a local connection and missed that.

Do the Arlo Q cameras work on the official web site - my.arlo.com?

**Comment by jerryzou** [comment]
This is getting interesting...
I've tried quite a few times (click that "live" button) on the Q with the official website. It only streamed once. all other time it only shows "please wait" until "request timed out".
Though the arlo 2 cams works consistently on the official site.
The Q shows full wifi signal and I have a good pretty good internet connection.

**Comment by jerryzou** [comment]
I've done some further test.
Compared with the official web portal, the official app has a better chance (around 40%) to start a live stream.
However, the lag is like 40 seconds!
Kind of feel like this is some issue at Arlo's end.
Is there anyone else here with an Arlo Q behaving the same?

**Comment by twrecked** [comment]
I don't have any Q cameras but I've noticed some strange behavior recently on the official web site - my older cameras not updating as much. My feeling is they are preparing to move away from flash and issues keep popping up.
