### ISSUE TITLE
Feature Request: Snapshot Thumbnails Available in HA file structure

### ISSUE THREAD

**Issue by CrouchingWorm** [twrecked/hass-aarlo#292]
Hi there,
Love this integration, thanks so much.
This probably isn't the right forum to ask for a feature.. Sorry, wasn't sure where else to ask.

I was wanting to have the ability to have the uploaded thumbnails available for use locally within HA.
I wanted to use them in a glance card (different to your excellent one)...
At the moment you provide a url via an attribute in the aarlo camera entity.

Do the files reside somewhere in the HA file structure?

**Comment by twrecked** [comment]
We don't have that right now but I don't think it would a huge piece of work to add it. We already have a service to write a snapshot out to a file. 

I would just need to modify `ArloCam` to write out a file every time the latest image changes.

**Comment by CrouchingWorm** [comment]
You're awesome. Thanks so much.
I'm currently triggering a script based on an update event. Bit clunky.

Thanks again!

**Comment by twrecked** [comment]
Can you try the latest build - 0.7.0.beta.2 - I added the `save_updates_to` option. For example:

```yaml
aarlo:
  .. your current config
  save_updates_to: /config/www
```

**Comment by CrouchingWorm** [comment]
You're awesome. I'll give it a go.
Thanks so much!

**Comment by CrouchingWorm** [comment]
Thanks again.
Worked a treat.
