### ISSUE TITLE
Slow play back

### ISSUE THREAD

**Issue by o10c01o** [twrecked/hass-aarlo#294]
Not sure if this is the correct place to ask, but is the play back for streaming really slow? I am seeing around 7-15 seconds delay. This is from the mobile app and also from browser. Using Arlo pro 2 cameras. Thanks!

**Comment by twrecked** [comment]
That sounds about right. The stream has to go from the camera into arlo servers and back out again, into Home Assistant and then back to you.

If you use the `aarlo-glance` Lovelace cards you can try [direct streaming](https://github.com/twrecked/hass-aarlo/issues/151#issuecomment-659567535) to see if that helps speed things up.

**Comment by o10c01o** [comment]
Thank you for the quick response! I'm currently using direct streaming already with aarlo-glance and user-agent: linux set. Sounds like this is just the nature of the data path.
