### ISSUE TITLE
Received Notifications after initial setup

### ISSUE THREAD

**Issue by alsoszaa** [twrecked/hass-aarlo#296]
Sorry, This isn't really much of a bug, but more of a setup help request. I am a complete nube to Home Assistant. I am trying to install AArlo through the HACS. In HACS integrations, I installed the repository. Then I looked at the instructions. I copied the folder from the zip file to /config/custom_components. The next part you say to install it from script. This is where I am not sure where to do this. that may be what I am missing? but then I added the arlo user/pass to my secrets.yaml and referenced the login in configuration.yaml and copied some of the configuration code to my configuration yaml. then I restarted Home Assistant. Then I see these two notifications. Honestly there isn't much about installing this with more of a step by step for beginners. Like I said I believe I just don't know where to run the install commands. maybe this is what I was missing. But any help is appreciated.

I am running the following:

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Ubuntu 20.04.1 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.4.0-42-generic
python_version | 3.8.3
supervisor | 229
timezone | America/Los_Angeles
version | 0.113.3
virtualenv | false

(running in docker, through ubuntu host)

Two Notifications after install:
______________________________
aarlo Component Setup
Error: authentication failed
You will need to restart hass after fixing.

______________________________
Invalid config
The following integrations and platforms could not be set up:

aarlo
aarlo.alarm_control_panel
aarlo.binary_sensor
aarlo.camera
Please check your config.

**Comment by twrecked** [comment]
If you install using HACS you don't need to do anything else other than restart. And it looks like that bit worked because you are seeing the message `Error: authentication failed`.

If the authentication fails then nothing else Arlo related will work.

Two things to check:
* make sure your username/secrets is correct in `secrets.yaml`
* the layout of `configuration.yaml`, the spaces are really important

**Comment by alsoszaa** [comment]
Thanks! I use 2FA in my arlo account. I think I need to implement that bit.
where do I place the config for that? In configuration.yaml? If so, does it need to go indented in the aarlo section? You have:
  tfa_host: imap.gmail.com
  tfa_username: your.email.account@gmail.com
  tfa_password: roygbiv
Obviously, I need my own information.

Sorry to use your time on this, and I really appreciate the help!
I also installed the awesome frontend lovelace through HACS as well. Is there anything special to do after its installed through HACS?

**Comment by twrecked** [comment]
You need to do exactly that. You need some more info to make sure it uses email.

```yaml
aarlo:
  ..your existing config..
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.host.com
  tfa_username: your-user-name
  tfa_password: your-imap-password
```

**Comment by alsoszaa** [comment]
Thanks! I've added that. i looked at the imap settings for my email provider (outlook.com) and it also says it uses IMAP port 993 and IMAP encryption method TLS. These are already assumed in your config? 

And to the point that spaces are critical in the config. I copied this directly out of my config. The config shows the green checkbox and I ran the config check which said my config was valid:

# Arlo config using AArlo installation via HACS
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: imap
  tfa_type: email
  tfa_host: outlook.office365.com
  tfa_username: xxxxxx@outlook.com
  tfa_password: xxxxxx
  refresh_devices_every: 2
  stream_timeout: 120
  
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 10
    alarm_volume: 3

camera:
  - platform: aarlo
  
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity

**Comment by alsoszaa** [comment]
oops.. looks like github reformatted it, I'll try it within a code block...

`# Arlo config using AArlo installation via HACS
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: imap
  tfa_type: email
  tfa_host: outlook.office365.com
  tfa_username: alsoszaa@outlook.com
  tfa_password: fqwzocwbudjwjhgf
  refresh_devices_every: 2
  stream_timeout: 120
  
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 10
    alarm_volume: 3

camera:
  - platform: aarlo
  
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity`

**Comment by twrecked** [comment]
We only support encrypted IMAP so the connection should work. I haven't tested the code against an outlook server - I don't have access to one - but I don't see any reason why it won't work.

If you run into problems you can turn on debugging to help us track down why. Add the following to `configuration.yaml`.

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    pyaarlo: debug
```

**Comment by alsoszaa** [comment]
hmmm. That's not how it looks. github reformatted it.
![image](https://user-images.githubusercontent.com/16808447/89593042-0181b280-d803-11ea-9651-1b9806dd7bee.png)

**Comment by twrecked** [comment]
That looks good. You can also specify your IMAP username and password in the `secrets.yaml`.

For formatting you need to add 3 backticks and the word yaml. And end it with 3 backticks. Like this without the indents...

```
    ```yaml
    aarlo:
       username: your-name
    ```
```

**Comment by alsoszaa** [comment]
Thanks a ton!!!

**Comment by alsoszaa** [comment]
Yay! It works! Thank you very much! 
One last thing, Is it possible to move these entities into an "Area"? I like to make sure things are in their respective Area.

Thank you again!

**Comment by twrecked** [comment]
What do you mean by area? You mean like a room? They are just standard home assistant objects so can be moved anywhere.

**Comment by alsoszaa** [comment]
Okay. I'll research that... Told you I'm a noob. hahaha. Thank you again! Consider this resolved!

**Comment by twrecked** [comment]
I never really got around to putting everything into rooms. I just ended up with a bunch of tabs across the top of the user interface and using group Lovelace cards to keep the items together.

Glad it worked. I'll make a note that at least one person has got it going against outlook!

**Comment by alsoszaa** [comment]
I wanted to let you know that because I used the same arlo account to connect to AARLO for HomeAssistant that I use to connect to my phone app for arlo, it constantly disconnects me. What I had to do was create a 2nd account in arlo under another email address so that HA managed one account and I manage my own account without getting kicked out.

**Comment by twrecked** [comment]
That is a known limitation of Arlo - see [here](https://github.com/twrecked/hass-aarlo#creating-a-login). Make sure to give it admin access or else some sensors might not work.
