### ISSUE TITLE
0.7.0-beta.2 errors in log

### ISSUE THREAD

**Issue by sebr** [twrecked/hass-aarlo#300]
Hey @twrecked - since upgrading to the latest beta I'm consistently seeing the following error in the log:

```
2020-08-14 09:22:56 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/background.py", line 35, in _run_next
    job['callback'](**job['args'])
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 278, in _refresh_bases
    base.update_modes()
  File "/config/custom_components/aarlo/pyaarlo/base.py", line 253, in update_modes
    props = resp.get('properties', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by twrecked** [comment]
I'll take a look. It was probably always there but I never printed the back trace out before. You can look for `AttributeError` in any old logs you might have.

**Comment by twrecked** [comment]
I reproduced this by forcing v1 of the mode change api. I look into a fix.

**Comment by sebr** [comment]
@twrecked okay thanks - I am only using `alarm_control_panel.alarm_arm_night` and `alarm_control_panel.alarm_arm_home` with the `lights` and `camera` devices.

I'm not using it with the Arlo baby devices, because of the limitation of having the same mode names across all devices.

**Comment by twrecked** [comment]
This should be fixed in `beta.3`.

**Comment by sebr** [comment]
Looks great, thanks Steve!
