### ISSUE TITLE
unable to read mode, try forcing v2

### ISSUE THREAD

**Issue by mikesalz** [twrecked/hass-aarlo#306]
I get this once or twice a day.  Not sure what it means, but just wanted to pass it on to you.  Does "try forcing v2" mean there is something I can do to fix the issue?

> Log Details (ERROR)
> Logger: pyaarlo
> Source: custom_components/aarlo/pyaarlo/__init__.py:504
> First occurred: August 27, 2020, 10:45:53 PM (1 occurrences)
> Last logged: August 27, 2020, 10:45:53 PM
> 
> unable to read mode, try forcing v2

**Comment by twrecked** [comment]
What kind of cameras are you using? Do you have an Arlo Baby or Q?

It looks like Arlo has changed their back end recently and the mechanism I use to get the modes for the aforementioned cameras doesn't work anymore. Does setting the mode work? And you can try adding this to you Arlo config to see if everything still works:

```yaml
aarlo:
  mode_api: v2
```

**Comment by mikesalz** [comment]
I have the Arlo Baby and Arlo Ultra. I will add mode to my config to see if that helps. Thanks so much!

**Comment by mikesalz** [comment]
@twrecked An update:  I added `mode_api: v2` 4 days ago, and have not seen the error since.  Thanks again for your help!!

**Comment by twrecked** [comment]
Closing, re-open if it starts failing again.
