### ISSUE TITLE
Which camera is supported?

### ISSUE THREAD

**Issue by Golab** [twrecked/hass-aarlo#317]
Which Arlo cameras is supported white stream video and sound? Is Arlo pro supported? Is Arlo camera supported?

**Comment by twrecked** [comment]
The Pro and non-pro are supported. They are the ones I use.

**Comment by twrecked** [comment]
If a camera is advertised as having a microphone we should be able to play sound on it. Especially with direct streaming from Arlo.

I'll close this for now.
