### ISSUE TITLE
binary_sensors for motion get created but never change state

### ISSUE THREAD

**Issue by elijah286** [twrecked/hass-aarlo#332]
I've never successfully had the binary_sensors work for motion detection with this module. I have 12 cameras across three different hubs, which are a mix of Pros, a Pro 2, and 5 Ultras

The binary sensors are correctly generated with no configuration errors, but always show as 'off.' 

Related, the sensor.aarlo_captured_today_name update correctly (based on corresponding logged videos with same timestamp)

I enabled logging, but I don't see any errors.

> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Cats created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Back Door created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Spare created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Alley created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Sloane created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Backyard created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Patio created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Playscape created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Garage created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Front Porch created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Front Yard created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Driveway created
> 2020-10-21 16:46:53 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Gate created

**Comment by twrecked** [comment]
Does your home assistant Arlo account have admin access?

If so, can you look through the logs for `motionDetected`? It will look like:

```
2020-10-21 20:09:01 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/XXXXXXXXXXXXX/motionDetected=True
```

**Comment by elijah286** [comment]
It did not! I didn't realize that was required.. hopefully that will fix it. Thank you!

**Comment by twrecked** [comment]
Closing, assuming it worked!
