### ISSUE TITLE
Alarm control panel doesn't update status

### ISSUE THREAD

**Issue by wonderbraun** [twrecked/hass-aarlo#338]
Hello I'm new to home assistant.
First of all I want to thank you (and all the community) for the excellent work.
I set up everything and seems to work fine but in the alarm control panel card the status (armed or not) takes a while to update, I took a look at logs and it seems to update every 10 minutes. Should I have to change some parameters in the configuration.yaml file? Thanks.

**Comment by wonderbraun** [comment]
Ok sorry I added two lines to configuration.yaml
refresh_devices_every: 2
stream_timeout: 120
and rebooted and it seems to work fine now, also motion sensors which were completely unresponsive.

**Comment by twrecked** [comment]
I'll close it for now but feel free to re-open it if it happens again.
