### ISSUE TITLE
No base station recognised in home assistant.

### ISSUE THREAD

**Issue by jameslunt81** [twrecked/hass-aarlo#342]
I have installed the Aarlo intergration and can view camera’s, however I am unable to access any of the sensors of the camera’s.

I am getting an error of no base station assigned to camera.

Any ideas on what I am doing wrong / missed as I have followed all of the steps.

![3BFD916D-4EC5-4CC1-AF38-7824E7EB487F](https://user-images.githubusercontent.com/73176119/98656343-77347780-2338-11eb-8805-5c6766273364.jpeg)
![671F0BE8-4D03-4A2C-8370-8A3D78CC946E](https://user-images.githubusercontent.com/73176119/98656367-7c91c200-2338-11eb-8271-dd86cfde3d32.jpeg)
![E90D9631-90F4-41B2-8813-4A0C6534A891](https://user-images.githubusercontent.com/73176119/98656377-7f8cb280-2338-11eb-9546-69ae4bab532d.jpeg)

**Comment by twrecked** [comment]
You need to give your new user admin access when you share the devices.

**Comment by jameslunt81** [comment]
Thanks, worked straight away 👍
