### ISSUE TITLE
What happens if 2FA fails?

### ISSUE THREAD

**Issue by TheDK** [twrecked/hass-aarlo#344]
I activated 2FA via e-mail a couple of days ago as it is now obligatory by Arlo (who btw really start to piss me off now that I have invested in 6 cams and 2 bases).

This morning for the first time it failed - as far as I can see at the time of the reconnect no mail came in (so Arlo screwed up I guess). Now all Arlo cams are unavailable as the component is not logged in anymore .

As for most people using this component 2FA by mail will be the defacto way as text messages are much harder to forward to Arlo I'm wondering how aarlo treats missing mails / failed 2FA? Will it re-trigger login after some time or just wait for the next interval (2hrs for me)?

A great solution would be to wait for the mail for a minute or so, then retrigger it (or just restart the login procedure), if it fails again stretch out the intervall to maybe 5min / 15min / 30min / 60min to avoid hammering the service.

This might be something to invest in as it will be critical for many more users now. Thanks!

**Comment by TheDK** [comment]
I can add that if 2FA fails aarlo does not seem to try to login again and will stay disconnected until HA gets restartet.
--> Is that expected behaviour or shall I activate logging again to pinpoin possible issues?
--> Is there a way to restart aarlo / trigger auth with restarting HA?

**Comment by twrecked** [comment]
I do need to make this better. I'll take a look.

**Comment by gones01** [comment]
having the same issue today, would appreciate the retry logic!

**Comment by twrecked** [comment]
Fixed by #345 and 0.7.0.beta.7.

Platform set up done wirh async now and Arlo login will keep trying in the background.

**Comment by TheDK** [comment]
I installed the latest beta and will keep an eye on it (obvs)... 👍

**Comment by TheDK** [comment]
This morning the first try failed, a re-send of the email was triggered and then aarlo logged in less then one minute later. So that seems you’re improvements are working!
