### ISSUE TITLE
Not receiving state change event when starting streaming

### ISSUE THREAD

**Issue by hennarah** [twrecked/hass-aarlo#349]
After upgrading to version 0.7.0.beta.7, I stopped receiving state event messages starting streaming from the arlo camera. I tested with beta.6 and the same issue does exist. It works as expected with beta.5. I'm using  aarlo API on Node-red on HA.

Thanks

**Comment by twrecked** [comment]
I'll take a look.

**Comment by twrecked** [comment]
I missed a state when I tidied up the state machine. It should be fixed by PR #355  and in release 0.7.0

**Comment by twrecked** [comment]
I'm assuming it's working so I'll close this.
