### ISSUE TITLE
Wrong timestamp in sensor

### ISSUE THREAD

**Issue by TheDK** [twrecked/hass-aarlo#351]
Since updating to 0.118 (but might be coincidental) the timestamps displayed in HA differ 1 hpur (earlier) then at Arlo (where they are correct). All other timestamps in HA are OK.

Example: I record something at 14.00 (2pm), timestamps:
- Arlo: 14.00
- HA Logbook: 14.00
- Last sensor (displayed on Lovelace card): 13.00

Timezone in Arlo and HA is correct. It seems that when reading the timestamp from Arlo Cloud and populating the sensor 1hr is being subtracted.

Thanks for any ideas where to look!

**Comment by twrecked** [comment]
Look in `custom_components/aarlo/pyaarlo/util.py`. `arlotime_to_datetime` is the function that takes an Arlo timestamp (think Unix epoch time with more granularity) and converts it to a local `datetime` structure. 

This function is used:
- `httptime_to_datetime` will convert the `Last-Modified` header of the http reply, used when creating `/captured/YYYY-` strings.
- `ArloMediaObject::datetime` when reading information from the video library

It should be keying into your local timezone information.

**Comment by TheDK** [comment]
Hey, I believe I found the problem - seems to be a HA bug introduced in 0.118

> Same issue happens in python_script
> 
> datetime.datetime.now () function, before 0.118, it gave me the local time. After 0.118 i get an hour less (UTC). My heating system has stopped one hour later today :S
> 
> Seems to be an python datetime issue with timezones.

https://github.com/home-assistant/core/issues/43337#issuecomment-730572015

After following up on all of this it appears to be a problem in the 32bit Docker image but does not affect all timestamps in HA...

Anway, I this issues are closed and merged into Docker base image 2020.11.1:
https://github.com/home-assistant/core/pull/43538

It will be in 0.118.3 sometime this week I guess...

**Comment by twrecked** [comment]
Good find!

Looking at my end I did notice they added a field `utcCreatedDate` to the media library so I might use that going forward. For now it's identical to the `localCreatedDate` field so wasn't the bug.

**Comment by TheDK** [comment]
As expected, update to 0.118.3 solved the problem, timestamps are correct again.
