### ISSUE TITLE
Change at Arlo to max. 5 cams to shared account?

### ISSUE THREAD

**Issue by TheDK** [twrecked/hass-aarlo#353]
Since yesterday I am getting a new error for one of my cams (the 6th one on my setup):
```
2020-11-24 15:54:41 WARNING (SyncWorker_1) [pyaarlo] error in response={'data': {'error': '2222', 'message': "Your account does not support the addition of another device.  Now's a great time to upgrade your account.  Or you can remove one of your other devices.", 'reason': 'Device is not provisioned'}, 'success': False}
```
I checked the account with the app and even though 6 cams are shared with the account (and the account sees them) only 5 can be arranged on the grid, recordings be viewed, etc. - So it's not an Aarlo issue, I am just asking here what other users are seeing.

It appears Arlo limited the devices that can be shared with a "free" account to close a loophole - on the other hand if you simply want your partner to look at the same cams as yourself (and that you're paying for) it appears a bit much that you have to pay for the second account - I can't even find an offering for that at Arlo...

Edit: I can't do anything with the cam (iE start stream, take snapshot, etc.) - but if I use my main account the picture in HA changes. I haven't checked motion detection but I guess information of that would be coming in as well. Sensors appear to get populated as well.

**Comment by TheDK** [comment]
Update: Since last weekend now the whole cam is not available anymore, aarlo only recognizes 5 out of the 6 cams shared to its account.

@twrecked: I believe you once stated you have more than 5 cams shared to the account connected to Aarlo - do you see the same effect?

I have also opened a ticket and am trying to make to them understand what the problem is and that I can reproduce it to two accounts (my wife doesn't see the cam anymore as well), will keep you posted. From what I understand now this seems to be a hard cap of 5 cams or Aarlo supports more than one account which I imagine would be anything but easy to do...

**Comment by twrecked** [comment]
I'm not seeing this. My main account has 10 cameras which are grandfathered in to an old plan. I have a second account with 1 camera. And I have a 3rd account - the one I use on Arlo - that has these 11 cameras shared to it.

I'll take a look at the multiple account idea.

**Comment by TheDK** [comment]
Nevermind - I finally cracked and called support by phone. We went through a couple of motions and got it working again (something stuck in the backend). So it really was a bug and not change on Arlos side. After all I don't think the added complexity of connection severall accounts is warranted as long as one can share 10+ devices to one account without additional cost.

--> Please feel free to close if you concur.

**Comment by twrecked** [comment]
Congrats on getting through to support!

I'll close this but I did take a look at multiple accounts and it's not that big of a change - it's just a case of creating multiple PyArlo instances. I may add it in at some later date.
