### ISSUE TITLE
Deleted entities - how do I recover?

### ISSUE THREAD

**Issue by augelr** [twrecked/hass-aarlo#354]
I was trying to get battery info to come back. In the process I deleted a bunch of entities.
I suppose I am essentially trying to 'reinstall' everything, but not sure how to do this.

How should I go about this? Much of what I have is working, but I no longer can select many of the entities I used to have.
Thanks.

**Comment by augelr** [comment]
I was able to fix this, was an issue on my end in my config file.

**Comment by twrecked** [comment]
Glad you got it working. I was going to say even if you delete entities they should come back after a reboot - assuming your config was ok.
