### ISSUE TITLE
Arlo Camera list not refreshing.

### ISSUE THREAD

**Issue by nickolas1969** [twrecked/hass-aarlo#361]
I had teh AARLO integration set up and working on my 5 initial cameras (Using an HA Dedicated account that was NOT 2F based). I added 2 new cameras of the same type, insuring my HA account was an admin of them as well. They do not show up in my entities list, even after I Update Information from the integration. I thought maybe I had messed up my HA Arlo account permissions, so I deleted one of my initial 5 Camera entities.... Yeah, it's gone now.. A reboot of the whol system and an integration update has not brought them back?

What should I be doing to get my Camera list to refresh?

aarlo:
  username: <HA Arlo Account>
  password: <secretstuff>
  refresh_devices_every: 1
  refresh_modes_every: 2

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: Night
    trigger_time: 30
    alarm_volume: 8
    
camera:
  - platform: aarlo

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - connectivity

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    siren_volume: 1
    siren_duration: 10

**Comment by MechEng70** [comment]
What HA version are you on?  My arlo (with 2FA) has stopped working.

Supervisor: 2020.12.6
I believe that the system is on 0.118.5 - Since upgrading to this, have lost grafana, influx, aarlo and glances.... not sure if that helps the dev team.

**Comment by nickolas1969** [comment]
I this case I solved it late last night. It was the portals issue with my HA account. It had admin right over all 7, but when I logged in I could only see 5. I removed permissions from one, saved, the added it back, saved. Now all 7 populated in HA. 🤦‍♂️

Nick Ellson - from iPhone (forgive typos)
CCIE #20018; VCIX-NV, CNSE
Network Hobbyist
"Educating Layer 8, one user at a time."

**Comment by twrecked** [comment]
Glad you got it working.

@MechEng70  118.5 is working for me. If you can't get it working open a new bug with some debug attached.

**Comment by MechEng70** [comment]
Will do.  Thanks.

**Comment by twrecked** [comment]
Closing for now.
