### ISSUE TITLE
Problems with "Last Recorded" video in Lovelace

### ISSUE THREAD

**Issue by JP13090** [twrecked/hass-aarlo#367]
Clicking the camera in a Lovelace card used to bring up the last recorded video clip from each camera.  Now, the popup comes up, but the broken picture icon replaces the video.  If I open that broken picture in a new window, I get "500 Internal Server Error
Server got itself in trouble."

This seems to be a relatively recent change.  It's worked for months, even as of last week.  I *did* just upgrade HA to 2012.12.01 and I think there was an Aarlo update around that same time.

Others I've spoken with don't seem to have this issue, so maybe something broke on my end.
1) Can you point me in the right direction to fix this in my own config?
2) Would a complete uninstall/reinstall of the integration fix this?

I *am* able to use every other aspect of Aarlo.  I can activate my siren, and cameras still trigger my automations I've built around them...  So it's not a login/API issue that I can tell.

Any help is hugely appreciated.  Thanks for this great integration.

![Screenshot 2020-12-19 212049](https://user-images.githubusercontent.com/65277373/102724255-57e81d00-42dc-11eb-9874-e55ea70ca1a6.png)

**Comment by twrecked** [comment]
Can you paste in the lovelace card configuration? I want to make sure I'm testing the same thing.

**Comment by mlgallup01** [comment]
I am having the same issue. However, it was happening intermittently for a couple of weeks. There has been an Android update for the app this week, so I'm wondering if they broke something on the AWS side as far as the integration goes. All other sensors work as far as the devices go. All 2FA emails are coming through into my inbox. Removed and reinstalled once and it worked, but not this time.

**Comment by JP13090** [comment]
cards:
  - entities:
      - entity: switch.aarlo_all_sirens
    theme: darkblue
    title: ARLO SIREN SWITCH (CAUTION)
    type: entities
  - entities:
      - entity: sensor.aarlo_total_cameras
      - entity: camera.aarlo_front_porch
      - entity: camera.aarlo_inside
      - entity: camera.aarlo_back_yard
      - entity: switch.aarlo_all_sirens
    show_icon: true
    show_name: true
    show_state: true
    theme: darkblue
    title: Arlo Cameras
    type: glance
  - entities:
      - entity: sensor.aarlo_battery_level_front_porch
      - entity: sensor.aarlo_battery_level_inside
      - entity: sensor.aarlo_battery_level_back_yard
    severity:
      - color: red
        from: 0
        to: 15
      - color: yellow
        from: 16
        to: 30
    type: 'custom:bar-card'
  - entity: alarm_control_panel.aarlo_home
    name: Arlo Base Station
    states:
      - arm_home
      - arm_away
      - arm_night
    theme: darkblue
    type: alarm-panel
  - entity: alarm_control_panel.alexa_guard_908f2
    name: Alexa Guard
    states:
      - arm_home
      - arm_away
    theme: darkred
    type: alarm-panel
type: vertical-stack


This is my entire vertical stack.

Sorry it took so long to respond.

**Comment by JP13090** [comment]
If this helps, the camera does automatically show slide-previews. The guy in the green shirt is me this morning. The only problem is when I click on that picture, the actual video does not play, sort of like a broken link to the video file. 
![Screenshot_20201226-083526_Home Assistant](https://user-images.githubusercontent.com/65277373/103152407-9efb6580-4755-11eb-82d7-2a910748fc93.jpg)

**Comment by twrecked** [comment]
Do you have a high resolution camera. Can you look here: https://github.com/twrecked/lovelace-hass-aarlo/issues/40

I didn't get chance to try your config yet, work and Christmas got in the way. Hopefully this weekend.

**Comment by twrecked** [comment]
Can you try 0.7.0.5; I pushed a possible fix #370

**Comment by JP13090** [comment]
Updated to 7.0.5 just now and that fixed it perfectly! Thank you, sir!

**Comment by twrecked** [comment]
Glad it's working.
