### ISSUE TITLE
Audio only when playing video from library

### ISSUE THREAD

**Issue by mc130420** [twrecked/hass-aarlo#369]
Within the last 60 days my videos from the aarlo-glance-card library are no longer playing - I receive audio only.  I am running 7.04 version.  My videos were once 4K but now I am only using 2K.  Not sure if that has any impact.  Need some ideas on where to look.  I see no errors in any logs.

**Comment by twrecked** [comment]
Can you check the solution here, see if it helps: https://github.com/twrecked/lovelace-hass-aarlo/issues/40

**Comment by mc130420** [comment]
Confirmed.  I too modified my Arlo camera settings to enable Auto Zoom and Tracking and now playback works.  Thanks for the information.

**Comment by mc130420** [comment]
I did fail to mention that I was using the Arlo Ulta with HDR and 4K resolution cameras.  However, I did lower my subscription for the 2K only.  Solution works now but it does seem some work needs done around the codec support.
