### ISSUE TITLE
Missing entity after removing/re-adding to Arlo app

### ISSUE THREAD

**Issue by krelltunez** [twrecked/hass-aarlo#371]
In my experience, I've occasionally had to remove and re-add a camera or light after something goes out of sync in the Arlo app.  I'd been going strong for a while, but suddenly one of my security lights had become unresponsive.  In the Arlo app, I removed it and went through the process of re-syncing it with the hub.  I gave it the same name after adding it.

Following that, the prior entity became unavailable and no longer works.  Nor does the system appear to detect the light as a new entity.  Did I do something wrong?  How do I get HA to re-discover/enable the light?

Thanks in advance for your help.

**Comment by twrecked** [comment]
I've had that happen too - normally after a power cut - and things just appeared again after I re-synced everything.

One quick thing to try - do you need to re-share the device with your HA Arlo account?

**Comment by krelltunez** [comment]
Not sure how or what you mean.  I have the aarlo add-in set up as detailed in the docs, with it set to refresh devices every 2 minutes.  I don't actually have ANY Arlo devices - they're all entities.

Perhaps therein lies my problem?

**Comment by twrecked** [comment]
My bad, I meant at the Arlo level. To clarify:

### At The Arlo Level
When you created the Arlo account to use in HA you had to share cameras/lights with it. Maybe when you lost the light and re-synced it with the hub you need to re-share it to your HA account?

### At the HA Level
There is no dynamic update of entities from `Aarlo`, you need to restart the system to detect new cameras/lights.

**Comment by krelltunez** [comment]
> My bad, I meant at the Arlo level. To clarify:
> 
> ### At The Arlo Level
> When you created the Arlo account to use in HA you had to share cameras/lights with it. Maybe when you lost the light and re-synced it with the hub you need to re-share it to your HA account?

Ha! I bet that's it. I'll check!!!

**Comment by krelltunez** [comment]
Yes, that was it.  So dumb I didn't even think of it!

THANKS!

**Comment by twrecked** [comment]
Excellent. Glad that worked!
