### ISSUE TITLE
Arlo Pro 3 base station with Arlo 1 cameras 

### ISSUE THREAD

**Issue by Spiff1** [twrecked/hass-aarlo#373]
I have a Arlo pro 3 base station with 3 Arlo Pro 3 cameras and 4 Arlo 1 cameras. I can find the three Pro 3 cameras but the Arlo 1 cameras in not available to HA when using aarlo. 
Any idea what can be wrong?

**Comment by twrecked** [comment]
Can you try logging into the Arlo website with your HA Arlo account and see what it shows - you will have to stop Home Assistant while you try. If you see all the cameras on there then we'll need to turn on logging. See [here](https://github.com/twrecked/hass-aarlo#debugging) to see how to turn on debugging.

**Comment by Spiff1** [comment]
So simple, thanks. The Arlo 1 cameras was not shared with the aarlo account, after adding them it worked like a charm.
Thanks for helping, much appreciated.
