### ISSUE TITLE
Just pointing out a spelling error in the readme.md file

### ISSUE THREAD

**Issue by rpitera** [twrecked/hass-aarlo#38]
> For the simplest use replace all instances of the arlo with **_aalro_** in your home-assistant configuration files. 

should be

For the simplest use replace all instances of the arlo with **_aarlo_** in your home-assistant configuration files. 

=================
Thanks so much for this component; I'm installing today and can't wait to try it out!

**Comment by twrecked** [comment]
Thanks! That's actually quite an important spelling mistake.

**Comment by rpitera** [comment]
So far it's working great!  Component is loaded and all the sensors seem to be showing up; now just have to move from my picture glance cards to your custom card.

**Comment by rpitera** [comment]
Oh, I just noticed another one that's important:

 ```
resources:
   - type: module
     url: /local/aarlo-glance.js
```

should be

```
 resources:
   - url: /local/aarlo-glance.js
     type: module
```

**Comment by twrecked** [comment]
The ordering can be changed by the UI editor. At least I think I noticed that in the past.

Glad you like the component. The goal is to get it included in Home Assistant and I was going to start looking into it last week but real life (and work) got in the way.

**Comment by rpitera** [comment]
Like it?  Hell, I tweeted about it!  LOL
https://twitter.com/aka_westofeast/status/1113099580705595392

Planning on doing a post in the HA subreddit as well.  It's just about everything I could ask for (hoping you'll be able to set up streaming for hass.io users at some point).  The fact that the alarm state isn't changing every five minutes is a godsend.

**Comment by twrecked** [comment]
Thanks!! It just started out as a way to fix some issues that were bugging me so I'm glad to know other people are finding it useful.

Streaming is going to need help from the some devs closer to the ffmpeg stuff. I want it fixing too because I run my main HA in a docker and it doesn't work there.

**Comment by rpitera** [comment]
Steve - since I have no other way to contact you, I just wanted to say that I posted about your component on the r/homeassistant subreddit and got a really good response.  Here's the link to the post:
https://old.reddit.com/r/homeassistant/comments/bblyjt/use_arlo_cams_in_ha_this_is_what_youve_been/

Just in case you were wondering where the traffic was coming from. LOL

**Comment by twrecked** [comment]
Thanks again!

Funny thing, I woke up this morning and my Google news feed was showing me the link to the Reddit article.

**Comment by rpitera** [comment]
LOL.  I'm a mod on the r/homeautomation sub so if you want it posted there too, let me know.  I mentioned it on a post in r/wyzecams in passing; someone was asking for a comparison between Arlo and Wyzecams.  I've been promoting it to anyone who'll listen.  I'm just so pleased with it.

Once it is in a bit wider circulation, I will put in a PR to have it added to Frenck's Awesome list.  I just need to wait a bit as he's hesitant to approve anything that's too new and doesn't have enough users to recommend it.  But he knows me so I'm sure that it will get added.

Hopefully, this will motivate you to keep up the great work!  Cheers.

**Comment by cbfreeborn** [comment]
Everything in my install of this GREAT alternative to the standard arlo component went fine; however, I'm still scratching my head about where exactly 

`resources:
  - type: module
    url: /local/aarlo-glance.js`

should be located. I'm running hassio so I assumed in a /config/ui-lovelace.yaml file?

Thanks!

**Comment by rccoleman** [comment]
/config/ui-lovelace.yaml if you're using Lovelace in YAML mode, or paste it at the top of the raw editor if you're using it in Storage mode (the default).

**Comment by twrecked** [comment]
@rpitera Once again, thanks for the support! And apologies for taking so long to acknowledge it. Spring arrived here so I've been running around like a lunatic fixing things inside and outside the house.

Just FYI, I'm planning on getting a 0.5 release out this weekend then looking to try to get into the official image.

**Comment by rpitera** [comment]
Just to note that I have not had a single issue with your code since I installed it.  Working great here and I continue to tell people about it.

**Comment by twrecked** [comment]
Tidying up! 

And hoping everything is still working well!

**Comment by rpitera** [comment]
Working great and BTW I put in a PR (which was accepted and pushed) to have Aarlo added to the HA Awesome list!  Congrats!
