### ISSUE TITLE
"No content to download" Error for 0.7.0.12

### ISSUE THREAD

**Issue by usedjeans818** [twrecked/hass-aarlo#387]
When I attempt to update to 0.7.0.12 from 0.7.0.10, it errors out with "No content to download" and the "Update pending" window closes immediately.  It's so fast, I had to record the action using slow-motion video on my phone.

![Screenshot_2021-02-08 HACS - Home Assistant](https://user-images.githubusercontent.com/74646319/107314262-1c9adc80-6a49-11eb-97c6-1f8c40da94ff.png)

```
2021-02-08 20:09:13 ERROR (MainThread) [custom_components.hacs] No content to download
```
I'm running:
Home Assistant OS 5.11
core-2021.2.2
HACS 1.11.0

**Comment by twrecked** [comment]
It worked fine for me just. Can you try going back a revision then trying 0.7.0.12 again?

**Comment by usedjeans818** [comment]
I tried several times with several reboots.  However, it suddenly started working for me.  Thanks for the prompt response, @twrecked.

**Comment by twrecked** [comment]
Glad it worked. Honestly, I'm not sure what I could have done here other than create a new identical release.
