### ISSUE TITLE
[FR] Ability to turn off a camera

### ISSUE THREAD

**Issue by seanmccabe** [twrecked/hass-aarlo#397]
I've looked through on the issues and in the readme, and can't find it.

Would it be possible to have the ability to turn off a camera?

I can see doing a request from the web interface it is possible.
![Screenshot from 2021-02-24 11-52-15](https://user-images.githubusercontent.com/12243212/108919354-bb554900-7697-11eb-8389-deb27f26317c.png)

Be great to be able to turn off individual cameras. Sometimes I have to as the wind is just too high, so sets off the audio alerts, or the washing is out and it sets off a camera.
First world problems I know.

**Comment by twrecked** [comment]
The cameras can act like standard Home Assistant cameras so you can use the `camera.turn_off` and `camera.turn_on` services.

You can also add the [`onoff`](https://github.com/twrecked/lovelace-hass-aarlo#image-options) icon to the Lovelace card.

**Comment by seanmccabe** [comment]
Ignore me then, i'm a muppet.
Should have just looked in the development tools to figure that one out and maybe used ctrl+f to find off in the readme :p

**Comment by twrecked** [comment]
No worries. It's a strange integration because it has one foot in the Home Assistant camp and one in the Arlo camp.

Hope you get it working!
