### ISSUE TITLE
Core update 2021.3.0b0 CONF_DURATION error

### ISSUE THREAD

**Issue by brianlaucis** [twrecked/hass-aarlo#399]
Anyone else getting this error after updating? 
![image](https://user-images.githubusercontent.com/40279388/109097314-b5d22000-76e4-11eb-9ed2-be13de74dfa9.png)

**Comment by twrecked** [comment]
Looks like they've moved some stuff about. I'll need to fix the record service for that release.

**Comment by brianlaucis** [comment]
@twrecked Thanks. Seems to be working now..  You are awesome.

**Comment by JManDoo** [comment]
Works for me too....Strong Work! Thanks!
