### ISSUE TITLE
Is this part of the official Hass release?

### ISSUE THREAD

**Issue by Muffo** [twrecked/hass-aarlo#40]
Newbie question: is this part of the the Home Assistant release 0.91?

I have just installed it on my RPi and I am having issues changing the status of my Arlo setup.
Made some research online and ended up on this project, but I am not sure if this is still under development or it has already been integrated in the latest official release.

**Comment by rccoleman** [comment]
Not yet, but we all hope it will be soon :). It’s easy to install as a custom component for now.

**Comment by Muffo** [comment]
Perfect!! I'll give it a try then :)

**Comment by Muffo** [comment]
FYI, this is working great so far! :)
I am using it only to control the state of the the alarm and it has been 100% reliable over the past couple of days. So much better than the official component.

**Comment by twrecked** [comment]
Glad it's working for you! 

As @rccoleman said I am working to get it in the official release - I've got a few things to tidy up and real life got it in the way the last week or two - but hopefully in the next couple of weeks.
