### ISSUE TITLE
New Installation 2FA Fail

### ISSUE THREAD

**Issue by americanjoe** [twrecked/hass-aarlo#402]
New install of Aarlo with HACS but getting 2FA fail when trying to set up the integration into home assistant.

The following lines are added to my /config/configuration.yaml

aarlo:
  username: myaccount@gmail.com
  password: my-arlo-account-pw
  refresh_devices_every: 2
  stream_timeout: 120
  tfa_host: imap.gmail.com
  tfa_username: my2fa-email@gmail.com
  tfa_password: mygmailaccountpw

I've even tried changing the tfa_password to my arlo account pw which is a helpful response in google for app requests, both options fail.

This is also a 2nd Arlo account with shared access to my main arlo account, but I've even tried my main arlo account information as well.

Here are the errors from my logs:

unable to connect to Arlo: attempt=2,sleep=30,error=2fa startup failed
12:38:09 PM – aarlo (ERROR) - message first occurred at 12:30:13 PM and shows up 6 times
imap connection failedb'[ALERT] Application-specific password required: https://support.google.com/accounts/answer/185833 (Failure)'
12:38:09 PM – custom_components/aarlo/pyaarlo/__init__.py (ERROR) - message first occurred at 12:30:13 PM and shows up 12 times
Setup of aarlo is taking longer than 300 seconds. Startup will proceed without waiting any longer

**Comment by twrecked** [comment]
Your main gmail password will not work, you need an application specific password: https://support.google.com/accounts/answer/185833

**Comment by americanjoe** [comment]
I've tried both my Gmail PW and my Arol account pw in the tfa_password slot.

**Comment by twrecked** [comment]
Correct. You need to create an application specific password for your Gmail account. A second password if you like. It's a Google security feature.

Follow the instructions under "Create & use App Passwords" on the link. It will create a second password you can use.

**Comment by americanjoe** [comment]
awesome, thank you
