### ISSUE TITLE
Wired video doorbell siren?

### ISSUE THREAD

**Issue by cameronurnes** [twrecked/hass-aarlo#404]
Hey there!  The wired video doorbell has a siren I can activate from within the Arlo app, but I don't see it supported in this integration.  Is it possible to add or does Arlo have that hidden?  I have the siren switch configs added, but it isn't showing up as an entity.

Thanks!

**Comment by cameronurnes** [comment]
Here is the payload from the post request to fire the siren, from the web interface.

![post-payload](https://user-images.githubusercontent.com/8864171/109844189-c0b71400-7c00-11eb-96d7-cabe49217040.png)

**Comment by cameronurnes** [comment]
I was able to get this working by modifying some code.  I will clean that up a bit and do a PR

**Comment by twrecked** [comment]
It's in the latest release. Can you check and close this if it works?

**Comment by cameronurnes** [comment]
I ended up swapping over to a UniFi camera so the Arlo isn't up anymore.  I can verify it worked before merge at least though.
