### ISSUE TITLE
Ability to change DISARMED to a custom mode

### ISSUE THREAD

**Issue by k41zen** [twrecked/hass-aarlo#409]
Is it possible we could have the ability to change the DISARMED state to a custom mode in configuration.yaml? 

When we're at home we still have 3 outside cameras watching cars in an a custom mode in Arlo called Home. This enables the three 3 cameras only and enables motion sensors and recording. And of course when we arrive back home Disarmed disables all motion and recording in Arlo.

I'm getting around this by altering the alarm_control_panel.py script and changing the disarmed line shown below to Home:

ARMED = "armed"
DISARMED = "disarmed" (change to Home)
ICON = "mdi:security"

Obviously every time there's an update this restores back to disarmed.

**Comment by twrecked** [comment]
I din't see this being a big change but why not just set the alarms to Home using the```alarm_control_panel.alarm_arm_home``` service.

**Comment by k41zen** [comment]
Thanks for this. It's because when setting to arm_home the panel still shows the red shield and the disarm button. I appreciate it is actually armed but not in the sense that it's completely armed. It invites the user to click the disarm button as they think the alarm is armed when they're home. Hope that makes sense.

**Comment by k41zen** [comment]
As another workaround I've added Alarmo in to the mix. Use the Alarmo panel on the dashboards and then use Node-Red to call disarmed for Alarmo to show the Green disarmed badge and not the disarm button, and then to set Aarlo to home but not use the panel. It's a little more than it should be so was just wondering if this could be possible so I could simplify my setup selfishly.

**Comment by twrecked** [comment]
Should be in the latest release, added by PR #411

**Comment by k41zen** [comment]
Awesome. Thank you

**Comment by twrecked** [comment]
I'm assuming this is working!
