### ISSUE TITLE
Strange issue with recording service not working for 1 of 6 camera entities

### ISSUE THREAD

**Issue by TheDK** [twrecked/hass-aarlo#414]
I use this code in an automation to record:
```  action:
    - service: aarlo.camera_start_recording
      data:
        entity_id: camera.aarlo_garage
        duration: 90
    - delay: 00:00:01
    - service: aarlo.camera_start_recording
      data:
        entity_id: camera.aarlo_haustur
        duration: 90
```
The first call works just fine, the second one fails:
In the log I get:
`Error executing script. Invalid data for call_service at pos 3: not a valid value for dictionary value @ data['entity_id']`

So I tried in the Developer tools :) - same effect, same error shown at the bottom:
![grafik](https://user-images.githubusercontent.com/5020623/110666532-b6c97e00-81c9-11eb-9f0b-573f653b60ca.png)

What actually happens is that the camera claims that it started and stopped recording:
![grafik](https://user-images.githubusercontent.com/5020623/110666900-027c2780-81ca-11eb-8030-84c900c0700f.png)
German for: Started recording - then recently active.

But no recording in the library and the Arlo app doesn't recognize any activity.

Screenshot of the entity_id from DevTools - I copied them so I think they should be fine:
![grafik](https://user-images.githubusercontent.com/5020623/110666162-5cc8b880-81c9-11eb-8793-7d7ddc42cba7.png)
![grafik](https://user-images.githubusercontent.com/5020623/110666204-65b98a00-81c9-11eb-81df-a49a1811f9a2.png)

So any idea why the exact same calls works on 5 entities and not the 6th one?

If not I will probably remove and reshare the camera with the account or change the entity_id - but the rest (iE snapshot!) works just fine!

**Comment by TheDK** [comment]
Yes :) It's called Haustür at Arlo and gets translated to camera.aarlo_haustur (notice the u for the ü!) in HA. How can I change that? Change the name in Arlo?

**Comment by twrecked** [comment]
Changing it in Arlo is the only solution for now.

I should run the names through some sort of processing - `unidecode()` for example - and I'll get something checked in this week.

**Comment by TheDK** [comment]
OK, so I renamed the Camera in Arlo, Restarted HA, deleted the old entity, renamed the new entity (was now _2) - and now everything incl. recording works again.

BUT: The Lovelace card does not show singnal strength anymore even though it is an exact copy of the other cards - which keep showing singal strenght. I even copied another card and just changed the entity_id - still two icons missing. Strange...

**Comment by twrecked** [comment]
Can you paste the card?

Did you change the name against the your main Arlo account or the HA one?

What does `Developer Tools > States` show for the entity? Is there more than one entity?

**Comment by TheDK** [comment]
Working card:
```
type: 'custom:aarlo-glance'
entity: camera.aarlo_garage
name: Garage
image_top: 'name,status'
image_bottom: 'motion,library,stream,snapshot,battery,signal,date'
image_click: recordings
library_sizes: '3,4,2'
light: light.garage_aussen
```
![grafik](https://user-images.githubusercontent.com/5020623/110949517-fa93c300-8342-11eb-9566-cfe6bf28898f.png)

Not working card:
```
type: 'custom:aarlo-glance'
entity: camera.aarlo_haustur
name: Haustür
image_top: 'name,status'
image_bottom: 'motion,library,stream,snapshot,battery,signal,date'
image_click: recordings
library_sizes: '3,4,2'
light: light.haustur
```
![grafik](https://user-images.githubusercontent.com/5020623/110949559-05e6ee80-8343-11eb-9f5c-99c7c0f605d6.png)


Camera name changed in Arlo Main Account and propagated to Shared Account: Haustur (no ü anymore!)

HA initially created the new one as camera.aarlo_haustur_2 and orphaned the first one. I deleted the orphaned one and renamed the new one camera.aarlo_haustur.
![grafik](https://user-images.githubusercontent.com/5020623/110949613-17c89180-8343-11eb-9e3f-3ec63bc922bb.png)

Everything works - except 2 missing icons... :)

**Comment by twrecked** [comment]
Look for the other entities; it might have called them `_2` as well. Something like:

`sensor.aarlo_signal_strength_haustur_2`

**Comment by TheDK** [comment]
Of course! As the information was present on the camera entity I thought the Lovelace card was reading it from the attributes. I renamed all the other entities, now everything is fine again. Thanks again Steve for the quick support!
