### ISSUE TITLE
Arlo Baby supported?

### ISSUE THREAD

**Issue by allenrong88** [twrecked/hass-aarlo#42]
Hi,

I have been using aarlo component for a while in order to get my Arlo system working perfectly. Thanks twrecked for your excellent work.

I have recently purchased an Arlo Baby and try to get it integrated into my HA. I added it into my Arlo app and do lots of things within the Arlo app, no issue. Now I moved onto my HA bit and get it restarted completely. However, I cannot see anything related to my Arlo Baby shown in the entity column nor its temp/ humanity sensor etc.

I did found the following https://github.com/twrecked/hass-aarlo/issues/4 mentioning that it was successfully resolved and merged. Could anybody point me to a right direction pls? Is there any extra configuration needed to get Arlo Baby working properly?

Thank you

**Comment by twrecked** [comment]
Hi.

Add the following options to your `sensor` configuration.

```
    - temperature
    - humidity
    - air_quality
```

Let me know if it works.

**Comment by allenrong88** [comment]
Beautiful! Thx so much. It is working perfectly now.
