### ISSUE TITLE
Aarlo not showing and camera picture after beta 7

### ISSUE THREAD

**Issue by elgeniskogen** [twrecked/hass-aarlo#422]
After updating to beta 7 my cameras failed to show and image. After rolling back to beta 6 it i snorking again. I do not use 2FA. My Setup is very simple:

aarlo:
  username: my_username
  password: !secret arlo_password

alarm_control_panel:
  - platform: aarlo
    home_mode_name: Hjemme
    night_mode_name: Natt

media_player:
  - platform: aarlo

**Comment by twrecked** [comment]
I'm assuming you have names with non latin characters in because I just released I accidentally turned on a breaking change. I'll push a quick fix.

**Comment by elgeniskogen** [comment]
Thank you  for quick response :-) You are totally right, I ute the Norwegian letter "ø". Thank you again!
