### ISSUE TITLE
authentication failed error

### ISSUE THREAD

**Issue by marsin-crypto** [twrecked/hass-aarlo#424]
Hi,
This integration worked for me almost flawlessly for may weeks.
Today I got authentication error
I did not changed my login nor in arlo neither in aarlo profile (both on gmail accounts) I can login to both outside home assistant
Here is copy of the error:

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:573
First occurred: 11:52:25 PM (5 occurrences)
Last logged: 11:56:24 PM

authentication failed

**Comment by dlo747** [comment]
Same here

**Comment by shehandavy** [comment]
Same here. Been using this integration without any major issues for a while now, but today I couldn't arm or disarm. Restarted HA and noticed the same error in the notifications.

Noticed that my 2FA emails to my secondary Gmail account have stopped coming in since 4 hours ago.

**Comment by twrecked** [comment]
I'm seeing it here. Looks like they changed the auth mechanism. I'll take a look.

**Comment by rpitera** [comment]
Yeah, I just tried rolling back to the last beta and it still failed so it's def something on their side. If it's fixable, I'm sure @twrecked will fix it. He's on a roll lately!  BTW, new features/implementation are rocking!  Been solid until Arlo glitched.

**Comment by dtrop1** [comment]
My Arlo IOS app was updated.  But I am having the same problem.  I did migrate my HA over to a new Pi4 and SSD.  So that broke the auth.

**Comment by twrecked** [comment]
It looks like Cloudflare tightened up their access. I've added [cloudscraper](https://pypi.org/project/cloudscraper/) to allow access to work again.

It should be fixed in version 0.7.1.beta.9.

**Comment by mikesplain** [comment]
Worked for me, thanks for the quick fix!!

**Comment by TheDK** [comment]
Very quick turn-around and working fix, thanks Steve!

**Comment by shehandavy** [comment]
Thanks for the quick fix @twrecked! Confirming it works for me again. Cheers! 🙂

**Comment by marsin-crypto** [comment]
thanks for the fix

**Comment by nsleigh** [comment]
@twrecked thanks for the quick fix. One observation, when there was an issue my Home Assistant was very slow to start and some parts failed to load - is there anyway it could be made to "fail safe"?

**Comment by tomlynn** [comment]
I'm a new adopter and am encountering the cloudflare challenge error:
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:676
Integration: aarlo (documentation, issues)
First occurred: 4:36:31 PM (42 occurrences)
Last logged: 5:45:19 PM

request-error=CloudflareChallengeError

I'm using version 0.7.2b7
