### ISSUE TITLE
Snapshots missing

### ISSUE THREAD

**Issue by dmccabe79** [twrecked/hass-aarlo#432]
Maybe I'm losing my mind. Where do snapshots go without doing the save_media parameter?

Also, I can't seem to get the same_media parameter to work. Where should I be putting that?

**Comment by twrecked** [comment]
We don't automatically save snapshots but there are 2 options that can do it:

- `save_updates_to`: here you specify a directory and `hass-aarlo` will save all image updates - snapshots you take and thumbnails from recordings - to here. For example, if you add `save_updates_to: /config/updates` into your `aarlo` config it will save them to a directory called `updates` next to you configuration.

- `save_media_to`: here you specify a directory and filename pattern and `hass-aarlo` will save all videos and snapshots to here. For example, setting `save_media_to: "/config/media/${SN}/${Y}/${m}/${d}/${T}"` will save all videos under a directory called `media` next to your configuration. As well as adding new media it will retrieve all available old media. See the README for a description of the media format.

You add these configuration items to the `aarlo:` section.

**Comment by dmccabe79** [comment]
Thanks. 

Has there been any fundamental changes to the Lovelace Card since the README was updated? I followed the HACS installation method and HA isn't liking the custom element "custom:aarlo-glance" when following the hass-aarlo-hacs part of the docs.

Thanks for this amazing integration!

**Comment by twrecked** [comment]
Nothing has changed. But Home Assistant aggressively caches things so you might need to force a reload. On Chrome:

- `CTRL+SHIFT+I` to enable the developer tools
- `CTRL+SHIFT+R` to reload the page

If you want to paste the card here I can take a look.

**Comment by dmccabe79** [comment]
Yes, HA is notorious for that. Let me switch over to Chrome and see if I get a better result.

**Comment by dmccabe79** [comment]
Got it. Thanks a lot. Going to see if I can do some image processing with snapshots now
