### ISSUE TITLE
Alarm Control Panel disable siren

### ISSUE THREAD

**Issue by rafuz** [twrecked/hass-aarlo#44]
There is a way to completely disable the Siren option when Alarm Control Panel is triggered?

**Comment by twrecked** [comment]
You could try:

```
alarm_control_panel:
  - platform: aarlo
    alarm_volume: 0
```

But I have no idea what that will do. If that doesn't work I can add a no_siren option.

**Comment by rafuz** [comment]
No effect, it stays at default volume I think.
It should be useful to disable siren as I use Arlo also for modes that do not involve ringing an alarm.

**Comment by twrecked** [comment]
I'll add an option.

**Comment by twrecked** [comment]
Can you update and try again. A volume of zero will not (should not!) call the siren any more.

**Comment by rafuz** [comment]
I can't test it properly now but I will tomorrow morning.

**Comment by rafuz** [comment]
I have tried it but siren still fires when Alarm Control Panel is triggered

**Comment by twrecked** [comment]
...helps if the code actually converts the volume to an integer before checking... 

Sorry, can you update and try again.
