### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by collse** [twrecked/hass-aarlo#45]
Hey Steve would you mind applying versioning to your commits? Its almost impossible to track merges or changes in the components without proper versioning - would be good to see the likes of

0.x.xxx as for example 0.4.123 - 0.4 release commit 123 to see what has changes but only if touching components rather than commits that represent changes in documentation as an example.

**Comment by allenrong88** [comment]
Looking forward 0.5 version. Still on 0.4 release at the moment, working like a charm! Thx Steve!

**Comment by twrecked** [comment]
Will be doing better on this going forward.

Commits will  increment the last number and changes will be put in the changelog file. I'll also be supporting the custom_updater better.

And hopefully 0.5 will be some time this weekend. Then I'll start trying to get it brought into the main component.

**Comment by twrecked** [comment]
Closing because I'm doing now!
