### ISSUE TITLE
Aarlo Component Setup Failed. Unable to set up component.

### ISSUE THREAD

**Issue by HumanSkunk** [twrecked/hass-aarlo#451]
Today I have tried to add a couple of new items to my HA config, consequently I have restarted my system a few times today. An error I have started to see today only seems to be complaining about an authentication issue with the Aarlo plugin. Sometimes it will work without issue, sometimes it will hang for a bit and eventually load after a few minutes and other times it will just hang and eventually time out.

I have checked the logs and these are the messages that returned:

```2021-06-03 13:28:28 WARNING (MainThread) [homeassistant.loader] You are using a custom integration aarlo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-03 13:28:32 WARNING (SyncWorker_4) [pyaarlo] request-error=CloudflareChallengeError
2021-06-03 13:28:33 WARNING (SyncWorker_4) [pyaarlo] request-error=CloudflareChallengeError
2021-06-03 13:28:34 WARNING (SyncWorker_4) [pyaarlo] request-error=CloudflareChallengeError
2021-06-03 13:28:34 WARNING (MainThread) [homeassistant.components.climate] ClimateDevice is deprecated, modify NestClimate to extend ClimateEntity
2021-06-03 13:28:35 ERROR (SyncWorker_4) [pyaarlo] authentication failed
2021-06-03 13:28:35 ERROR (SyncWorker_4) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
2021-06-03 13:28:42 WARNING (MainThread) [homeassistant.setup] Setup of aarlo is taking over 10 seconds.
```

Eventually it will just fail (but not all times with this error:

```
2021-06-03 13:33:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547486204400] Received invalid command: aarlo_library
2021-06-03 13:33:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547486204400] Received invalid command: aarlo_library
2021-06-03 13:33:31 ERROR (MainThread) [homeassistant.setup] Setup of aarlo is taking longer than 300 seconds. Startup will proceed without waiting any longer
2021-06-03 13:33:31 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
2021-06-03 13:33:31 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.camera: Unable to set up component.
2021-06-03 13:33:31 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
```

There seems to be an issue with the 2FA. I have not changed my password nor my logins to the google account that it is linked to. Could there be some form of call limit that I have now hit? The only way to get it to work sometimes is restart HA a second time and hope that it works.

Any idea what the cause is my guess the Cloudflare challenge error message could be key, but unsure if this is Arlo, the plugin or HA.

**Comment by HumanSkunk** [comment]
So it seems to the a issue with getting the 2FA code. Sometimes it takes a couple of minutes for the email to come in and in that time HA just hangs until it comes in. If I run the process manually and try and log into Arlo then I get the 2FA email instantly on request. Perhaps its taking too long to attempt to reach the domain?

**Comment by twrecked** [comment]
You could try disabling 2FA, it might not actually be needed just yet. See the bug raised about it.

What version of Aarlo are you on?

**Comment by HumanSkunk** [comment]
> You could try disabling 2FA, it might not actually be needed just yet. See the bug raised about it.
> 
> What version of Aarlo are you on?

Have they recently switched the need for it back off again?  As they were hammering it down my throat for months. It has been working fine like I say up until today. 

Version I am running is v0.7.1.beta.15. I have just looked that there is a new one v0.7.1 with a fix "Fixed auth issue, I need to use cloudscraper to access the cloudflare sites." So you may have already fixed the issue. I will try updating and will give it a few restarts. If you hear nothing back from me me in a few days with an update then assume this is fixed

**Comment by twrecked** [comment]
I implemented the `cloudflare` change and there was an update to `cloudscraper` shortly after. There was a timing issue that meant some people might have the previous version. I made the `cloudscraper` version explicit in `0.7.1`.

Let me know if it helps.

**Comment by HumanSkunk** [comment]
So it still seems to be intermittent with whether it will initialise quickly. In the 10 or so times I have restarted this afternoon it hasn't completely failed once. There have been acouple of times where it has hung the start up until its completed where it could take any time between 20 seconds and 2-3mins. 

```
This error originated from a custom integration.

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:444 
Integration: Arlo Camera Support (documentation, issues) 
First occurred: 17:39:00 (4 occurrences) 
Last logged: 17:40:56

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed

```
Then suddenly it will work like there isn't an issue. `2021-06-03 17:39:18 WARNING (SyncWorker_1) [pyaarlo] request-error=CloudflareChallengeError` and everything will start like there was never a problem.

**Comment by twrecked** [comment]
I'm seeing the same issue and looking at what I can do. It might be the `cloudscraper` component needs updating or it could be I need to modify the headers I use.

**Comment by HumanSkunk** [comment]
Let me know if you want me to test anything my end

**Comment by twrecked** [comment]
Will do. For now I'm tidying up the headers and updating "sseclient" to deal with a JSON error issue.

I found some comments online indicating we may be able to bypass the cloudflare check by changing up the requests packet but I've not had any luck implementing that.

**Comment by georgejung** [comment]
i am having what seems to be the same issue. I wonder if its something on arlo's side. I have my 2FA setup with email (gmail) and even just trying to login to the arlo my account it isn't sending me the verification code reliably. I saw the comment about being able to disable 2fa, but i can't even login to try that...

**Comment by twrecked** [comment]
Mine seems a lot better now - it's working every time.

But I have found a way of persisting the authorization token so I think I can get the code to the point where it needs to "really" login, triggering 2FA if needed, once every 12-14 days.

**Comment by georgejung** [comment]
yep working for me now and i was able to login to disable 2FA. Interested in the persisting token, but would go a few days short, maybe 10. Give it a couple days where it starts to 'retry' to get the new token before expiration, in case it has a problem like this again, the old token will persist while it is still trying to get the new one.

**Comment by twrecked** [comment]
The persistent token seems to working pretty well, I've been using the same token now for 12 hours and it's survived 4 restarts.

Another bonus, it doesn't seem to need the `cloudscraper` component when reusing the token.

I think one problem with trying to get the new token while using the old token is Arlo won't let you use the same login twice, it will close the current event stream immediately. It's the reason you need a second account for Home Assistant. I'll still give it a try though.

**Comment by gwalker88** [comment]
I've found that the one-time code sent to my Gmail account is now ending up in the Spam folder. Hope that helps.

**Comment by georgejung** [comment]
Good catch! Sure enough that's where a lot of mine were ending up. FYI to whitelist in gmail you create a filter to "never send to spam".

**Comment by HumanSkunk** [comment]
This doesnt seem to be an issue for me anymore. I have restarted a few times since my last comment and not seen any errors in HA regarding issues setting up Aarlo, so will close the issue.
