### ISSUE TITLE
Component freezes if internet is unstable

### ISSUE THREAD

**Issue by czagatti** [twrecked/hass-aarlo#453]
Hi all

Just sharing something that happens (unfortunately a lot) in my environment, not exactly a bug. Not sure if somebody else has this too..

If the internet connection drops (ex. ISP uplink unstable), the component stops updating the armed/disarmed status and does not trigger automations based on motion. To solve it I have to "restart" the component by either restarting the entire HA instance or reinstalling the component.

If there were a way to restart the component I guess that would solve this issue, it seems this is related to the way the component "reads" push messages from the cloud. Does that make sense?

Thanks for reading :-)

**Comment by twrecked** [comment]
Look at `stream_timeout`, it should reconnect after a period of inactivity. A good starting point is 180 seconds.

https://github.com/twrecked/hass-aarlo#best-practises-and-known-limitations
