### ISSUE TITLE
Custom element doesn't exist: aarlo-glance

### ISSUE THREAD

**Issue by AndrewsBrewing** [twrecked/hass-aarlo#459]
I highly doubt this is your issue twrecked, but I can't get this setup...

Used HACS to load it.  Got this message.
When installed, this will be located in '/config/custom_components/aarlo'

Here is the entry in my configuration.yaml
--------------------------------------------------
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-hass-aarlo/aarlo-glance.js
      type: module

aarlo:
  username: !secret arlo_user
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 5
    alarm_volume: 5
camera:
  - platform: aarlo
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - connectivity
sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
switch:
  - platform: aarlo
    siren: False
    all_sirens: False
    snapshot: True
media_player:
  - platform: aarlo
--------------------------------------------------

Here is my entry in ui-lovelace.yaml

--------------------------------------------------
    cards:
      - type: 'custom:aarlo-glance'
        entities:
          - entity: camera.aarlo_front_door
          - entity: camera.aarlo_back_door
          - entity: camera.aarlo_garage
--------------------------------------------------

Here is the error on the dashboard

--------------------------------------------------
Custom element doesn't exist: aarlo-glance.
type: 'custom:aarlo-glance'
entities:
  - entity: camera.aarlo_front_door
  - entity: camera.aarlo_back_door
  - entity: camera.aarlo_garage
--------------------------------------------------

**Comment by twrecked** [comment]
Sorry, I've been busy and didn't get chance to look at his. Did you get it going?

**Comment by AndrewsBrewing** [comment]
> Sorry, I've been busy and didn't get chance to look at his. Did you get it going?

Yes I did, thank you. I just had to read all the instructions. Lol

**Comment by jake-gore** [comment]
I'm having the same issue.  What was your fix?

**Comment by eddieparker** [comment]
I had the same issue.  I ended up following these instructions again: https://github.com/twrecked/lovelace-hass-aarlo/blob/master/hacsinstall.md and just clicking 'update' on the existing resource that HACS had already added.  After that I was able to add the card.

**Comment by mermelmadness** [comment]
I followed all the directions and I'm still getting the "Custom element not found: aarlo-glance" error.
![image](https://user-images.githubusercontent.com/38080873/149871672-e0a587e7-4239-4ff1-91a0-d895d88eac1a.png)
![image](https://user-images.githubusercontent.com/38080873/149871722-62fbe56a-2251-4964-b84f-220f0310837e.png)
![image](https://user-images.githubusercontent.com/38080873/149871746-87a2bac3-c1ff-41bb-a076-bd990f6ffd13.png)
![image](https://user-images.githubusercontent.com/38080873/149871768-54e60a65-e2cf-49e9-8863-3b383c84ff18.png)

**Comment by adieball** [comment]
I tried everything I could find, no success. Installed aarlo and aarlo lovelance via HACS
aarlo itself is working fine.

/hacsfiles/lovelace-hass-aarlo/hass-aarlo.js?hacstag=1972451790261 in in the ressources

But when I add a custom card with:

```
type: custom:aarlo_glance
entity: camera.aarlo_garten
```

I just get back: `Custom element not found: aarlo_glance
`
Files instaled at:

```
➜  ~ find / -name \*aarlo\*                                             
/homeassistant/.aarlo
/homeassistant/.aarlo/aarlo.pickle
/homeassistant/www/community/lovelace-hass-aarlo
/homeassistant/www/community/lovelace-hass-aarlo/hass-aarlo.js
/homeassistant/www/community/lovelace-hass-aarlo/hass-aarlo.js.gz
/homeassistant/custom_components/aarlo
```
