### ISSUE TITLE
Ability to change motion detection mode for Arlo Essential Cam

### ISSUE THREAD

**Issue by NickM-27** [twrecked/hass-aarlo#474]
The Arlo app doesn't have sunset timing for motion detection so I currently use IFTTT for that. I am interested in Aarlo but from what I can tell it doesn't support enabling / disabling motion detection for the Essential cam.

**Comment by twrecked** [comment]
Unfortunately the plugin is limited to the functionality provided by the web interface. There are two options that might help:

- turn the camera off/on as needed
- set up a mode where only motion detection is enabled and use that mode at sunset

I use the second option, in the evening I enabled motion detection with a `home` mode and at night, motion detection and recording with the `away` mode.

**Comment by NickM-27** [comment]
@twrecked The web interface supports the feature I am talking about. Including a screenshot for reference
![Capture](https://user-images.githubusercontent.com/14866235/128604666-1bfbc78b-a267-4380-9a66-0bdab3d617f0.PNG)

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#alarm-configuration

Create an alarm device and you can change the mode from there. They are a standard HA `alarm_control_panel` so you can use standard service calls and lovelace cards to change the mode.
