### ISSUE TITLE
Arlo Wire-free camera recordings not showing up in cloud library

### ISSUE THREAD

**Issue by daveyijzermans** [twrecked/hass-aarlo#524]
Hi!

I'm trying to send a record command to all my Arlo cams (they are the wire-free model, the first models). I'm using the aarlo.camera_start_recording service. They seem to record just fine, they wake up, the night vision IR light up and the status in Home Assistant is Recording. However, when recording is done the resulting files are not visible in the cloud library and subsequently not downloaded to Home Assistant (I'm using the save_media_to parameter)

I can't figure out what I'm doing wrong. When I used the record button in the app or in the web interface the camera's also record and the file is shown in the cloud library and downloaded by your integration. So is this a server side problem at Netgear? Or is there something in the integration that makes the server drop the recordings?

Let me know if you want to see any logs. But that might me pointless since it's a cloud/API issue. I did consider maybe the problem is that I'm using those older model cameras. Do you have any clue as to what might be going on? I also tried using my main account instead of my second account with which I share the cameras (to prevent logouts between the Arlo app and Home Assistant)

Kind regards,

Davey.

**Comment by twrecked** [comment]
Can you try adding this to you config?


```yaml
aarlo:
 .. other config
  no_media_upload: True
```

It maybe not getting the event it's expecting.

**Comment by olines** [comment]
Hello!

I am having the same issue.  I added the above config but no change.

Interestingly the thumbnail updates but no video appears to be saved to the server.  I can see the camera recording (IR lights) and the status on the card says recording...

I tried on Pro, Pro 2, and Doorbell varieties with same results...

Thanks.

**Comment by daveyijzermans** [comment]
Config change didn't work for me either. Is there any debug info to provide you with that could help diagnose the issue?

**Comment by krelltunez** [comment]
Hi all.  My setup is a bit different (I don't use HA to trigger recordings), but I'm experiencing the issue as well.  What I'm seeing is that all my thumbnails in HA show "0" in the counter (even though there have been events) and as @olines mentioned, the thumbnail shows the latest event.  However, when clicking on the library (or on the thumbnail), I'm only seeing videos from yesterday.  I'm not exactly sure when this issue started.

FYI, I'm not using the beta.  I'm on v0.7.1.8 of the integration.  Also, I checked my.arlo.com and the recordings do show up in my library there.

Thanks!

**Comment by olines** [comment]
Issue has resolved itself for me with v0.7.2b7

**Comment by daveyijzermans** [comment]
Working for me now as well!
