### ISSUE TITLE
Arlo Pro 3 Floodlight camera not detected

### ISSUE THREAD

**Issue by neilsleightholm-paxton** [twrecked/hass-aarlo#526]
I have just added an Arlo Pro 3 Floodlight camera to my setup (device 7 if that matters). I have enabled logging and I can see it detecting the other 6 devices but not the new one.

I believe this device is supported by aarlo, is there anything else I can do to get it detected?

**Comment by twrecked** [comment]
Did you share the device with your second account?

**Comment by neilsleightholm-paxton** [comment]
Doh, of course completely forgot that. Will give that a try.
