### ISSUE TITLE
Component Doesn't Have Devices Defined in Home Assistant?

### ISSUE THREAD

**Issue by NickM-27** [twrecked/hass-aarlo#528]
Just curious, I was wondering if there are any plans to add a HA device for each Arlo Device. For example I have my Driveway Cam which of course has all of its associated entities but there is no HA device which contains those entities. I think it would be nice to have `Driveway Cam` device which has `control`, `sensor`, and `diagnostic` entities categorized to make them easier to work with.

The reason I am asking is because I just wanted to make sure there isn't a reason this hasn't been done already.

**Comment by twrecked** [comment]
Hi.

Sorry, I don't think I understand the question. You want a single device with more attributes? Do you have an example of a device that does this?

Thanks.

**Comment by NickM-27** [comment]
@twrecked Sure I will provide a few examples. In my experience all my other components work in the way I am describing.

For example:

My zigbee temperature / humidity sensor:
![temp_sensor_ex](https://user-images.githubusercontent.com/14866235/143777504-6c7ca78e-5654-4b1a-baa7-c12a82b98ccc.png)

My zigbee air vent:
![vent_ex](https://user-images.githubusercontent.com/14866235/143777522-b7fe277e-7ab7-4b23-88c1-e8b7cdd5ed03.png)

And my front door lock:
![lock_ex](https://user-images.githubusercontent.com/14866235/143777535-b567a695-ab74-44aa-9991-5b9b29fde319.png)

They all have a `device` which contains the entity so it is easier to have things organized and related to each other.

**Comment by twrecked** [comment]
Gotcha. I'll take a look. The integration needs some updating in these areas.

Forgive my ignorance, but how do you get to those screens?

**Comment by NickM-27** [comment]
@twrecked Sure, from the dashboard it is `Configuration` -> `Devices` and then tap on any device

![Screenshot 2021-11-28 101003](https://user-images.githubusercontent.com/14866235/143778469-e971c18a-2b89-495e-9bb8-955aeed63ab6.png)

Also just a note, I am a dev and have contributed to homeassistant a couple of times (nothing too big) and would be happy to help with this as well as adding a config_flow. My only issue is not being super familiar with the HA part of things. I tried looking through a few other components and the docs but haven't nailed down where these devices are created.

**Comment by twrecked** [comment]
Firstly, help is always appreciated! Between my real job and the house the time I've been able to spend on this component has been limited. It should get better soon...

I'm working on 0.8 branch that's (hopefully) fixing a lot of these sorts of issues. It''s also going to have a saner set of defaults and, with those saner defaults, `config_flow` was on my TODO list.

And just to comment on your update, I find the HA development docs underwhelming, I usually start with them and then `grep` among the components to see how they handle it.

I just thought, for the device issue, see what the original Arlo component does, it maybe fixed there and this code is based on that component.

**Comment by NickM-27** [comment]
@twrecked Totally understand! Having finally found that doc it seems all that would be needed is that the entities would all define the device info with an identifier like MAC or SERIAL. 

I would like to work on a PR for this, but have a couple questions:

- I'm not seeing a 0.8 branch here so is that still a WIP and I should hold off? I don't want to do the work for this without those changes as it may already be improved and I would potentially cause conflicts.

**Comment by twrecked** [comment]
Thanks for attempting this!

`master` is 0.8 branch. `version-0.7x` is the 0.7 branch.

The big change is the I removed the `pyaarlo` directory from 0.8, and I definitely haven't changed this area, so I think this change will drop into both of them. And when you have something working I'll just check out your branch and try it here.

**Comment by NickM-27** [comment]
@twrecked Awesome! I went ahead and got started, might have a question or two in the PR but it should be submitted in 30 mins or so.

**Comment by twrecked** [comment]
I'm running errands at the moment, in case I don't answer quickly, but I'll take a look later. Thanks!

**Comment by NickM-27** [comment]
@twrecked Based on the info in the PR, looks like the config_flow is required for this to work as well. That being the case, I have gone through the docs and could definitely write the code for the config flow but I would definitely need your collaboration on deciding the flow for how the flow should work and which items should be selectable and which items should only be configurable in the configuration.yaml

**Comment by twrecked** [comment]
Sounds good. You should target 0.8 then because that one is where I'm planning on making the defaults better.

I was hoping to get it down to just the equivalent of this:

```yaml
aarlo:
  username: username
  password: password
  tfa_username: your-user-name
  tfa_password: your-imap-password
  tfa_host: imap.host.com
```

But, looking at the different entities,  I think we might need to add a few more options. I guess people can always fall back to `configuration.yaml`.

**Comment by NickM-27** [comment]
Okay sounds good, I will create a separate PR for that then
