### ISSUE TITLE
Motion sensors not functioning

### ISSUE THREAD

**Issue by techtim89** [twrecked/hass-aarlo#533]
Was prompted last night for an update to Aarlo via Hacs.  After updating my cameras all appear to be working and showing last motion recordings.  However the motion sensor is no longer functioning within Hassio.  Anyone else?

**Comment by twrecked** [comment]
Seeing this here. I'll take a look.

I must have missed something moving to the new backend.

**Comment by twrecked** [comment]
Should be fixed in `b3`. I broke event reporting adding support for the enhanced device reports.

**Comment by techtim89** [comment]
Thank you!!  Working great now!

**Comment by techtim89** [comment]
Thank you!! Working great now!
