### ISSUE TITLE
Aarlo integration - Arlo Camera Motion sensors are showing as unavailable and not detecting motion - was working before 

### ISSUE THREAD

**Issue by Ralcidonis** [twrecked/hass-aarlo#535]
I believe this started after installing the most recent update last week.

I have four Arlo cameras, including a video doorbell.

First, the last capture service was constantly showing "None" in the string that's returned by the API. I was getting the object detection: person, vehicle, animal.

I use the motion sensors to turn outside lights on. As of the last few days, the motion sensors have not been working. In the developer options, they show as being "unavailable" and cameras are "idle."

I modified the config and added the extra parameters from the docx to help with disconnection issues. I restarted HA several times. I commented the binary sensors and restarted HA to force a reload, to no avail.

No authentication failures noted in the notifications after restart. so, the integration is loaded, I thinkn..

Outside of HA, cameras are working fine.

**Comment by NickM-27** [comment]
These seem to be working for me, what model cameras are they?

Also, can you put your config from inside configuration.yaml?

**Comment by Ralcidonis** [comment]
They are Arlo Pro 2 Cameras and an Arlo video doorbell.

 

My config is already within the config.yamll. Are you advising to move it out of there?

 

Thank you so much for your assistance!

**Comment by NickM-27** [comment]
No I'm just asking to share what's in there here so it's clear what config options are setup and such, just to compare to mine

**Comment by Ralcidonis** [comment]
If it helps to better diagnose, here is my current config:

 

 

aarlo:

  host: https://my.arlo.com

  username: !secret arlo_user

  password: !secret arlo_pass

  db_motion_time: 30

  db_ding_time: 10

  recent_time: 10

  last_format: '%m-%d %H:%M'

  refresh_devices_every: 3

  stream_timeout: 180

  request_timeout: 120

  reconnect_every: 90

  verbose_debug: False

  tfa_host: 'imap.gmail.com'

  tfa_type: email

  tfa_username: !secret GV_USER

  tfa_password: !secret GV_PASS

 

 

alarm_control_panel:

  # Uses the custom arlo integration found in HACS

  - platform: aarlo

    home_mode_name: home

    away_mode_name: Armed

    trigger_time: 30

    alarm_volume: 8

 

 

sensor:

  - platform: aarlo

    monitored_conditions:

    - last_capture

    - total_cameras

#    - battery_level

    - captured_today

    - recent_activity

    - signal_strength

 

camera:

  - platform: aarlo

 

binary_sensor:

  - platform: aarlo

--------

 

Thanks!

**Comment by Elox1991** [comment]
I think Arlo made some changes. Motion stopped working for me around one week ago (Arlo wirefree doorbell)

**Comment by Ralcidonis** [comment]
Thank you for confirming your experience. The timeline is consistent with my situation as well. My wife came home and told me that the outside lights did not come on. I went into the developer options and observed that the reported states were “unavailable” for the sensors.

 

The object detection was also reporting “unavailable” and not the last object detected. I turned off an automation I had based on that sensor.

 

Rod,

**Comment by DerHerzog7** [comment]
I noticed my motion stopped working about a week ago or so as well, but is just showing 
"clear" in hass.

**Comment by twrecked** [comment]
I'll double check it here.

What version of Home Assistant are people on?

**Comment by NickM-27** [comment]
I'm on `2021.11.5`

**Comment by Ralcidonis** [comment]
Me, too. I  am on core-2021.11.5/.

Thank you so much for your time looking into this.

**Comment by twrecked** [comment]
I'm on 2021.11.3 and it's working here. 

Can you check you are getting the events on `my.arlo.com`? Use your HA account to login and check the motion icon is changing colour.

**Comment by Elox1991** [comment]
I rolled back to Aarlo v0.7.1.8 and now my motion sensor is working.👌

**Comment by twrecked** [comment]
Interesting, it means they haven't moved everybody to mqtt yet. And I just noticed one of my accounts doesn't use it...

I'll poke around. 

Just use `0.7.1.8` for now, there are no big changes.

**Comment by Ralcidonis** [comment]
What is the process for rolling back please. I am on an install on a VM on windows?

**Comment by twrecked** [comment]
If you are using HACS I think you can just select the release you want to install. There are no configuration changes.

I'll push a version that supports both MQTT and SSE this weekend. I'm trying to see if there is a way to automatically detect when to use MQTT or not.

**Comment by Elox1991** [comment]
> What is the process for rolling back please. I am on an install on a VM on windows?>
_**HACS**_ -» Integrations -» Click on the dots next to _**Arlo Camera Support**_ -» Redownload -» Select the release you want. Done!

**Comment by DerHerzog7** [comment]
They've just updated the doorbell with new firmware which also allows it to be added to hubs. Would this change anything?

**Comment by Ralcidonis** [comment]
I appreciate you man. I will wait to test the new release.

**Comment by Ralcidonis** [comment]
Hi Steve:

 

Appreciate your time looking into this…

 

I installed the update you pushed out this weekend but the problem persist: no motion detection.

 

In case this is helpful, I went ahead and removed the entire integration and restarted from scratch. Regardless of what I do, the binary sensor and the sensors will not install. I have restarted HA multiple times. Only alarm, switch, and camera entities get installed.

 

I downgrade and upgraded to latest, to no avail.

 

Here is my config below. Could it be that Aarlo stop supporting the Pro 2s?

 

aarlo:

#  host: https://my.arlo.com

  username: !secret arlo_user

  password: !secret arlo_pass

  db_motion_time: 30

  db_ding_time: 10

  recent_time: 10

  last_format: '%m-%d %H:%M'

  refresh_devices_every: 2

  stream_timeout: 120

  verbose_debug: False

  tfa_host: 'imap.gmail.com'

  tfa_type: email

  tfa_username: !secret GV_USER

  tfa_password: !secret GV_PASS

 

alarm_control_panel:

  # Uses the custom arlo integration found in HACS

  - platform: aarlo

    home_mode_name: home

    away_mode_name: Armed

    trigger_time: 30

    alarm_volume: 8

 

camera:

  - platform: aarlo

 

sensor:

  - platform: aarlo

    monitored_conditions:

    - last_capture

    - total_cameras

    - battery_level

    - captured_today

    - recent_activity

    - signal_strength

 

binary_sensor:

  - platform: aarlo

    monitored_conditions:

    - motion

    - sound

    - ding

    - cry

    - connectivity
