### ISSUE TITLE
Sensors and  binary sensors not recognized/loaded  in HA from config file

### ISSUE THREAD

**Issue by Ralcidonis** [twrecked/hass-aarlo#544]
I am filing this as a different issue since I performed a complete install of Aarlo to get motion working again. 

After uninstalling the integration  and re-installing it  with all sensors removed, now the integration will not load sensors and binary sensors after restarting HA.  I have restarted HA several times, to no avail.

I reported earlier the issue with motion detection being broken on cameras and doorbell. In a desperate move, I went ahead and performed a fresh install to see if that could resolve the problem and now sensors are not loading at all.

The integration is authenticated as I received the AUTH email on Gmail after HA started..

Thanks.

**Comment by throgmortin** [comment]
I have the same issue

**Comment by Ralcidonis** [comment]
We can close this issue. I Deleted for a 3rd time and re-install the integration, and now my sensors are installed, though the video wired doorbell camera is not detecting motion in the AArlo.
