### ISSUE TITLE
streaming on raspberry pi

### ISSUE THREAD

**Issue by maheus** [twrecked/hass-aarlo#55]
Hello,

 it is not a real issue but a important information.
On raspbian (Raspbian GNU/Linux 9), the streaming with aarlo doesn't work out of box.
I doesn't had any error in homeassistant log, only   `[homeassistant.components.stream] Started stream: rtsps://XXXXXXX`
after some tests , i realize, if i want to read rtsps protocol, ffmpeg send me (`Operation not permitted`) , 
If i use ffmpeg 4.1.2 on my Arch , the stream is ok.

i think that  most important difference is version of libraries used by Pyav : 
- libavformat (v57 on rpi , v58 on Arch)
- libavcodec (v57 on rpi , v58 on Arch)
...

I had to compile ffmpeg  (i removed package libavformat57 and libavdevice57 before) ,
i used modified script posted here https://community.home-assistant.io/t/arlo-replacement-pyarlo-module/93511/293 .
And finaly i manually compiled  av with the sources (the next week , i will test with  pip )
After this the stream works ;)
 
it may be necessary to update the documentation in relation to this

**Comment by twrecked** [comment]
Thanks. I'm looking to release 0.5 this week - the last release before trying to get into the official build - so I'll add this information to the release notes.

**Comment by twrecked** [comment]
Thanks, And closed because I added a quick note in README.md in #67

**Comment by twrecked** [comment]
..forgot to close on previous comment..
