### ISSUE TITLE
Config flow incorrectly requires TFA details

### ISSUE THREAD

**Issue by jesserockz** [twrecked/hass-aarlo#550]
The config flow has the TFA details marked as required, but TFA is not a requirement for an account to log in, you are able to disable the TFA on an account (like I have for my secondary HA account).

**Comment by pinkfloydFR** [comment]
How do you do this ? TFA is required now, no option to disabled it :(

**Comment by jesserockz** [comment]
I think at the time it became a requirement, I was also able to disable it again after enabling it. The option looks to be gone now, but my second account works perfectly fine without it.
