### ISSUE TITLE
TFA with smartphone

### ISSUE THREAD

**Issue by PGalteau** [twrecked/hass-aarlo#555]
Hello,
i try to set up arlo, but i have some trouble with TFA.
My authentication against Arlo is done with my validation on my (android) phone, so no email.
And when i authenticate on my.arlo.com i receive a request on my phone.

I did the setup on Google, with a password app, but i never receive email when i authenticate.
In any case, as it seems mandatory on the addin, i did it.

Here is my config:

aarlo:
  host: https://my.arlo.com/
  username: myemail@mydomain.com
  password: mypasswd
  user_agent: linux
  tfa_email: myemail@gmail.com
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: myemail@gmail.com
  tfa_password: mypassword_app

I don't have a real much and clear log in /config/home-assistant.log:

2022-01-06 15:15:26 INFO (SyncWorker_3) [pyaarlo] pyarlo 0.8.0a13 starting...
2022-01-06 15:15:26 WARNING (SyncWorker_3) [pyaarlo] request-error=CloudflareChallengeError
2022-01-06 15:15:27 WARNING (SyncWorker_3) [pyaarlo] request-error=CloudflareChallengeError
2022-01-06 15:15:28 WARNING (SyncWorker_3) [pyaarlo] request-error=CloudflareChallengeError
2022-01-06 15:15:29 ERROR (SyncWorker_3) [pyaarlo] authentication failed
2022-01-06 15:15:29 ERROR (SyncWorker_3) [custom_components.aarlo] unable to connect to Arlo: attempt=44,sleep=300,error=authentication failed

Can someone help me ?

**Comment by twrecked** [comment]
You're seeing cloudflare issues, it's not even getting to the "real" authentication.

Take a look here:
https://github.com/twrecked/hass-aarlo#cloud-flare

**Comment by PGalteau** [comment]
Progression: it's OK.

I did create a new login on Arlo portal, dedicated for my HA, and gave it 'delegation', and a 2FA with email.
I read this in an article, and found it really clever:
_Username and password will be the login you use for the Arlo app on your phone. I would create a new account and share your devices with it. Otherwise every time you login into your app you will kick Home Assistant out and vice versa._ 

So now i received email (first as spam, but i did the exclude in my filter), and it works fine in HA.

My only remaining trouble is with integration panel, as Arlo does not appear, but i can see entities in listing, so it seems fine now.
