### ISSUE TITLE
Question about motion detection 

### ISSUE THREAD

**Issue by kzagatti** [twrecked/hass-aarlo#556]
Hi

I'm using 2 Arlo cameras positioned in different parts of the house and I'm trying to use their motion sensors to turn some lights on as I pass by.  What I want to do is:

- I pass by camera 1, it detects motion and reports to HA;
- When I pass by camera 2, it also detects motion and HA then turns the lights on.

The issue is that they're a bit far one from another and the motion sensor "turns off" so the automation I have, triggered by motion on camera 2, if there's motion on camera 1 too, does not work properly.

Question is: can I increase the time motion is reported as "on"? Or would you suggest me to work with HA templates to get the last time the state was changed?

Thanks in advance!

**Comment by twrecked** [comment]
I'll think about this one, in the mean time you might look at the recently active sensor. You can set how long it says `on` after an event on the camera. Maybe have camera 2 checks camera 1's recently active sensor.

You can configure the recently active timeout.

**Comment by kzagatti** [comment]
Hi @twrecked, thanks for replying.

Please, when you say I "can set how long it says on after an event on the camera", how do I do it?

Thanks in advance.

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#all-parameters

Look at `recent_time`. You can create a `recent_activity` sensor that will stay on for `recent_time` seconds after a camera detects activity.

**Comment by kzagatti** [comment]
Thanks @twrecked, it does work as expected, so I'm closing this thread.
