### ISSUE TITLE
New Camera

### ISSUE THREAD

**Issue by ddjobe** [twrecked/hass-aarlo#558]
I am using the HACS Aarlo integration.  I added a new camera to my Arlo setup but it is not being added into HA.  I can't seem to figure out how to get it added.

**Comment by twrecked** [comment]
Did you share the camera with your Home Assistant account? Did you restart Home Assistant?

**Comment by ddjobe** [comment]
Steve, thanks for the reminder.  I shared and restarted.  It showed right up.
