### ISSUE TITLE
Authentication error.

### ISSUE THREAD

**Issue by tomlynn** [twrecked/hass-aarlo#559]
I'm a new adopter and am encountering the cloudflare challenge error:
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:676
Integration: aarlo (documentation, issues)
First occurred: 4:36:31 PM (42 occurrences)
Last logged: 5:45:19 PM

request-error=CloudflareChallengeError

I'm using version 0.7.2b7

I can log into my.arlo.com using the credentials supplied to the integration.  I can also login to the secondary gmail account I'm using for the challenge email.  Those emails are arriving as expected when logging into arlo with the web browser, but are absent when the integration is making the attempt.  Does the integration mark itself as trusted at any time, assuming it had a successful go?  Or does the my.arlo.com url have to be modified to included the original token that gave me hell when I first set  up the "friend" account?

Decided to login manually to my.arlo.com and watch for the session being closed when the integration attempts to login, but it never happened, so this looks like credentials, which I've checked several times.
Changed credentials and no improvement.  It's as if the login to my.arlo.com is failing or is not being attempted, resulting in no email with code and therefore no two factor authentication takes place.  

This notification happens after the integration is started:  aarlo Component Setup
Error: 2fa startup failed
If error persists you might need to change config and restart.

I've noticed this issue is closed, so I'll copy it to a new issue.

**Comment by gjelsoe** [comment]
Had the same issue with my config, try to add this to your aarlo: section

user_agent: Android

That worked for me.

**Comment by tomlynn** [comment]
Changing user_agent to Android did not help.   Thanks, though.

**Comment by twrecked** [comment]
I'm sorry you're having these issues, if you're seeing cloudflare error messages then the code isn't even getting to `Arlo` to login. It's a real pain and affects me as well.

Try some of the suggestion [here](https://github.com/twrecked/hass-aarlo#cloud-flare).

And one person found out that waiting 24 hours before trying again seemed to help. The good news is, once you're in it seems to work ok going forward.

**Comment by tomlynn** [comment]
I'm currently in the waiting phase.

**Comment by tomlynn** [comment]
Having waited the 24 hours, I've tried again, without success.  I've tried the /etc/hosts fix and set the user-agent to Android and alternately random.  Nothing is working.  Anybody know where I can buy a rubber chicken?

**Comment by twrecked** [comment]
That sucks. Is it the same cloud flare error or did it change to something else?

I appreciate the following is grasping at straws but:

Can you try restarting your router? Would your ISP give you another address if you do that?
Is it possible to try a VPN?

**Comment by tomlynn** [comment]
Here's the cloudflare error(s):

2022-01-24 18:39:02 WARNING (SyncWorker_7) [pyaarlo]
request-error=CloudflareChallengeError
2022-01-24 18:39:04 WARNING (SyncWorker_7) [pyaarlo]
request-error=CloudflareChallengeError
2022-01-24 18:39:05 WARNING (SyncWorker_7) [pyaarlo]
request-error=CloudflareChallengeError

They're all the same, I guess it justs tries three times.

**Comment by tomlynn** [comment]
Switching to a new IP address was not successful, either.
