### ISSUE TITLE
Stream via 'play_stream' service to Chromecast

### ISSUE THREAD

**Issue by Swiftnesses** [twrecked/hass-aarlo#56]
Firstly, this is working perfect!

I was just wondering if you knew of a way to stream with sound too (streaming via the 'play_stream' service provides video, but not audio). I still need to get streams working via HA (I'm running Ubuntu).

**Comment by twrecked** [comment]
I'll give it a try tonight. I really don't have much control over the streaming - I just tell the `stream:` subsystem where to look - but I thought HLS included audio.

**Comment by friendodevil** [comment]
can you please share your automation calling play_stream to Chromecast.
I'm looking to stream from aarlo to motioneye, any idea how to get this going?

**Comment by twrecked** [comment]
Did you get this going?

**Comment by Swiftnesses** [comment]
Sure did (minus sound)!

**Comment by twrecked** [comment]
Brill, I'll close this.
