### ISSUE TITLE
Cameras work fine, Arlo Doorbell does not return data

### ISSUE THREAD

**Issue by mermelmadness** [twrecked/hass-aarlo#564]
I have 3 Arlo cameras that return good data for the video, sensors, current state, etc.  I also have an Arlo Doorbell, which does not return all data.  As you can see from the pictures, the Motion data for the doorbell never changes from Clear.  The regular cameras do.  While the battery is not necessary since it's hard wired, the signal strength, motion, and recent activity come through as unknown.  The "connected" status even says disconnected.  Not sure what's different about the doorbell but it's not sending proper data to aarlo.  The Arlo app on my phone detects everything from the doorbell just fine.
![image](https://user-images.githubusercontent.com/38080873/151644497-e6a5e40d-0a34-4555-8eb6-83fa999311a6.png)
![image](https://user-images.githubusercontent.com/38080873/151644522-7be54cbf-1803-4671-a245-206468878609.png)
![image](https://user-images.githubusercontent.com/38080873/151644569-9dc415b8-c9a3-42c0-864c-0f500790bd08.png)

**Comment by twrecked** [comment]
Can you try using a different back end?

```
aarlo:
  ...
  backend: sse
```

If that doesn't work we can turn on some extra debug.

**Comment by mermelmadness** [comment]
> Can you try using a different back end?
> 
> ```
> aarlo:
>   ...
>   backend: sse
> ```
> 
> If that doesn't work we can turn on some extra debug.

Like this?

aarlo:
  username: *******@gmail.com
  password: *******
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: *******@gmail.com
  tfa_password: *******
  backend: sse

**Comment by twrecked** [comment]
Exactly. Arlo is moving to a MQTT system and it works for some people and not for others.

**Comment by mermelmadness** [comment]
That did it.
![image](https://user-images.githubusercontent.com/38080873/151685276-546f34d6-8e8d-424c-ac20-fb2d2a5c1dd2.png)

Thanks so much.  I'm getting a Zigbee dongle on Monday and will be using Zigbee2mqtt, but I have MQTT installed.  Is there any way to get the signals directly from the cameras instead of having the delay of the cloud?

**Comment by mermelmadness** [comment]
Though now I can't seem to manually turn on my camera lights...
![image](https://user-images.githubusercontent.com/38080873/151685387-e9adf3f5-ad2e-4d7b-8f9e-9247bd923ac4.png)

**Comment by mermelmadness** [comment]
Nevermind, I had to add the lights to the config yaml this time.

light:
  - platform: group
    name: Driveway
    entities:
      - light.driveway_east
      - light.driveway_north
      - light.driveway_west
  - platform: aarlo
    entities:
      - light.aarlo_driveway
      - light.aarlo_westbrook
      - light.aarlo_floodlight

**Comment by twrecked** [comment]
Glad you got it working.

There is no way to get to the cameras directly, they talk to the cloud and so do you...

**Comment by mermelmadness** [comment]
So be it.  Oh well.  Odd that the doorbell now shows a battery of 37% even though it's hard wired.  Whatever.  Thanks so much for this custom integration, it's fantastic and much easier to access than the app itself.  The custom card doesn't really work on my tablet, but it's an old Asus Nexus 7, so I'm not surprised.  Works fine on my iPhone.
