### ISSUE TITLE
Arlo setup problem

### ISSUE THREAD

**Issue by paulonHA** [twrecked/hass-aarlo#565]
Hi everyone, 
I am quite new to all of this and i have no experience in coding.  I am trying to setup the Arlo Hacs integration for my camera but something seems to be not rigth. Before someone is asking, yes TFA is setupa, yes I have also the App Password from gmail and yes the system was restarted already several times but I keep finding the following error message ion the log: No devices returned from /hmsweb/v2/users/devices?t=1643450180057
Can someone please help me with this one? Thanks in advance.
Here also my code. I know the indentations are  not showing correctly here, it is just to know if there is a major problem in the code itself.

aarlo:
  host: https://my.arlo.com
  username: user
  password: pass
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2
  verbose_debug: True
  tfa_host: 'imap.gmail.com'
  tfa_username: other user
  tfa_password: other pass

camera:
  - platform: aarlo
        
sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
    
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

**Comment by twrecked** [comment]
If you're seeing that message then you've made it passed the Arlo authentication.

Can you try turning on debug and see if any other messages are coming out? You can find out how to [here](https://github.com/twrecked/hass-aarlo#debugging). But a good place to start is with this:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    pyaarlo: debug
```

Also look out for any `traceback` lines.

**Comment by paulonHA** [comment]
Hey thanks for your quick reply. So I copied the whole code from, your link and here is what I get as result:
Logger: aiohue.util
Source: /usr/local/lib/python3.9/site-packages/aiohue/util.py:175
First occurred: 14:32:12 (14 occurrences)
Last logged: 14:32:12

Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]

**Comment by paulonHA** [comment]
So apparently the error is related to the Hue system, my bad sorry. But still no working arlo system. I have 2 more error messages, the one that i posted in my first message and the second one is : connection pool is full, discard connection. Which i'm not sure it is related to the arlo. Please help me to understand this.

**Comment by paulonHA** [comment]
Problem solved! Thanks a lot dude. So I was watching the log for a while. I got the idea that something was wrong with the 2nd account that I created for the use in HA. And exactly. Somehow the 2nd account didn't get confirmed. Now as it is, everything is working. Sorry for bothering.
