### ISSUE TITLE
AttributeError: 'AarloFlowHandler' object has no attribute 'email'

### ISSUE THREAD

**Issue by msawyer91** [twrecked/hass-aarlo#566]
First let me say I'm very appreciative of the community for building an Arlo connector for Home Assistant. It appears the "official" Arlo add-in is no longer maintained and it is not available in the Home Assistant store.

I have Home Assistant Container running on a Raspberry Pi 4. The Container installation doesn't officially support the Home Assistant Store, so I have to add integrations/add-ons manually or via HACS. I did also set up Home Assistant in a Hyper-V virtual machine. But, when it comes to Aarlo, I am encountering the issue of "AttributeError: 'AarloFlowHandler' object has no attribute 'email'".

I downloaded aarlo and deployed the aarlo folder into /custom_components, restarted HA, then updated /configuration.yaml to add the following entries:

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  tfa_host: 'imap.gmail.com'
  tfa_username: !secret arlo_tfa_username
  tfa_password: !secret arlo_tfa_password
  reconnect_every: 90
  stream_snapshot_stop: 0
  save_media_to: "/config/www/arlo/${Y}/${m}/${d}/${T}"

I then made the following entries in secrets.yaml:

arlo_username: mycleveremailaddy@gmail.com
arlo_password: mysupersecretpasswordstoredinplaintext
arlo_tfa_username: samecleveremailasarlo_username@gmail.com
arlo_tfa_password: mysupersecretapplicationpasswordgooglecreatedforme

I restarted HA, then went to enable Arlo Camera Support. I am immediately prompted to enter my Arlo username and password, along with my TFA username, TFA password, and TFA host. I re-enter the same information, and am informed an unknown error was detected. Portainer allows me to see the container log, which reports:

2022-01-31 23:50:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/aarlo/config_flow.py", line 42, in async_step_user
    title=f"${DOMAIN} - ${self.email}", data=info
AttributeError: 'AarloFlowHandler' object has no attribute 'email'

I received the same error when I created an Arlo account using my Comcast email, which actually had 2FA enabled. My Gmail account doesn't have 2FA enabled, but Aarlo is requiring me to provide TFA details anyway.

Where have I made a boo-boo?

Matt

**Comment by msawyer91** [comment]
I dug into this a bit more today, since it was calling out line 42 in config_flow.py. I put a try/except block around line 42, so it now reads like:

            else:
                try:
                    return self.async_create_entry(
                        title=f"${DOMAIN} - ${self.email}", data=info
                    )
                except:
                    print("Exceptions were detected by the Server.")
                    return self.async_create_entry(
                        #title=f"${DOMAIN} - dojonorth@gmail.com", data=info
                        title="Arlo Cameras", data=info
                    )


Restarted HA, got a new error. This one was "AttributeError: module 'custom_components.aarlo' has no attribute 'async_setup_entry'" Thankfully the search consultants of the Googlé were either on their game, or my query was good enough. I found the exact same error on another HA integration, duofern. Their fix? Add the following two lines to __init__.py:

async def async_setup_entry(hass, entry):
    return True

Rebooted HA again. I had a few other small issues to work through, like remembering to grant Administrative rights to my Arlo HA account. But once I had done that, and added all necessary options to my configuration.yaml file, I saw my cameras and was able to test out the siren which earned me snarky feedback from my daughter. :)

So overall I think I'm good to go! I'm not sure if what I did to config_flow.py was the most appropriate course of action; I just wanted to see if I could get past the error, and it worked. I'll leave it to your team to determine the best long-term strategy. It would seem, however, that HA does want to see the call to async_setup_entry in the __init__.py though.

Matt

**Comment by twrecked** [comment]
Well done on getting 0.8 going! That stream is still very experimental and - truthfully - I haven't had much time to look at it recently. Thanks for the fix, it's noted and I'll probably use it when I get round to testing the release here.

If 0.8 is working for you then great. But the official release is the 0.7 stream.
