### ISSUE TITLE
Getting 2FA issues again

### ISSUE THREAD

**Issue by cloudbr34k84** [twrecked/hass-aarlo#567]
this morning, i my Aarlo component stopped working. I reset and now it says. I did not notice that Github was down. Would this have caused this issue?

aarlo Component Setup
Error: authentication failed
If error persists you might need to change config and restart.

**Comment by dmeeker-ra** [comment]
I just installed for the first time, as I've just recently been turned on to home assistant. I am getting a 2FA error upon startup also. 


This error originated from a custom integration.

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:454 
Integration: aarlo (documentation, issues) 
First occurred: 10:14:58 PM (6 occurrences) 
Last logged: 10:22:59 PM

unable to connect to Arlo: attempt=2,sleep=30,error=2fa startup failed
unable to connect to Arlo: attempt=3,sleep=60,error=2fa startup failed
unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed
unable to connect to Arlo: attempt=5,sleep=240,error=authentication failed
unable to connect to Arlo: attempt=6,sleep=300,error=2fa startup failed

**Comment by twrecked** [comment]
@cloudbr34k84 github shouldn't affect anything. If you've had it working then it might be a cloudflare issue. Try chaning your `user_agent` and restarting.

@dmeeker-ra This is your first time? Do you need 2 factor authentication, did you set it up? See [here](https://github.com/twrecked/hass-aarlo#imap) for some details. If you're using a gmail account you will need to set up an application password.

@cloudbr34k84  and @dmeeker-ra 

I recommend looking in `homeassistant.log`, it's in the same directory as your configuration, it gives you more information about what might have gone wrong.
