### ISSUE TITLE
unable to connect to Arlo

### ISSUE THREAD

**Issue by paulonHA** [twrecked/hass-aarlo#585]
Hi I am getting several error message for some time and of course the cameras are not working in HA.
- unable to connect to Arlo: attempt=1,sleep=15,error=session start failed
- Setup of aarlo is taking over 10 seconds.
- body-error=JSONDecodeError
- session start failed

Can someone help me and tell to what those error/warning messages are related?

**Comment by JeffSteinbok** [comment]
I'm getting this from the latest release.  Downgrading to the latest non-beta version seems to help.

**Comment by paulonHA** [comment]
Ok thx. Will give it a try
