### ISSUE TITLE
Connectivity Binary sensor for doorbell shows Off even although it is connected

### ISSUE THREAD

**Issue by ehendrix23** [twrecked/hass-aarlo#588]
My connectivity binary sensor is showing Off for my doorbell even although the doorbell is showing online in my Aarlo app.

I did debug but could not see why it would be different. If I could get some initial assistance

**Comment by twrecked** [comment]
Can you try changing the backend you use - see [here](https://github.com/twrecked/hass-aarlo#missing-events).

If that doesn't work can you turn on debug and collect some logs - see [here](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs).

**Comment by ehendrix23** [comment]
That seemed to do it. Now the doorbell is showing On for connected.

Thx!
