### ISSUE TITLE
Entities do not update, but calls still work

### ISSUE THREAD

**Issue by squirtbrnr** [twrecked/hass-aarlo#589]
As of 4/27 at about 3:54pm central time, this component only half works for me.  I can set the monitoring mode and it will be correct in the Arlo app, but the state of the alarm does not update in HA regardless if I set it in HA or Arlo.  I can view past recordings, but they are choppy at best and I also cannot view live video.  The integration will connect and show all the entities, but sensors are stuck showing old values and never update.

I can confirm the cameras are working and my account can log in through a web browser and also has full access rights to the cameras.  This may be an Arlo issue though as they had some issues throughout the day they claim they have solved, but when logging in through the website, live video is choppy at best and sometimes won't play.

**Comment by dewittutonnie** [comment]
Hi, I had a very similar experience since yesterday. Moving from the default mqtt to sse solved all my problems immediately: simply add ‘backend: sse’ to your aarlo: section in your config to give it a try.

**Comment by squirtbrnr** [comment]
thanks, I will give that a try.  I was in the process of deleting the integration and reinstalling it, but that didn't seem to change anything.

**Comment by squirtbrnr** [comment]
I can confirm switching back to the old "'backend: sse'"connection method works and fixes this issue.  It's possible Arlo is having a problem with connections which is why the default MQTT is failing.

**Comment by twrecked** [comment]
Glad you got it working. The sse/mqtt is a pain. Some people seem to need mqtt to work and some people need sse and some people (me included) seem to be able to use both.

I'm trying to figure out if I can detect which to use in the messages I get back from Arlo but haven't had much free time recently.

**Comment by squirtbrnr** [comment]
I used sse for the longest time then finally updated through HACS to the version that supported mqtt.  That was maybe a month ago? and mqtt worked fine... until it didn't yesterday.  I still think it's an issue on Arlo's end as they had some server side issues yesterday and even today the website sometimes just times out when trying to view live video.

**Comment by TheDK** [comment]
The MQTT based variant has been working for 8-10 weeks now for me and stopped working a couple of days ago. Reverting back to SSE solved the problem…

**Comment by QuakeGio83** [comment]
> I can confirm switching back to the old "`backend: sse`"connection method works and fixes this issue. It's possible Arlo is having a problem with connections which is why the default MQTT is failing.

Hi, if I want go back to old backend what I have to do? Thanks in advance

**Comment by squirtbrnr** [comment]
> Hi, if I want go back to old backend what I have to do? Thanks in advance

https://github.com/twrecked/hass-aarlo#missing-events

**Comment by Spiff1** [comment]
I have the same problem, using `backend: sse` seems to solve the issue but only for an hour or so, restarting home assistant will make it will work for an hour again. Calls work al the time but not receiving status from Arlo.

**Comment by weimdall** [comment]
Same issue here, backend: sse fixed some problems, but the information regarding cameras are not updated. 
(A restart can help to temporarily solve the issue on my side..)
