### ISSUE TITLE
unable to read mode, try forcing v2

### ISSUE THREAD

**Issue by tayloracarr** [twrecked/hass-aarlo#593]
I can set the mode, just not getting the read part coming through.

ob-error=AttributeError Traceback (most recent call last): File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next job["callback"](**job["args"]) File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 380, in _refresh_modes base.update_mode() File "/config/custom_components/aarlo/pyaarlo/base.py", line 350, in update_mode self._set_mode_or_schedule(mode) File "/config/custom_components/aarlo/pyaarlo/base.py", line 127, in _set_mode_or_schedule self._save_and_do_callbacks(MODE_KEY, mode_name) File "/config/custom_components/aarlo/pyaarlo/device.py", line 98, in _save_and_do_callbacks self._do_callbacks(attr, value) File "/config/custom_components/aarlo/pyaarlo/device.py", line 90, in _do_callbacks cb(self, attr, value) File "/config/custom_components/aarlo/alarm_control_panel.py", line 233, in update_state self._state = self._get_state_from_ha(self._base.attribute(MODE_KEY)) File "/config/custom_components/aarlo/alarm_control_panel.py", line 349, in _get_state_from_ha lmode = mode.lower() AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by c-scoot** [comment]
I had a similar issue. Switched the backend to sse. All ok

**Comment by tayloracarr** [comment]
> I had a similar issue. Switched the backend to sse. All ok

Thank you! Worked

**Comment by djfanatix** [comment]
Can you explain switch backend to sse?

**Comment by tayloracarr** [comment]
Yes. Within your config file add “backend: sse” to the aarlo setup. Like this:

**Comment by VdkaShaker** [comment]
> Yes. Within your config file add “backend: sse” to the aarlo setup. Like this:

Greetings.... trying to solve this issue on my HA setup, but I can't figure out where to put the `backend: sse` entry.  I've tried putting it in the `aarlo:` section of my configuration.yaml file, which HA accepted, but it did not fix the error in my logs, and when I tried adding it to the `camera:` section where I configured aarlo in my configuration.yaml it is reported as an unsupported entry.

Appreciate further guidance on how others have resolved this log error.

**Comment by tayloracarr** [comment]
> > Yes. Within your config file add “backend: sse” to the aarlo setup. Like this:
> 
> Greetings.... trying to solve this issue on my HA setup, but I can't figure out where to put the `backend: sse` entry. I've tried putting it in the `aarlo:` section of my configuration.yaml file, which HA accepted, but it did not fix the error in my logs, and when I tried adding it to the `camera:` section where I configured aarlo in my configuration.yaml it is reported as an unsupported entry.
> 
> Appreciate further guidance on how others have resolved this log error.

Through the aarlo versions, I found the backend parameter not working anymore either. What is currently working for me is adding parameter  `mode_api: v2` within `aarlo:`. I have older cameras, so that might be the reason.

**Comment by twrecked** [comment]
With the newer builds there is code to determine which `backend` to use based on the data returned from _Arlo_.  If you remove the `backend` setting from the config and [turn on debug](https://github.com/twrecked/hass-aarlo/tree/master#debugging) you can see what is happening by looking for one of the following messages:

```
auto chose SSE backend
auto chose MQTT backend
user chose MQTT backend
user chose SSE backend
```

If you need to override it you can add either

```yaml
  backend: sse
```

or 

```yaml
  backend: mqtt
```

to your `aarlo:` configuration.

Now you've turned debug on, if you want to paste some logs into here I can see why the mode change isn't working.
