### ISSUE TITLE
Service disarmed does not work anymore

### ISSUE THREAD

**Issue by herveaurel** [twrecked/hass-aarlo#594]
the disarm service no longer works.

**Comment by justinmaiuto** [comment]
Yep, I've found the same. I can arm devices, but can't disarm. Also the status does not update in HA after arming via HA. Confirmed the arming command is being processed correctly via the arlo app. Also getting this error in the logs:
This error originated from a custom integration.

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:668
Integration: Arlo Camera Support (documentation, issues)
First occurred: 20:02:04 (8 occurrences)
Last logged: 20:24:04

unable to read mode, try forcing v2

**Comment by justinmaiuto** [comment]
Looked into this more, seems arlo playing with their backend, adding 'backend: sse' to the config file resolved it

**Comment by herveaurel** [comment]
> Looked into this more, seems arlo playing with their backend, adding 'backend: sse' to the config file resolved it

Great !  where exactly do you write this?

**Comment by makz159** [comment]
> Great ! where exactly do you write this?

in your configuration.yaml file for home assistant under the aarlo section
https://github.com/twrecked/hass-aarlo/blob/master/README.md#all-parameters

**Comment by herveaurel** [comment]
> > Great ! where exactly do you write this?
> 
> 
> 
> in your configuration.yaml file for home assistant under the aarlo section
> 
> https://github.com/twrecked/hass-aarlo/blob/master/README.md#all-parameters

this configuration + reboot did not change anything 🙁!
![image](https://user-images.githubusercontent.com/64784541/166147311-3269aaf1-2682-4bdf-aa83-7bc605eb5058.jpeg)

**Comment by suneworld** [comment]
> Looked into this more, seems arlo playing with their backend, adding 'backend: sse' to the config file resolved it

Fantastic!! Worked!!

**Comment by aliaghil** [comment]
That worked for me too. Thank you for sharing it with us.

**Comment by pierrebengtsson** [comment]
Fixed it for me too! Thanks for sharing.

**Comment by dskramst** [comment]
Worked!  Thank you

**Comment by KalleHoppe** [comment]
Hi!
I'm having the same issue. I've added backend : sse but it stil won't disarm. The other custom modes work just fine

**Comment by herveaurel** [comment]
Still the problem since the last HA update.  The disarmed service is not running.
