### ISSUE TITLE
After reboot, cameras no longer update statuses in HA (# of captures, still images, battery status)

### ISSUE THREAD

**Issue by yuckypants** [twrecked/hass-aarlo#596]
HA version: 2022.4.5
aarlo version: 0.7.2b8.2

Noticed after a reboot the other day that the cameras are not updating statuses. HA is not updating attributes on the cameras, like battery level, etc. In fact, today I charged a camera and HA is still showing 20%. I rebooted again just to be sure and the camera entity history shows it was updated, but the battery level hasn't changed - it's still showing 20% even though the camera is actually at 100%. Other attributes got updates, like the number of detected events today, but it has been a static issue since the initial update after the reboot. 

I also noticed after a reboot, I did not receive the arlo authentication email. I checked the login outside of HA and verified that I do receive the login emails and the account is able to login

let me know if any additional information is required. 

Thanks!

**Comment by twrecked** [comment]
Firstly, can you try changing the backend if you have't already - see [here](https://github.com/twrecked/hass-aarlo#missing-events)

Can you turn on debug and send me the logs - see [here](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs)

You can hide the data so only I can see it [here](https://github.com/twrecked/hass-aarlo#hiding-sensitive-data)

**Comment by yuckypants** [comment]
So I enabled the backend, turned logging, and rebooted and now things
appear to be operating normally again.

Not sure why this time is special, but it's good to know this is back to
normal. Thank you anyway, love the work you've done on this.

**Comment by jurgenweber** [comment]
yeah, this backend try solved it for me also

**Comment by krelltunez** [comment]
I was having this issue and upon looking at my configuration I already had sse as the backend. I removed that from the config, rebooted, and all is working now. Strange!

**Comment by krelltunez** [comment]
So much for that.  Removing sse as my backend introduced all sorts of problems, including no longer picking up mode changes.
