### ISSUE TITLE
Aarlo Camera returning incorrect battery settings

### ISSUE THREAD

**Issue by 14Data** [twrecked/hass-aarlo#601]
The Battery Levels appear not to be being updated anymore (they were initially) and are now returning the incorrect values. There don't appear to be any errors relating to this. 

E.g Aarlo battery_level entity show 50%, but if I go to the Arlo app the camera is only at 20%

Similar comparison
HA aarlo 69% Arlo 62%
HA aarlo 81% Arlo 50%

It appears that this is not updating. 

Config
aarlo:
    username: !secret aarlo_username
    password: !secret aarlo_password
    refresh_devices_every: .5
    refresh_modes_every: 2
    stream_timeout: 120
    reconnect_every: 90
    verbose_debug: true

camera:
 - platform: aarlo
sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature

![image](https://user-images.githubusercontent.com/63935656/169637758-cafd18c4-23cd-4fe3-85d7-5ec70eec0e79.png)

**My Arlo app:** 
![image](https://user-images.githubusercontent.com/63935656/169637927-93c489a0-55f9-4d12-b9c8-b9be696108df.png)

I have turned Arlo base station and cameras off and on. 
Updated everything and restarted HA. 

Has anything changed or any idea why the battery levels appear not to be updating? 

Thanks, Tony

**Comment by twrecked** [comment]
Can you try changing the [backend](https://github.com/twrecked/hass-aarlo#missing-events). Arlo has been playing around with things recently.

**Comment by 14Data** [comment]
@twrecked That worked 👍 Thanks for the prompt help.

**Comment by aureaboros** [comment]
> Can you try changing the [backend](https://github.com/twrecked/hass-aarlo#missing-events). Arlo has been playing around with things recently.

@twrecked worked for me as well. Thanks!

**Comment by talljohnson** [comment]
changing the [backend](https://github.com/twrecked/hass-aarlo#missing-events) worked for me as well. Further confirmation that this is a way to fix the interface.
