### ISSUE TITLE
Camera binary sensors and connections stopped working

### ISSUE THREAD

**Issue by winnettjeff** [twrecked/hass-aarlo#610]
About a month ago my Arlo camera binary connections stopped working.  I noticed this when the Homa Assistant automations I had that were triggered by camera motion detection stopped working.  Subsequently I bought 3 more cameras.  They show up in the HA Arlo camera count, and I see their images, but they show up as not connected.  Any thoughts on this?  I really liked having the HP integration of my Arlo cameras working.  Perhaps some config change I'm not aware of?  I think I have logging turned on but I see no log entries for the connections or binary sensors.
Thanks.

**Comment by angrycatmeowmeow** [comment]
I'm having the same issue. Battery and motion don't update, but I am still able to see them/videos in HA and turn them on and off with automations.

**Comment by winnettjeff** [comment]
Hi. Per Rob Coleman,  “Try addingbackend: sseunder aarlo: in configuration.yaml. The transition to MQTT caused some breakage.” This worked for me, I got everything back, again, working as it was earlier. Jeff Sent from Mail for Windows From: angrycatmeowmeowSent: Sunday, July 17, 2022 6:16 AMTo: twrecked/hass-aarloCc: winnettjeff; AuthorSubject: Re: [twrecked/hass-aarlo] Camera binary sensors and connections stopped working (Issue #610) I'm having the same issue. Battery and motion don't update, but I am still able to see them/videos in HA and turn them on and off with automations.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
