### ISSUE TITLE
Video Doorbell not alerting on motion

### ISSUE THREAD

**Issue by TravisRoy** [twrecked/hass-aarlo#613]
I get email and app notifications, but nothing in HA. Nothing in the logs either. I tried my primary and secondary (just for HA) account. I tried sse backend, no luck with anything. Just looking for guidance or what you would need from the logs.

**Comment by TravisRoy** [comment]
IFTTT is also reporting the motion events.

**Comment by bradarussell** [comment]
I'm also trying to figure out how to use motion detected events in my automations.  Are you using motionDetected in a state trigger?  If you're doing something different can you share what you're doing?

**Comment by twrecked** [comment]
Can you post your `binary_sensory` config for Arlo? We should be creating motion sensors you can use in your automations. And remember, you HA Arlo account will need admin access.

If you want to check if you're getting the notifications from Arlo you need to [turn on debug](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs) and look for `motionDetected` in the logs.

**Comment by bradarussell** [comment]
Can more accounts than the primary subscriber have admin access?  I've enabled Access Rights but that's all that can be enabled.

I turned on debug and am getting other log data from aarlo but no motionDetected.  

Pardon me being new, but what config do you want for the binary_sensor?  The name of the entity is `binary_sensor.aarlo_motion_front_door` and it's setup with `Entity Status: Enabled`.  I didn't see other config data I could find other than assignments to zones and naming it.

**Comment by twrecked** [comment]
You need to have "Allow Access Rights" enabled, which you already have.  I need to update the docs for that, it used to be "Admin Access".

The binary sensors looks good, I was actually after this information but it looks like you have it set.

```yaml
- platform: aarlo
  monitored_conditions:
  - motion
  - sound
  - ding
  - cry
  - connectivity
```

In the logs are you seeing anything similar to this?

```yaml
2022-10-24 16:55:00.861 DEBUG (ArloEventStream) [pyaarlo] packet-in=
{ 'action': 'is',
   ...rest of packet
```


Two more things to try:

- Can you log into the [Arlo camera](https://my.arlo.com/) web page with you Home Assistant credentials and check if you see motion detection showing there? You will need top stop Home Assistant while you check this.
- Can you try changing the backend? But the latest versions of the code should detect this.

```yaml
aarlo:
  ..your current config..
  backend: sse
    --or--
  backend: mqtt
```

**Comment by twrecked** [comment]
Can you try the latest release. #646 may have fixed the issue.
