### ISSUE TITLE
Custom updater not working

### ISSUE THREAD

**Issue by Nicxe** [twrecked/hass-aarlo#62]
I noticed that there was changed file on the GitHub and no update in Custom Updates. So I downloaded the latest from GitHub and now custom updater say that I use 0.0.7 but the lattes is 0.0.2. Is the custom updater not updated?
<img width="453" alt="image" src="https://user-images.githubusercontent.com/27124316/58000622-9b175400-7ad9-11e9-813e-60a81958a723.png">

**Comment by rccoleman** [comment]
Did you update all files from github?  It sounds like you may have an older custom_components.json that’s still pointing to my repo.

**Comment by Nicxe** [comment]
Hmm, I think there was something wrong with the URL to custom component.js file, I got it two work now. Thanks!
