### ISSUE TITLE
Latest Camera Images are not Refreshing

### ISSUE THREAD

**Issue by ddjobe** [twrecked/hass-aarlo#627]
The camera images are one day behind.  Anything for today is not displayed.  I originally thought I was losing connection/authentication but that does not seem to be the case.  I'm just not getting today's events.  I turned on logging.  I'm not finding any apparent issues.

Home Assistant 2022.9.2
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

Aarlo v0.7.2b8.3

**Comment by juju159** [comment]
Hello,
do you use the snapshot?
BR

**Comment by ddjobe** [comment]
The snapshot functionality does not seem to be working.

**Comment by blue-hound** [comment]
Hi, came here because I was having the same trouble. Home Assistant writes out the file that I specify but the image in the file is the image from the last time the camera was triggered, not a current snapshot.

**Comment by Aldicarus** [comment]
I found a workaround for the same issue, maybe it works for you. Eventually, at the same time the issue arised on HA, I lost mobile notifications of camera events in an arlo shared family account where, identically to arlo integration, I share access to the cameras through the app. Stop sharing cameras and admin privileges with aarlo and other users, save it and then sharing again all the cameras and admin privileges solved both problems. HA recovered the real time updates (not -1 day) and my family the event notifications. Not sure about the root cause (mayble arlo changed something) but it is still working for the last 2 weeks.

**Comment by ddjobe** [comment]
@Aldicarus, I apologize for my tardy reply.  I was on vacation and away from home.  I tried your suggestion and it did not work.  I completed removed all sharing from Arlo.  Re-added and got everything set up back.  I then restarted HA just for good measure.  I still only get yesterday's last images.

I have updated to the latest HA and am running the latest HACS integration for Aarlo.

@twrecked, what else can I try?

**Comment by ddjobe** [comment]
I think I might have got this fixed.  I read through the documentation again and landed on the Missing Events section.  I decided to try and add **backend: sse** to my config.  I've been running this way since yesterday afternoon and all events compared to my Arlo app are current in HA with my cameras.  I'm going to run like this for a while and I'll report back in.

**Comment by ddjobe** [comment]
Apparently I spoke too soon.  Today I can only see the last events from yesterday.  Back to drawing board.

@twrecked, what else can I try?

**Comment by juju159** [comment]
Hello,

Pluggin is very tricky,

It works a little bit better since I had these lines:

  refresh_devices_every: 2
  verbose_debug: True
  stream_timeout: 120
  reconnect_every: 90
  backend: sse

Except snapshot. It stop to work after a while ...
I hope a new release to improve stability @twrecked 

BR

**Comment by twrecked** [comment]
`sse` is really annoying, they turned it on for a while and everything seemed to work and then they turned it off. For a month it seemed like some people had to have it enabled and some didn't. And `sse` was much nicer for me, I could examine the events coming back from the Arlo servers.

Can you paste in your `aarlo` config - minus the sensitive bits obviously - and what Lovelace cards are you using to view the images?

**Comment by twrecked** [comment]
Snapshots have always been annoying. I have 2 identical cameras here that need snapshots to be triggered in 2 different ways for them to work. It's the same on the Arlo app.

The config items have been taken care of in release 0.8 (which I should have time to work on soon), I choose much saner defaults for those values in that release. There is lots of historical reasons why they don't come as defaults in the 0.7 release.

And you have `sse` working?

**Comment by juju159** [comment]
Hello,

This is the config of my side, I use aarlo-glance

Thanks you for your help @twrecked 

# # # # # # # # # #  Arlo
aarlo:
  username: XXXXX
  password: XXXXXX
  refresh_devices_every: 2
  verbose_debug: True
  stream_timeout: 120
  reconnect_every: 90
  backend: sse
#Aarlo integration
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: XXXXXX
  tfa_password: XXXXXX


alarm_control_panel:
  - platform: aarlo
    home_mode_name: disarmed
    away_mode_name: armed

binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - connectivity

**Comment by ddjobe** [comment]
I forgot to mention, but I also use the aarlo-glance cards.

**Comment by twrecked** [comment]
Sorry, are you all seeing up to date images or are some of you seeing out of date ones still?

**Comment by juju159** [comment]
> Sorry, are you all seeing up to date images or are some of you seeing out of date ones still?

Hello,
In fact it's totally random. I have 3 camera Arlo essential ..
Sometime all are uptodate and sometime several are out of date ...
Now all are uptodate until when ?
BR

**Comment by twrecked** [comment]
@juju159

Can you [turn on some debug](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs) for me. Then you'll need to restart and you can either:
- send me the logs use [this page](https://pyaarlo-tfa.appspot.com/) to encrypt them so only I can see them.
- search the logs for this keyword `mqttSupport` and paste here the entire line if you find it.

**Comment by juju159** [comment]
Hello @twrecked ,

please find encrypted log.

BR
[Encrypted.txt](https://github.com/twrecked/hass-aarlo/files/9795160/Encrypted.txt)

**Comment by twrecked** [comment]
It might not be the issue but the time on your device is wrong, the logs are showing from March 2021.

Can you try correcting that and trying again? I don't think it will cause an issue but it's worth trying.

**Comment by juju159** [comment]
Hello @twrecked ,

Strange, the date on the snapshot seems good on all devices.
I'm not sure that it's possible to change date on camera. It's set automatically with NTP.

**Comment by twrecked** [comment]
It's not the cameras, it looks like the HA device has the wrong date. Your logs all start with this:

```
2021-03-08 09:05:14 DEBUG ...
```

Which is 18 months ago.

**Comment by juju159** [comment]
Heuu nope.
2022-10-16 16:12:10.551 DEBUG (ArloEventStream)  ..
Are you sure did you take the good log?
No 2021 on my log

**Comment by twrecked** [comment]
Let me check my end...

**Comment by twrecked** [comment]
Can you send me the debug when the image should change or does change. One way might be to arm the camera and set the motion detection off.

**Comment by ddjobe** [comment]
> Sorry, are you all seeing up to date images or are some of you seeing out of date ones still?

@twrecked, mine seem to be staying current at this time.  I'm going to watch them over the next couple days.

**Comment by juju159** [comment]
Hello @twrecked ,

Since the reboot of HA.

Snapshot are uptodate.
Maybe I can wait a couple of times. And send the logs when it bugs.
BR

**Comment by twrecked** [comment]
That make sense. When it happens next try making a capture happen (snapshot or motion) and I'll check those logs.

**Comment by juju159** [comment]
Hello @twrecked 
I have a snapshot issue on one camera.
I force a snapshot at 18:45 UTC. Issue is on the camera named Piscine & image is stuck at 17:40 today
BR,
Thanks
[Encrypted.txt](https://github.com/twrecked/hass-aarlo/files/9803690/Encrypted.txt)

**Comment by twrecked** [comment]
So, this line doesn't look right, it looks like something never got cleared.

```
2022-10-17 18:45:13.967 DEBUG (SyncWorker_2) [pyaarlo] request_snapshot::reqs='{'snapshot'}',local='set()',remote='{'snapshot'}'
```

That `remote` entry at the end should look like:

```
2022-10-17 18:45:00.014 DEBUG (SyncWorker_1) [pyaarlo] request_snapshot::reqs='{'snapshot'}',local='set()',remote='set()'
```

That gives me something look at, I'm guessing I'm not clearing up correctly. Do you have the previous snapshot logs?

**Comment by juju159** [comment]
Hello,

Please find the log of the previous snapshot.

[Encrypted.txt](https://github.com/twrecked/hass-aarlo/files/9806776/Encrypted.txt)

When I try since the app it refresh the image.

BR

**Comment by twrecked** [comment]
I think I have to actively clear the remote value. I'll push a fix later today that should better handle it.

In the meantime, can you try calling this service `aarlo.camera_stop_activity` against the camera the next time it happens. It should clear the status.

**Comment by juju159** [comment]
Thanks the trick seems work ;)

**Comment by ddjobe** [comment]
> > Sorry, are you all seeing up to date images or are some of you seeing out of date ones still?
> 
> @twrecked, mine seem to be staying current at this time. I'm going to watch them over the next couple days.

Good morning!  So far my HA is keeping in sync with Arlo.  It appears this combination of settings is my fix.

stream_timeout: 120
reconnect_every: 90
backend: sse

**Comment by getsmokes** [comment]
Hi, I have the same problem. Snapshot works fine and updates, however the recordings do not. If I restart HASS the latest recordings show up fine.

**Comment by ddjobe** [comment]
> Hi, I have the same problem. Snapshot works fine and updates, however the recordings do not. If I restart HASS the latest recordings show up fine.

@getsmokes, since I put in the following lines, Arlo and HA are staying in sync.

refresh_devices_every: 2
stream_timeout: 120
reconnect_every: 90
backend: sse

**Comment by getsmokes** [comment]
> > Hi, I have the same problem. Snapshot works fine and updates, however the recordings do not. If I restart HASS the latest recordings show up fine.
> 
> @getsmokes, since I put in the following lines, Arlo and HA are staying in sync.
> 
> refresh_devices_every: 2 stream_timeout: 120 reconnect_every: 90 backend: sse

I have the same config. Everything works except seeing the updated recordings in the lovelace card. One I restart HASS they update.
