### ISSUE TITLE
Map control panel to schedule?

### ISSUE THREAD

**Issue by fosselius** [twrecked/hass-aarlo#629]
I am trying to configure the control panel for Arlo in a way so that I can map the "away mode" to whats called "Schedule" within the app. However it doesnt seem like it is possible to turn on the schedule in this way. I manage to mapp individual modes from the app to away mode etc, but not the schedule. Am I doing something wrong is is this not supported (yet?)?

**Comment by twrecked** [comment]
You should be able to do this. Let me look.

**Comment by twrecked** [comment]
You could try `schedule.1`  as the mode. If that doesn't work then [turn on debug](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs) and restart HA, you'll see the name to use in the logs.

An example of mine is this:

```
2022-09-26 08:00:05.972 DEBUG (ArloBackgroundWorker) [pyaarlo] schedule.1<=S=>Arm light 7days 6pm-6am
```

The bit you can search for is the `=S=`.

**Comment by fosselius** [comment]
Thank you very much! That worked just fine! I must have been looking in the wrong place in the documentation.
