### ISSUE TITLE
Integration doesn't appear after install via HACS

### ISSUE THREAD

**Issue by andypburke** [twrecked/hass-aarlo#630]
I installed via HACs but the integration doesn't appear when trying to add.  I am running HA on a Synology NAS in a docker container. 

 Is there anything specific I need to do differently?

**Comment by davidoxe** [comment]
This needs to be setup in the configuration.yaml file. No UI setup possible.

**Comment by andypburke** [comment]
Thanks.  I have managed to get this setup and also the aarlo glance to show the camera streaming.  It works well on a computer browser but not on my iPhone.  Any idea what is wrong?

**Comment by twrecked** [comment]
I'll take a look. What kind of computer is it? MAC or PC?

**Comment by andypburke** [comment]
It works on a Mac but I can’t stream on my iPhone.  Thanks.

**Comment by twrecked** [comment]
Can you paste in your Lovelace card configuration?

**Comment by andypburke** [comment]
`type: custom:aarlo-glance
entity: camera.aarlo_kitchen_camera
name: Kitchen
image_view: direct
image_top: name,status,date
image_bottom: motion,library,stream,sound,snapshot
image_click: stream
library_sizes: 3,4,2`
