### ISSUE TITLE
Flux Video

### ISSUE THREAD

**Issue by schumi2309** [twrecked/hass-aarlo#635]
Hello,
For me, it's impossible to have the video stream in HA. (arlo doorbell to battery)
when I ask for the stream, my camera becomes unavailable.
Is there something to do to fix this problem?
Thank you.

**Comment by twrecked** [comment]
Can you turn on some debug and send it to me? See [here](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs).

I only need the events when you try to stream.

And what is Flux?
