### ISSUE TITLE
Arlo HA Credentials

### ISSUE THREAD

**Issue by feron81** [twrecked/hass-aarlo#641]
Hello

I copied the aarlo folder to my "custom_components" and I'm now able to add the arlo integration in HA.

Now I have to enter the username and TFA username etc. This is not working for me. I get everytime the message "Error occured". Is TFA 2 two factor authentification for the mail account and the "normal" username and password the login for arlo?
Is it possible to setup the Arlo Login without TFA?

![Screenshot 2022-10-20 101908](https://user-images.githubusercontent.com/84832617/196895591-ed7d672b-0c3f-4cf9-bbac-c0edcdcabd59.jpg)

Whats the name of the configuration file, I can fill in with this informations (without TFA Informations)?
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password

best

**Comment by twrecked** [comment]
I recommend installing from HACS at the moment, the trunk code isn't quite ready for prime time, with the HACS install configure it with the file.

Having said that, if you don't have two factor authentication set up on you Home Assistant Arlo account you can safely enter anything into those fields and they will be ignored. (I don't know if you can leave them blank, I always have to fill them in.)

But if you do have TFA enabled you will need to enter the username/password/host of the IMAP account you get the code sent to.

**Comment by feron81** [comment]
Hi twrecked

Thank you very much for your answer. My problem is, I use Home Assistant on Synology Docker. Here I'm not able to install HACS. Is it not possible to configure it with the file without HACS?

I tried now everything without TFA settings etc. I'm not able to connect.

Best
feron

**Comment by feron81** [comment]
That would be great, when the version use the configuration.yaml and I can use the same HACS Version on docker. But I don't understand what I have to send you? How can I clone the repository?

**Comment by twrecked** [comment]
How did you get the original code?

**Comment by feron81** [comment]
Hi Steve

 

I opened «Code» than copied the HTTPS URL and copied it go Git-Bash and started the Git-Bash. After that I uploaded the files to my synology docker custom_components folder:



 

Best

feron

 

Von: Steve Herrell ***@***.***> 
Gesendet: Donnerstag, 20. Oktober 2022 18:11
An: twrecked/hass-aarlo ***@***.***>
Cc: feron81 ***@***.***>; Author ***@***.***>
Betreff: Re: [twrecked/hass-aarlo] Arlo HA Credentials (Issue #641)

 

How did you get the original code?

**Comment by feron81** [comment]
For me its also the first time I use Git Bash. You wrote about clone directoy. That was the reason, why I downloaded Git-Bash. I can't see something about version-0.7.x.

I have a changelog file there:
aarlo = 0.8.0a9 last entry
aarlo/pyaarlo = 0.7.1 last entry

**Comment by twrecked** [comment]
You need to checkout the version-0.7.x, did you try the `git checkout` command in the previous comment?

**Comment by feron81** [comment]
I tried this command. I get following message:
fatal: not a git repository (or any of the parent directories): .git

**Comment by feron81** [comment]
I think it could be the right version now. I uploaded the files to my Synology Docker. Then I added my username and passwort on the configuration.yaml and started the Home Assistant new. It tooks a long time to connect "waiting on arlo". But when I open "Camera" I can't see a view. Where can I check now, if I uploaded it correct?

**Comment by twrecked** [comment]
It's getting there!

One thing to try now would be to logon to the [Arlo camera website](https://my.arlo.com/#/login) with your Home Assistant login and see what is happening. For the Home Assistant integration to work you need to either login straight in or to get sent an email with a code in it. Does one of those two things happen?

If that doesn't help we can turn on some extra debug. Read [this section](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs) for turning on extra debug. This debug will contain some sensitive data - camera serial numbers and the like - so you can use [this page](https://pyaarlo-tfa.appspot.com/) to encrypt it so only I can see it.

But by reading the debug, look for lines with `pyaarlo` in them it might be pretty obvious what is going wrong.

**Comment by feron81** [comment]
Now I could connect my camera with the Home Assistant account. Is it possible to see the live view of the cam directly on the home assistant web page. And is it also possible to make a flow on Home Assistant, so that my camera will cast to my google nest hub every 30 minute? How does it work?

**Comment by feron81** [comment]
Thank you very much for your help. Stream on a lovelance glance would be good for me. Nest hub is secondary. Here I have the same problem that I don‘t have the HACS Store while running on Docker. Where can I install the lovelance glance manually? Do I need to copy the code to my configuration.yaml?Am 21.10.2022 um 03:30 schrieb Steve Herrell ***@***.***>:﻿
I don't know how to stream a live view to a nest hub, I just show everything on a lovelace glance card on the standard GUI. You might have more luck with that one on the Home Assistant community website.

**Comment by twrecked** [comment]
I'm not understanding why you can't install HACS on your device, I run a docker image and I've done it, it really would make things easier. If you can install my pieces you can install HACS - [see here](https://hacs.xyz/docs/setup/download/).

This is the location [of the lovelace card](https://github.com/twrecked/lovelace-hass-aarlo), the installation is slightly different, see the README for details.

**Comment by feron81** [comment]
I rode on several blocks that its not possible to install HACS on docker, that it needs a OS version. How did you install HACS on docker? That would really be much better for me. Do I need the Container/Container version? Where I have to open a terminal (Home Assistant, Client)? And where I have to run the HACS download script?

**Comment by feron81** [comment]
I opened my Synology File station and copied the files from my local C to my Synology custom_components folder.

**Comment by twrecked** [comment]
You can do the same with HACS - the source is [here](https://github.com/hacs/integration), and the exact piece you need is [here](https://github.com/hacs/integration/tree/main/custom_components).

But if you ssh onto your Home Assistance install then you can run the instruction on [here](https://hacs.xyz/docs/setup/download)

**Comment by feron81** [comment]
You mean I have to copy the exact piece "hacs" to the same folder than aarlo (custom_components\hacs)? Thats all what I have to do? Then I don't need ssh?

**Comment by twrecked** [comment]
I believe so.

**Comment by twrecked** [comment]
It's not under integrations?

**Comment by twrecked** [comment]
No idea, it's not my integration. Did you check out the HACS install instructions?

**Comment by feron81** [comment]
Thank you for your help. I will have a look at the install instructions. I hope I can install HACS on docker and then I will download arlo lovelance. Maybe I have then question about lovelance.

**Comment by twrecked** [comment]
Good luck. And once HACS is on there is a load more stuff you can install with a single click, it really makes things easier.

**Comment by feron81** [comment]
Hi twrecked, I have HACS now running on my Docker installation. I downloaded an older version. With this one it works. Now I installed the lovelace files from HACS. No the files are installed. 

Now I tried the following readme. I don't understand point 9. Where can I find the lovlace Dashboard?
https://github.com/twrecked/lovelace-hass-aarlo/blob/master/hacsinstall.md

**Comment by twrecked** [comment]
I feel like is very out of date, sorry, and it's safe to ignore that config on there as well.

The card is probably already installed. it will be under `www/community` on your docker device. `www` is at the same level as `custom_components`.

And [this is a good example](https://github.com/twrecked/lovelace-hass-aarlo#a-single-camera-card) configuration to start with.

**Comment by feron81** [comment]
Yes, I can see 2 files under www/community/lovelace-ass-aarl:
hass-aarlo.js.gz
hass-aarlo.js

In which file, do I have to copy your example configuration?

**Comment by twrecked** [comment]
It's all done from the GUI from now on. Click the triple dots on the top right, then choose `edit dashboard` followed by `add card` at the bottom right. The choose `Manual` at the bottom of the list.

**Comment by feron81** [comment]
Ok, now I can see Card Configuration. Does I copy the code from your link here an Save?

**Comment by feron81** [comment]
I refreshed the browser with CTRL + Shift + R and restarted HA. Still the same error:
Custom element doesn't exist: Aarlo-glance.

Do you have another idea?

**Comment by twrecked** [comment]
Lovelace cards are all done from HACS, you don't need any configuration changes.

Maybe try the mini-graph card through HACS, see if that installs and works. The [GitHub page](https://github.com/kalkih/mini-graph-card) is here if that helps.

Can you paste your Lovelace configuration here so I can double check it?

**Comment by feron81** [comment]
I installed now the mini-graph cards from HACS. I still have the same error after refreshing browser and HA restart.
Cutom elemt doesn't exist: Aarlo-glance

I installed now aarlo from HACS. This folder I can see under "config/custom_components/aarlo". Then I installed the "Frontend Lovelace Hass Aarlo" and "mini-graph" also from HACS. This folder are under "config/www/community/lovelace-ass-aarlo" and "config/www/community/mini-graph-card". This are the folders I can see after HACS insallation of the 3 package. Which configuration I should paste here? I can't see a lovelace configuration file.

**Comment by twrecked** [comment]
Did you try to set up a mini-graph card?

And the configuration you tried for the Aarlo Lovelace card?

**Comment by feron81** [comment]
You mean "Add Card" "Mini Graph Card"? Here I get this error:
No visual editor available for type "custom:mini-graph-card".

**Comment by twrecked** [comment]
Can you type anything above that message?

**Comment by feron81** [comment]
I click on the 3 dots. Than I'm "Add card". Then I take "Mini Graph Card". 

Then It looks like that. I'm able to add something there.
1) type: custom:mini-graph-card

Please provide the "entities" option as a list. See https://github.com/kalkih/mini-graph-card/blob/master/README.md
type: custom:mini-graph-card

**Comment by twrecked** [comment]
And did you enter any entities?

**Comment by feron81** [comment]
Yes, I tried also with the entity of my Arlo Camera and get this:
 
Konfigurationsfehler erkannt:
bad indentation of a mapping entry (2:8)

 1 | type: custom:mini-graph-card
 2 |  entity: camera.aarlo
------------^

**Comment by twrecked** [comment]
It's yaml, you need to enter a list. Did you look at the [examples here](https://github.com/kalkih/mini-graph-card#example-usage).

```yaml
type: custom:mini-graph-card
entities:
 - camera.aarlo_back_camera
```

Change that camera entity to one that matches yours.

**Comment by feron81** [comment]
I changed it to your example with my entity. I don't get an error with this. Only a message:
No visual editor available for type "custom:mini-graph-card" and no camera picture only a Text "NaN".

**Comment by twrecked** [comment]
But you see a card? So that's working.

The `NaN` means Not A Number because mini graph expects a number to put on a graph.

Now try: `ADD CARD --> By Card --> Manual` then paste the following in and then change the `entity:` to a camera name you have.

```yaml
type: custom:aarlo-glance
entity: camera.aarlo_front_camera
```

**Comment by feron81** [comment]
With this command you send me, I don't get an error and I can see a picture of the camera a few hours ago. When I click on the play symbol nothing happen. Is it possible to add live streaming, when I click on play?

**Comment by twrecked** [comment]
Excellent,. The card is working.

The configuration options for the card are [here](https://github.com/twrecked/lovelace-hass-aarlo#configuration), I encourage you to read the documents and try out various settings.

This is a modified version of the example [here](https://github.com/twrecked/lovelace-hass-aarlo#a-single-camera-card), this configuration will put a "triangle" button on the bottom that will start a live stream. Clicking the image will show you the recordings in the library.

```yaml
type: 'custom:aarlo-glance'
entity: camera.aarlo_front_door_camera
name: front door
image_view: direct
image_top: 'name,status'
image_bottom: 'motion,library,stream,snapshot,battery'
image_click: 'recordings'
library_sizes: '3,4,2'
```

**Comment by feron81** [comment]
Your code works, so that I can click on the play symbol to start live stream. Do you know that, when I click on snapshot, where will the snapshot be saved?

**Comment by feron81** [comment]
On Home Assistant left site navigation there is a point "Media".  When I click on camera I can see my camera. When I click there on the Play symbol the streaming not working. Is it also possible on this point that the live streaming works?

**Comment by twrecked** [comment]
The snapshot will be saved in the Arlo cloud but you can view it from the library.

The code I sent you ends up in the GUI, you can see it from `Edit Dashbooard --> Raw Configuration Editor`.

I have no idea what the media button is sorry, does it come as default? And chances are it won't work because Home Assistant expects an RTSP stream and Arlo doesn't provide that. You need to use the Aarlo Lovelace card.

**Comment by feron81** [comment]
I meant, that the code is in a yaml file. But I can see the code now in Raw Configuration Editor. Thats great. Set up with yaml is not possible?

Regardind the snapshot, could it be possible to make a flow in HA, when a snapshot created, send me the snapshot by mail or somethng like that?

I mean the media button on the left site (under HACS). In my installation it was default. When I click on media, camera I can see a picture of my cam (but live streaming is not possible).

**Comment by twrecked** [comment]
Possibly. Look for `auto_play` on the Lovelace page.

Not that I'm aware of, you can check with the Home Assistant people to see if `yaml` editing is possible.

You can probably email a snapshot, I've never tried, check under `Developer Tools --> SERVICES`, there are a bunch of services you can use in automations.

I got rid of all the default GUI stuff, but I suspect it's using the wrong type of card for the camera. You used to be able to use the old card but Arlo changed their back end and broke it all.

**Comment by feron81** [comment]
Thank you, that works with auto_play. Great

Under Developer Tools / Services I'm able to make such a service. But I don't know where test.jpg will be stored. I can't find it.

service: aarlo.camera_request_snapshot_to_file
data:
  entity_id: camera.aarlo
  filename: test.jpg

**Comment by twrecked** [comment]
You'll need to white list a directory to allow the file to be downloaded. You need to configure

https://www.home-assistant.io/docs/configuration/basic/
https://www.home-assistant.io/docs/configuration/basic/#allowlist_external_dirs

And then you specify the full path.

**Comment by feron81** [comment]
Now, I have the next problem. I would like to install Tailscale. Regarding the web instructions, I have to download it from Supervisor sidebar. My problem is, I don't have Supervisor in my Docker installation. Do you use Supervisor in your Docker installation?

**Comment by twrecked** [comment]
Sorry, but I'm no familiar with either of those things. A good place to check would be [the community web site](https://community.home-assistant.io/), somebody will have tried to do what you are doing.

**Comment by feron81** [comment]
The Arlo camera works great on my Home Assistant. I saw that the Arlo Camera makes an automatically Snapshot on a https site, when the camera is playing. Do you know, if its possible to make flow, that the camera automatically start maybe at 15:00, that I get an actually snapshot?

**Comment by twrecked** [comment]
Just to clarify: you want to take a snapshot every time the camera start recording?

**Comment by feron81** [comment]
No, I only want to know if its possible to play the camera automatically at a time over Home Assistant. At the moment I have to open Home Assistant and the camera starts automatically. That's great. The camera makes a snapshot automatically to a https location. Now my question, if its possible that Home assistant starts the camera automatically for a few seconds to get a new snapshot, without opening the home assistant app. I don't have motion detection active.

**Comment by feron81** [comment]
I don‘t have the service camera_start_activity in Home Assistant. I only have the service camera_stop_activity. That would be so great, if I can say start playing at 15:00 in Home Assistant to get a actual snapshot.

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#advanced-services

**Comment by feron81** [comment]
Thanks. And which service is the right one to start automatically streaming in Home Assistant?

**Comment by feron81** [comment]
I found an option play_stream. That works :-). But the problem it would be great to stop_stream after 5 minutes. I have a camera with battery pack, when every stream runs more than 10 minutes, my camera battery pack is down in a few weeks. Do you know if stop_stream is possible?

Camera_request snapshot also works great, but it's only works when the camera is streaming. Is there a possibility to wake up the cam to only make a short snapshot?

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#services

Look for `stop_activity`.

**Comment by feron81** [comment]
That works, great. In your service list I saw also a service called "stream_snapshot". That could be my solution to start a short stream and take a snapshot. But I don't have this service "stream_snapshot" and "stream_snapshot_stop" to choose in my home assistant installation. Do you know why?

**Comment by feron81** [comment]
Now everything works great, but with snapshot I have still problems. I play the stream with Home Assistant at 12:00 and then I take a snapshot at 12:05 (kamera take snapshot). The stream works and its also generating a file at 12:05, but not everytime I have a new file. I think the snapshot not working everytime. Do you have another suggestion to make snapshots?

**Comment by feron81** [comment]
Hi twrecked, for your information, it works now for me also with snapshots. Is it also possible to change the settings, so that not a stream start directly on the dashboard, I only want a actual snapshot when I open the app. Is that also possible to add it? My Dashboard code looks like this:

type: custom:aarlo-glance
entity: camera.aarlo
name: Test
image_view: direct
image_top: name,status
image_bottom: stream
image_click: direct
library_sizes: 3,4,2

**Comment by feron81** [comment]
Not everytime my Home Assistant makes a Snapshot, I can see it on my Dashboard. After a restart of my Home Assistant Installation it works. Do you have an idea, what could be the problem?

**Comment by feron81** [comment]
I updated today to the newest Beta version. With this my snapshots to file not working anymore. Now, I downloaded the older master version and everything is working correctly. Do you know about this problem?

**Comment by feron81** [comment]
Hi Twrecked

Today, I updated to the Home Assistant Core Version 2023.5.3. Now, I get following error and no snapshot will be created since  the update. Do you have an idea why?

![Screenshot 2023-05-15 091642](https://github.com/twrecked/hass-aarlo/assets/84832617/f3ae6463-1586-4c2d-9044-41073c67239b)

Thank you for your help.

Best
feron81
