### ISSUE TITLE
Odd battery level readings with Arlo Pro 2 cameras

### ISSUE THREAD

**Issue by thijsputman** [twrecked/hass-aarlo#642]
My two Arlo Pro 2 cameras have been reporting odd battery level readings for a while now:

![image](https://user-images.githubusercontent.com/4418373/196995616-0e7e5c83-f9a4-4a84-9e69-ffcfb4424cf0.png)
![image](https://user-images.githubusercontent.com/4418373/196995720-14e21959-2606-4e2e-88c7-8b6245816f88.png)

The "base" readings are correct (or at least, they match up with those in the Arlo app). Approximately every two hours an errant reading is reported (always to the same value, but different for each camera). Apart from these odd readings everything else works just fine with these two cameras.

An Arlo Essential Spotlight camera attached to the same setup does not suffer from the issue.

Guestimating from the historical data, I'd say the issue started somewhere at the beginning of September. It appears unrelated to an update of / change of configuration for `hass-aarlo`. I've been on the latest version all the the time (just upgraded to `0.7.2.beta.10` — the issue is present there).

**Comment by twrecked** [comment]
Can you upload some logs. Around the point things go wrong.

See [here for turning on logs](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs) and [here for encrypting them](https://github.com/twrecked/hass-aarlo#hiding-sensitive-data).

**Comment by thijsputman** [comment]
> just upgraded to 0.7.2.beta.10 — the issue is present there

It seems I spoke too soon. 

Roughly a day after upgrading to `0.7.2.beta.10` (and removing the `backend` setting from my configuration) the odd behaviour stopped; it's been working properly ever since...

I guess/assume it was thus related to the back-end?
