### ISSUE TITLE
2fa finishAuth failed

### ISSUE THREAD

**Issue by crosenkr** [twrecked/hass-aarlo#643]
After the last update, mt 2FA seems to be broken. I am using IMAP and before bumping, it worked flawlessly. The OTP is sent to my IMAP account, but for whatever reason the remote access does not seem to work anymore.

Logger: pyaarlo
Source: custom_components/aarlo/__init__.py:300 
Integration: aarlo (documentation, issues) 
First occurred: 09:48:36 (6 occurrences) 
Last logged: 09:49:33

error in new response={'meta': {'code': 400, 'error': 9236, 'message': 'Invalid OTP'}}
2fa finishAuth failed

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:355 
Integration: aarlo (documentation, issues) 
First occurred: 09:48:36 (5 occurrences) 
Last logged: 09:52:43

unable to connect to Arlo: attempt=1,sleep=15,error=2fa finishAuth failed
unable to connect to Arlo: attempt=2,sleep=30,error=2fa finishAuth failed
unable to connect to Arlo: attempt=3,sleep=60,error=2fa finishAuth failed
unable to connect to Arlo: attempt=4,sleep=120,error=2fa finishAuth failed
unable to connect to Arlo: attempt=5,sleep=240,error=2fa finishAuth failed

**Comment by lukone** [comment]
Same error here

2022-10-21 09:04:24.169 ERROR (SyncWorker_1) [pyaarlo] 2fa finishAuth failed
2022-10-21 09:04:24.177 ERROR (SyncWorker_1) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=2fa finishAuth failed

**Comment by twrecked** [comment]
Thanks. I'll take a look.

**Comment by lukone** [comment]
I brought it back to v0.7.2b7 and now it works.

**Comment by twrecked** [comment]
Which provider do you use for email?

**Comment by lukone** [comment]
Micso.net a provider without 2fa authentication.

Il Ven 21 Ott 2022, 18:02 Steve Herrell ***@***.***> ha
scritto:

**Comment by twrecked** [comment]
Thanks. I changed the email checking code to move to read-only and to specifically read the INBOX, I wonder if that broke it.

Unfortunately I needed a debug from a broken install to check. I'll do some digging.

**Comment by twrecked** [comment]
Can you try the latest build, it fixes the most likely issue.

And can you turn on debug in case it doesn't? Thanks.

**Comment by lukone** [comment]
It's working now.

thank you

Il giorno ven 21 ott 2022 alle ore 23:42 Steve Herrell <
***@***.***> ha scritto:

**Comment by crosenkr** [comment]
Sorry for running late, I guess debugging not needed because I can confirm it's working again? Thank you! Who was the culprit?

**Comment by twrecked** [comment]
I was scanning everything in the email not just the `text/html` section and the code match was picking up an incorrect code.
