### ISSUE TITLE
Platform aarlo does not generate unique IDs. Doorbell Binary Sensor issue

### ISSUE THREAD

**Issue by alsoszaa** [twrecked/hass-aarlo#644]
Not sure why I get this:
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:520
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 4:52:13 PM (1 occurrences)
Last logged: 4:52:13 PM

Platform aarlo does not generate unique IDs. ID connected_front_doorbell already exists - ignoring binary_sensor.aarlo_connected_front_doorbell

I do have an Arlo Front Doorbell 
Here is what I have in binary sensor for aarlo in config.yaml:
binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - ding
      - connectivity

**Comment by twrecked** [comment]
Looks like a repeat of this: https://github.com/twrecked/hass-aarlo/issues/446

Can you send me the doorbell model number,  It will be in `Developer Tools > STATES > camera.aarlo_front_doorbell`

Thanks!

**Comment by alsoszaa** [comment]
AVD1001B

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by twrecked** [comment]
Thanks. I'll add it into the code and hopefully it will fix the issue.

**Comment by twrecked** [comment]
I don't think it is that issue, we already handle that model number. 

How is the doorbell connected to Arlo - via a base station or not?

**Comment by alsoszaa** [comment]
Yes. Base station. I have the VMB5000r5 base station.
I have the latest update from your Arlo integration.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by karolizz777** [comment]
Hi, I am also getting a similar error for both of my Arlo doorbels.

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:520
Integration: Binary Sensor (documentation, issues)
First occurred: 21:03:34 (2 occurrences)
Last logged: 21:03:34

Platform aarlo does not generate unique IDs. ID connected_backdoor already exists - ignoring binary_sensor.aarlo_connected_backdoor
Platform aarlo does not generate unique IDs. ID connected_front_door already exists - ignoring binary_sensor.aarlo_connected_front_door

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:520
Integration: Switch (documentation, issues)
First occurred: 21:03:39 (2 occurrences)
Last logged: 21:03:39

Platform aarlo does not generate unique IDs. ID siren_backdoor already exists - ignoring switch.aarlo_siren_backdoor
Platform aarlo does not generate unique IDs. ID siren_front_door already exists - ignoring switch.aarlo_siren_front_door 


This error originated from a custom integration.

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:679
Integration: Arlo Camera Support (documentation, issues)
First occurred: 21:22:33 (1 occurrences)
Last logged: 21:22:33

request-error=ReadTimeout

**Comment by twrecked** [comment]
I just realised my logic is a bit broken,  for video doorbells attached to a base station we'll create the connectivity option twice.

Same with the siren I think.

I'll give it some thought on how best to tidy it up.
