### ISSUE TITLE
No 'last_video' attribute for Arlo Baby camera

### ISSUE THREAD

**Issue by allenrong88** [twrecked/hass-aarlo#651]
Running the latest HA and also aarlo plugins for a while now, tried implementing some automation by using the last_video attribute and realized that there is no 'last_video' available at all for the Arlo Baby, but there is one for the Arlo Pro 2 cameras, which I am using as well.

Am I missing some configurations to prevent it appearing for the baby camera?

Many thanks.

**Comment by twrecked** [comment]
Do you mean there is no entity created or the value in it blank? We should create an entity of the Arlo Baby, we do it for all cameras.

**Comment by allenrong88** [comment]
No, the camera entity gets created fine with lots of attributes, such as last_thumbnail, access_token, etc showing the correct value. The issue I am experiencing is that the 'last_video' attribute is completely missing, it is not shown at all, not even a blank value.

**Comment by twrecked** [comment]
It should all be coming through the same mechanisms. We need to look at the debug and see what information is coming back from Arlo. Can you tun on debug and restart. 

See [here](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs) for enable debug logs, you will also need to add `verbose_debug: True` to the Arlo config.

And what we're looking for is the video list coming back from Arlo. It will look a little like this, the keyword `contentType` is a good one to look for.

```
2022-10-25 16:28:04.929 DEBUG (ArloBackgroundWorker) [pyaarlo] request-body=
{'data': [{'contentType': 'video/mp4',
           'createdBy': 'XXXXXXXXXXXX',
           'createdDate': '20221025',
           'currentState': 'new',
           'deviceId': 'XXXXXXXXXXX',
           'donated': False,
           'lastModified': 1666709889379,
           'localCreatedDate': 1666709879521,
```

You need to then match the `deviceId` with the ID of the Arlo Baby device.  Do you see any?

**Comment by allenrong88** [comment]
Hi Steve,

Eventually figured out that it was caused by motion that had not been triggered for a while. All good now.

Thanks
