### ISSUE TITLE
Arlo issue: Subscription required?

### ISSUE THREAD

**Issue by Stupco** [twrecked/hass-aarlo#660]
Since updating my HA and Aarlo, the devices have stopped responding.

Trying to re-add the integration again, it seems there may be a soft lock on the Arlo side? Does anyone else experienced this?

Logging in successfully via the web portal, a page comes up to confirm subscription and you can't navigate further.
![Screenshot_20221106-091714](https://user-images.githubusercontent.com/64451616/200143501-26997512-9cea-45d8-96cd-427f8fd1c761.png)

Issue in my logs:
```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:293
Integration: Arlo Camera Support ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 5 November 2022 at 17:33:59 (8 occurrences)
Last logged: 07:36:59

No devices returned from /hmsweb/v2/users/devices?t=166765169xxxx
No devices returned from /hmsweb/v2/users/devices?t=166765895xxxx
No devices returned from /hmsweb/v2/users/devices?t=166766615xxxx
No devices returned from /hmsweb/v2/users/devices?t=166767341xxxx
No devices returned from /hmsweb/v2/users/devices?t=166768061xxxx
```

**Comment by twrecked** [comment]
Do you need to re-share your devices with your HA account?

I'm not aware of any soft lock that _Arlo_ uses.

**Comment by Stupco** [comment]
I have reshared the devices. I can login via app but cannot login via browser and it soft locks to the subscription page screenshot I shared. Can't go further, but also having issues with aarlo so not sure if related?

Website dashboard; https://my.arlo.com/account/v4/#/login

**Comment by Stupco** [comment]
Called up Arlo support who weren't very helpful, but I temporarily got around the softlock subscription page by going to "My Account > View Cameras" and logging in again. This time, the cameras flash up briefly and then I get pushed out with an error "You have been logged out because you are logged in from another device"

![image](https://user-images.githubusercontent.com/64451616/200232398-c7416b47-559b-4346-adeb-07b0bdf9ad65.png)

Now, I the error from my HA logs is gone and I can arm/disarm alarm, but all my cameras are gone:
![image](https://user-images.githubusercontent.com/64451616/200232649-c7de8438-2bde-45ce-aee1-b05bb353a3f1.png)


I still don't think this is an aarlo issue, but I do think that Arlo has made some changes/issues to their backend?

**Comment by twrecked** [comment]
The "you logged in from somewhere else" message is because you had _Home Assistant_ running at the same time, _Arlo_ is very strict about letting a user log in only once. You can end up with the web site and _Home Assistant_ battling it out if you're not careful.

Can you turn on more logging? See [here for how to turn on extra logging for Home Assistant](https://github.com/twrecked/hass-aarlo#debugging) and see [here for how to turn on verbose debug for Aarlo](https://github.com/twrecked/hass-aarlo#verbose-debug). And see [here for how to encrypt so only I can see it](https://github.com/twrecked/hass-aarlo#hiding-sensitive-data).


You will need to restart, maybe this will show us something.

**Comment by Stupco** [comment]
See attached, hope this helps! 
[PyAarloDump.txt](https://github.com/twrecked/hass-aarlo/files/9955852/PyAarloDump.txt)

**Comment by twrecked** [comment]
I'll look this week; I've been running in Windows for the past few days and the keys to decode are it are in the Linux boot.

**Comment by twrecked** [comment]
It's picking up the cameras in the logs I'm just not sure why they aren't being created. The sensors are being created fine, even the sensors based off the cameras. This looks like the motion from a camera `ArloBinarySensor: Motion Front Door created`.

Can you post your camera configuration.

**Comment by Stupco** [comment]
... I am an absolute muppet/idiot. I'm sorry for wasting your time!

I had commented out the camera component (accidentally) after Home Assistant was warning me about another camera deprecation. I did it on my phone so I didn't realise I took out Aarlo too.

Again, a thousand apologies and thanks so much for your help! :'(

**Comment by twrecked** [comment]
No worries. Glad it's working again!
