### ISSUE TITLE
Arlo floodlight dusk to dawn - luminosity sensor?

### ISSUE THREAD

**Issue by tapioturta** [twrecked/hass-aarlo#662]
I added an Arlo floodlight to my installation and as it seems there's a "dusk to dawn" optionality on the camera itself (you're able to determine the sensitivity on the Arlo app) I'm wondering if there's some sort of luminosity sensor in the camera which could be used as a sensor value on the home assistant? Does anyone have any idea (or knowledge)on this? I don't have skills or understanding where and how this could be checked... Appreciate your insights on this!

**Comment by twrecked** [comment]
They do expose the value I just never found it to be correct on my lights - I was hoping it was so I could time automations on light levels. 

I'm not on my development machine at the moment but once I boot it up I'll post some instructions to try and see the values - it involves turning on debug - and we'll see if the spotlights return better values. If they do I can make a sensor to expose them properly.
