### ISSUE TITLE
Unknown issue.

### ISSUE THREAD

**Issue by fightinbeavs** [twrecked/hass-aarlo#664]
2022-11-15 19:46:49.097 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aarlo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-15 19:46:57.990 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.aarlo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
cache[self.domain] = importlib.import_module(self.pkg_path)
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/aarlo/__init__.py", line 29, in <module>
from .pyaarlo.constant import DEFAULT_AUTH_HOST, DEFAULT_HOST, SIREN_STATE_KEY
File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 12, in <module>
from .camera import ArloCamera
File "/config/custom_components/aarlo/pyaarlo/camera.py", line 1395
camera:
^
SyntaxError: invalid syntax

Any suggestions?

**Comment by twrecked** [comment]
There is no line 1395 in `camera.py`.

Which version is this? And how did you install this?

**Comment by fightinbeavs** [comment]
I installed it all from the HACS Arlo. that was part of my confusion too. I looked at the Camera.py and only goes to 1162

**Comment by twrecked** [comment]
Interesting. There are actually 2 `camera.py` files. The one failing is under `pyaarlo`. 

It almost looks like some configuration was written in the file by mistake, I'd expect `camera:` to appear in a configuration file. Take a look at `custom_components/aarlo/pyaarlo/camera.py`

**Comment by fightinbeavs** [comment]
I think we made progress. the only error I am getting is: Error: 2fa startup failed
If error persists you might need to change config and restart. 
 what is the code that is put in for that, and where do I put it? thanks!

**Comment by fightinbeavs** [comment]
I saw your coding for it, I guess not sure where in Home assistant I plug that in. does that go in configuration.yaml or elsewhere?

**Comment by fightinbeavs** [comment]
awesome. thank you much!

**Comment by twrecked** [comment]
If you use google you will need to use a 3rd part password.

**Comment by fightinbeavs** [comment]
I do not have an aarlo config. I have the main config.yaml but nowhere else.

**Comment by twrecked** [comment]
You need one. It's a section in `configuration.yaml` (or whatever your main configuration is).

See here https://github.com/twrecked/hass-aarlo/tree/version-0.7.x#main-configuration

**Comment by fightinbeavs** [comment]
![Screenshot 2022-11-16 104315](https://user-images.githubusercontent.com/115807084/202266130-75634f58-d95d-4f16-bedc-382655e48d79.jpg)
Invalid config for [aarlo]: required key not provided @ data['aarlo']['password']. Got None
required key not provided @ data['aarlo']['username']. Got None. (See /config/configuration.yaml, line 25).

**Comment by fightinbeavs** [comment]
that is what I have, with the errors its giving me

**Comment by twrecked** [comment]
You have 2 `aarlo` entries, join them together.

**Comment by fightinbeavs** [comment]
got it. if you were unsure, I am kind of a newbie at all this, so thank you for your help and patience.

**Comment by twrecked** [comment]
No worries. Glad you're getting it working!

**Comment by fightinbeavs** [comment]
![Screenshot 2022-11-16 110320](https://user-images.githubusercontent.com/115807084/202270138-868f1ae4-18c9-4d3c-915b-f7f26db1955f.jpg)
this is what it is showing for my dashboard card.

**Comment by twrecked** [comment]
Is the camera name correct? It will look like this `camera.aarlo_back_camera`, you can find a list of them in `Developer Tools --> STATES`.

**Comment by fightinbeavs** [comment]
thats what I was just thinking because I dont have it listed as a camera within Media. it shows one incompatible item hidden, which I am guessing is the arlo camera. but I guess I am not sure how to configure the camera outside of having all the code within camera.py

**Comment by fightinbeavs** [comment]
I have tried to look at the documentation it but since they removed the integration, its hard to find what to do

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#readme

https://github.com/twrecked/hass-aarlo#camera-configuration

Put this in you configuration file.

(Go real work to do at the moment... I'll answer more later.)

**Comment by fightinbeavs** [comment]
sounds good. I have made progress, they are showing up on the dashboard and with media, but not sure how to make it show live feed...

**Comment by fightinbeavs** [comment]
when something happens in it, it says "recently active" which I assume is the sensor going off for activity. but when I click on it, it doesnt show me anything or live feed. do I need to change the feed to auto from live. as I have them on live now.
