### ISSUE TITLE
2 camera won't start streaming

### ISSUE THREAD

**Issue by platini76** [twrecked/hass-aarlo#665]
hello I have two problems.
4 arlo ultra, 2 of them wont' start streaming... same card...
and all light switch wont work... any suggestions?
thanks

**Comment by twrecked** [comment]
Can you:

- tell me what you are streaming on - Windows, Linux, Mac - and what browser you are using
- tell me what versions of Aarlo and the Aarlo Lovelace you are using
- paste an example of the Lovelace configuration

Thanks.

**Comment by platini76** [comment]
my server is a raspberry pi 400
I am streaming on mac with chrome
lovelace arlo 0.2.0b5
arlo 0.7.2b13
type: custom:aarlo-glance
entity: camera.aarlo_arlo_soggiorno
name: Arlo Soggiorno
light: light.aarlo_arlo_soggiorno
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - signal_strength
  - captured_today
  - image_date
top_title: true
top_status: true
top_date: true
image_click: stream


sometimes I see video, sometimes not... snapshop won't update... some problems..


thanks for help
