### ISSUE TITLE
No devices returned, but login was successful?

### ISSUE THREAD

**Issue by Skaani** [twrecked/hass-aarlo#672]
Hi,
I hope you guys can help. I have been struggling with this issue for close to a week now. I cannot get any devices or entities from Arlo.

- The tfa login works and my secondary HA user for Arlo is logged in.
- I have tried to check, uncheck and recheck all cameras and access rights to the secondary HA user. It does not help
- I have tried to uninstall and redownload aarlo integration and front-end to see if that helped

The log I get:
 
WARNING (SyncWorker_5) [pyaarlo] No devices returned from /hmsweb/v2/users/devices?t=1670414376970
DEBUG (SyncWorker_5) [pyaarlo] devices=[]
DEBUG (SyncWorker_5) [pyaarlo] set:ARLO/totalCameras=0
DEBUG (SyncWorker_5) [pyaarlo] set:ARLO/totalDoorBells=0
DEBUG (SyncWorker_5) [pyaarlo] set:ARLO/totalLights=0
DEBUG (SyncWorker_5) [pyaarlo] auto chose SSE backend
DEBUG (ArloEventStream) [pyaarlo] re-logging in
DEBUG (ArloEventStream) [pyaarlo] starting stream with no timeout
DEBUG (SyncWorker_5) [pyaarlo] waiting for stream up
DEBUG (SyncWorker_5) [pyaarlo] stream up
DEBUG (SyncWorker_5) [pyaarlo] queueing initial settings
DEBUG (SyncWorker_5) [pyaarlo] registering cron jobs
DEBUG (SyncWorker_5) [custom_components.aarlo] login succeeded, attempt=1

My Arlo config is the following in the yaml config:

# AARLO setup
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_user
  password: !secret arlo_pass
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2
  verbose_debug: True
  tfa_source: email
  tfa_type: email
  tfa_host: 'imap.gmail.com:993'
  tfa_username: !secret gmail_user
  tfa_password: !secret gmail_app_password
camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2' 
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity
light:
  - platform: aarlo
switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10

**Comment by twrecked** [comment]
If you use the HA username and password on the [Arlo web](https://my.arlo.com/#/home) site what do you see?

**Comment by Skaani** [comment]
i see all the cameras that i setup. if I change access rights to the secondary (Home assistant) user, e.g. remove a camera, it reflected on the my.arlo.com webpage. too.

**Comment by Skaani** [comment]
a little further investigation (i used ChatGPT to debug) it seems like its not logged in correctly. i cannot get the integration to login either with TFA or without. i have triple checked the login details and they work just fine on my computer and tablet. i wonder what simple issue I am missing

**Comment by twrecked** [comment]
One thing to try, from where your config is:

```sh
rm .aarlo/session.pickle
```

The restart your Home Assistant, it would force another log in attempt.

**Comment by Skaani** [comment]
> One thing to try, from where your config is:
> 
> ```shell
> rm .aarlo/session.pickle
> ```
> 
> The restart your Home Assistant, it would force another log in attempt.

i am not sure I follow what exactly you want me to do and where.

**Comment by twrecked** [comment]
Look in the directory where your `configuration.yaml` file is. There is a subdirectory called `.aarlo`. Delete the file `session.pickle` in there.
