### ISSUE TITLE
Aarlo connecting with previous login credentials?

### ISSUE THREAD

**Issue by chicknlil** [twrecked/hass-aarlo#673]
I am using the HACS version of this integration, and Home Assistant 2022.12.1.

When I originally installed this integration, I set it up with my main Arlo account, before I read/saw that wasn't smart, since Arlo logs you out if you're logged into the account in more than one place. I created a secondary account, but it took about a week before Arlo support corrected an error on their end that prevented the camera from properly sharing. It's only been in the last 2 days that I've re-enabled your integration, with the new login credentials in my `secrets.yaml`, and everything was working great until about 30 minutes ago.

One of my Aarlo automations alerted me that the camera detected motion.  Cool - but my phone/watch didn't do the same? I check on the phone and I'm logged out of my primary account. Try to login, and it immediately logs me out again.  Try this from both the app and the website, no joy.  In frustration, I try using the account that HA has access to - and I'm able to login and stay logged in, which leads me to believe that for some reason, Aarlo is connecting with the previous credentials.

The only credentials in `secrets.yaml` are the new ones. I use the 2FA that requires my phone to authenticate on first login.

Are the login credentials saved/accessed from elsewhere? I'll have no choice but to disable the integration if it's going to otherwise lock me out of the phone app despite intentionally giving it access to a secondary account.

**Comment by twrecked** [comment]
I'm out and about so I'll reply more later but look for authentication caching on the README.

Or try deleting `.aarlo/session.pickle` from the same directory as your configuration

It should detect a login change and handle it correctly but there might be a bug there.

**Comment by chicknlil** [comment]
Deleting the `session.pickle` did the trick. Thank you! Marking this closed.

**Comment by twrecked** [comment]
Glad it's working, it really should have picked up the email change. I'll take a look when I have the time.

**Comment by chicknlil** [comment]
Do you have a KoFi or something similar that I can buy you a cuppa?
