### ISSUE TITLE
After login, I only get one update...

### ISSUE THREAD

**Issue by DominikReber** [twrecked/hass-aarlo#675]
Hi

I have seemed to have set aarlo correctly up, it is logging in correctly using gmail as 2facter auth.
But I only get the first image/link after login/reboot of homeassistant.
Any further updates of arlo are not registered.

HASS is running in docker and I had to install HACS using command line (as the docker installation does not support addons) 
But it all seems to work ,except for the problem that it's only detected the first update of a camera. 

What can the reason for it be?

Anytime when I delete session.pickle and reboot home assistant, I get a new image/video, but that's it. 

Thanks

Dominik

**Comment by twrecked** [comment]
Can you paste in your _Aarlo_ config and we'll start there.

**Comment by DominikReber** [comment]
`# Aarlo
aarlo:
  backend: sse
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_host: 'imap.gmail.com'
  tfa_username: !secret tfa_username
  tfa_password: !secret tfa_password
  recent_time: 10
  db_ding_time: 10
  db_motion_time: 30
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 1
  reconnect_every: 90
  stream_timeout: 120
  backend: sse
  verbose_debug: True

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality

light:
   - platform: aarlo

switch:
   - platform: aarlo
     siren: True
     all_sirens: True
     snapshot: True
     doorbell_silence: True
     siren_volume: 1
     siren_duration: 10

media_player:
   - platform: aarlo
`

**Comment by DominikReber** [comment]
Somehow it is formatting the code...

**Comment by twrecked** [comment]
You need to use triple backticks to format the config.

The one thing to try would be to take out the `backend: sse` entry (entries) and try again. The code should be able to work out which backend to use.

If that doesn't help with the issue can you attach some debug. See [here](https://github.com/twrecked/hass-aarlo#component-logging) for turning it on and [here](https://github.com/twrecked/hass-aarlo#online) for encrypting it for uploading.
