### ISSUE TITLE
Arlo integration stoped working

### ISSUE THREAD

**Issue by bigbossteach** [twrecked/hass-aarlo#682]
After I have done the core update 
Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

I am getting the following error 
aarlo Component Setup
Error: 2fa startup failed
If error persists you might need to change config and restart.

  tfa_type: email
  tfa_host: 'imap.gmail.com'
  tfa_username:  !secret gamil_username  # email 2 step verfication  at secrets file
  tfa_password:  !secret gmail_password  # email password at secrets file

Can you help me on that

**Comment by twrecked** [comment]
Can you turn on some extra logging. See here:

https://github.com/twrecked/hass-aarlo#debugging

**Comment by bigbossteach** [comment]
The problem is solved by creating a gmail key to login to the mail and using it as my password in the configuration YMAL file
