### ISSUE TITLE
No Motion detection from Door bell camera

### ISSUE THREAD

**Issue by finnmadsen** [twrecked/hass-aarlo#684]
Hi, I've been using a number of cameras and one doorbell/camera in homeassistant for a while with great success. But recently the motion detection from the door bell stopped stooped working.

I activated the logging of packages from the Arlo stream and it seems like the motionDetected event is no longer included in the stream for the doorbell. 

MotionDetections is still working for my other PRO4 cameras and other events like the ButtonPressed is also still working for the doorbell. The doorbell is also generating motion alerts in the Arlo App as expected.

Homeassistant: 2023.1.2
  
[doorbell.log](https://github.com/twrecked/hass-aarlo/files/10420881/doorbell.log)
[doorbell-event.log](https://github.com/twrecked/hass-aarlo/files/10420935/doorbell-event.log)

**Comment by Fat-Knees** [comment]
I have this same issue with a wired Essential Doorbell
