### ISSUE TITLE
aarlo.camera start recording

### ISSUE THREAD

**Issue by samidcs2** [twrecked/hass-aarlo#685]
Hello,
i try this service

service: aarlo.camera_start_recording
data:
  entity_id: camera.aarlo_front_camera
  duration: 30

But where the file is saving ?

in then configuration.yaml,
il put this line on aarlo:
  save_media_to: "/config/www/cam_captures/cam_sonnette/videos/${SN}/${Y}/${m}/${d}/${T}"

But nothing in the folder.

I precise my cloud abonnement is terminated.

Thank you for your reponse

**Comment by twrecked** [comment]
Did you whitelist the directory? https://www.home-assistant.io/docs/configuration/basic/#allowlist_external_dirs
