### ISSUE TITLE
Arlo Security system isn't showing up in HA

### ISSUE THREAD

**Issue by xirtamoen** [twrecked/hass-aarlo#686]
I have Arlo integrated in home assistant and recently got the security system for Christmas.  It came with window/door sensors and a security hub with a keypad.  Has anyone figured out how to integrate this into Home assistant?

**Comment by twrecked** [comment]
Are we talking this device?

https://www.arlo.com/en-us/security-system/SS1201-100NAS.html

Because we don't (currently) support it. Does it appear when you log into the [web interface](https://my.arlo.com/#/home)?

**Comment by xirtamoen** [comment]
Yes, that is the device I am speaking of.   Is this something that will be supported soon?

**Comment by twrecked** [comment]
First question, have you enabled alarm support?


If you have then we need to add it, and 'when' depends on:
 - how good you are with Chrome or Python or
 - if you don't mind granting me access to the device for a day or two

I don't have the device and everything we support is reverse engineered. The easiest way to start might be to send me some debug, we don't support the device but _Arlo_ should be letting us know it's there.

Can you turn on debugging, the instructions are [here](https://github.com/twrecked/hass-aarlo#debugging). You will need to enable verbose debug as well - the instructions are [here](https://github.com/twrecked/hass-aarlo#verbose-debug). With those turned on restart you system.

There will be a lot of stuff written into `homeassistant.log`, you can copy out the important pieces, they start with `pyaarlo` or send me the whole thing. There are instructions [here](https://github.com/twrecked/hass-aarlo#hiding-sensitive-data) on how to encrypt it so only I can see it.

**Comment by xirtamoen** [comment]
I am not the greatest in Python but can grant you access to the device.  I did setup debugging and verbose debug but when I encrypt it the window isn't able to scroll to the very beginning.   Is there a way for me to output it to a file?  Thanks.

**Comment by twrecked** [comment]
When you say scroll to the beginning do you mean this website https://pyaarlo-tfa.appspot.com or do you mean the logs from _Home Assistant_.

If you want to share the devices I should only need half a day or so to get what I need. If you want (or can) share a window sensor, door sensor and the alarm that would be great. My email is steve.herrell@gmail.com

I'm on Eastern US time. So GMT -5 hours.

**Comment by xirtamoen** [comment]
I am referring to the logs from Home Assistant.

I have shared out the securtiy hub along with a sensor that came with the package. 

Thanks!

**Comment by twrecked** [comment]
I got the email but I the registration hung and the devices didn't appear. I'm sorry, can you send it again?

**Comment by xirtamoen** [comment]
I just sent another invite.  Let me know if this one goes through and you can see the devices.  Thanks!

**Comment by twrecked** [comment]
Do the devices appear on the Arlo web site: https://my.arlo.com/#/cameras

**Comment by twrecked** [comment]
This request went through but I can't see the devices in the web interface. I'm charging up a phone to check to see if they appear in the app.  It maybe I need to upgrade my account to the new v4 interface.

Also, can you make sure my invite was accepted at your end?

It's getting late here so I'll continue to look in the morning.

**Comment by xirtamoen** [comment]
It does show that you have accepted the invite.  You actually have to go to locations and choose the one that has my devices.  Arlo has made this a little difficult with the new app.

**Comment by twrecked** [comment]
It's almost working... I just got an update from the an open/close sensor. But the app is still showing the wrong interface and won't let me upgrade to access the locations stuff. 

I'm going to bring in some changes that @JeffSteinbok brought in and then I'll see about upgrading my main account, hopefully that will have a knock on effect.

**Comment by JeffSteinbok** [comment]
Sounds good.
Note that I've been running with my fork on my HA instance since I published it and it's working flawlessly.

Note you cannnot share devices across versions.

**Comment by xirtamoen** [comment]
Thanks for the update!  Let me know if you need anything further from me to assist.

**Comment by xirtamoen** [comment]
Hi do you have any further updates?  Do you still need access?  Thanks again!

**Comment by twrecked** [comment]
I've not had any luck getting the cameras to appear. You can remove access but I might ask for them again in a day or two.

Thanks to @JeffSteinbok I've just created a new release with v4 API support, can you download that and try. See if any pieces you're expecting appear, your locations should appear.

In the meantime, now v4 API is in I'm going to work on upgrading my _Arlo_ systems here. None of my test accounts have worked so far but I think it might be to with an old base station or being in Canada or both. I'll let you know when I succeed so you can share the devices again and then we should be able to get them working.

**Comment by JeffSteinbok** [comment]
Could very well be Canada.  I was testing this too when I was overseas this Christmas and an account I made there was v3.  When I VPNed via the USA, I got a v4 account.  It could be that the relevant products aren't sold in Canada yet?  If you want, I can create you a test account from here and send you the info, should trigger the v4 flow.

Also, again sharing from v4 to a v3 user doesn't work. Just won't show up.

**Comment by twrecked** [comment]
@xirtamoen What are you running Home Assistant on? Docker, rapsberry pi?

**Comment by xirtamoen** [comment]
@twrecked I am running home assistant on docker.

**Comment by twrecked** [comment]
We can get the logs encrypted another way. The following will get you inside the docker container and run a command. Change `YOUR_DOCKER_NAME` as necessary.

```sh
docker exec -it YOUR_DOCKER_NAME bash
cd /config/
cat home-assistant.log | curl -s -F 'plain_text_file=@-;filename=clear.txt' https://pyaarlo-tfa.appspot.com/encrypt > home-assistant.log.enc
exit
```

You should end up with a file called `homeassistant.log.enc` that starts something like this:

```html
<!DOCTYPE html>                                                                                                                                  
<html lang="en">                                                                                                                                 
<head>                                                                                                                                           
    <link rel="preconnect" href="https://fonts.googleapis.com">                                                                                  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>                                                                         
    <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Mono&display=swap" rel="stylesheet">                               
    <link rel="stylesheet" href="/static/styles.css">                                                                                            
    <meta charset="UTF-8">                                                                                                                       
    <title>Pyaarlo TFA Helper</title>                                                                                                            
</head>                                                                                                                                          

<body>
    <div style="margin-left: 5%; margin-right: 5%;">
         

<h2>Pyaarlo Output Encryption</h2>

Encrypted logs:

<pre class="language-enc"><code>-----BEGIN PYAARLO DUMP-----
gAN9cQAoWAEAAABrcQFCAAEAAG+0LxkuREMkh16LMa9ENklmhTsYRxpplOMcLd5YyQFssH30hCwa
grp9PQqLrzjhmX7a7uNv++muS83KOdWlWiS/9T3Hs8XFPtjS4O09RGxVsYlj5St0Elh+HnEaDy2L
```

Can you attach it to this bug report by dragging and dropping it into this conversation?

**Comment by xirtamoen** [comment]
[home-assistant.log.zip](https://github.com/twrecked/hass-aarlo/files/10524406/home-assistant.log.zip)

**Comment by xirtamoen** [comment]
Thanks again!

**Comment by twrecked** [comment]
Got it. Thanks. I'll take a look.

**Comment by xirtamoen** [comment]
@JeffSteinbok Are you running with just the cameras, or do you have the Arlo Security center and door/window sensors as well?

**Comment by JeffSteinbok** [comment]
Just cameras and a base station. All my cameras are paired to the single base.

**Comment by twrecked** [comment]
@xirtamoen I think you're the only one using the security center, certainly you're the only one using it with this component.

From you logs I can see the security device, it appears as a new device type `hub`. I think just adding that check to the code when creating base stations might be enough to get it working. I'll create a new release later.

I can't see the sensors though. Can you send me a debug log but this time arm the system and trip the sensors? I want to see if any messages come in.

@JeffSteinbok Can you create a test account for me? If we get that working then @xirtamoen would you be willing to share temporarily your devices to that account? Hopefully this will let us know what we can do with the new devices in this component.

**Comment by JeffSteinbok** [comment]
Sure. Give me an email address I can bind it to? Will need to verify it and all that jazz. You can do the “+” trick with a gmail account.

**Comment by xirtamoen** [comment]
[home-assistant.log (1).zip](https://github.com/twrecked/hass-aarlo/files/10530958/home-assistant.log.1.zip)
@twrecked I still have it shared to your gmail account.  Let me know if I need to reshare it to the account you provided earlier or a different one.   I have included the new encrypted log after arming the system and triggering the sensor.  Thanks!

**Comment by xirtamoen** [comment]
@twrecked / @JeffSteinbok Does anyone have the arlo doorbell?  I noticed I don't see anything that will allow me to silence it during certain times of the day.   Is that something that has been tested/worked on?

**Comment by twrecked** [comment]
@xirtamoen I got an account to upgrade, I set up a VPN and it worked. It wiped out all my camera from my non-upgraded account - I believe @JeffSteinbok mentioned this would happen - so now I can test the code at my end.

I'll leave my connection running. Can you try changing the mode and tripping the sensors again? I should get notifications here. With this information I should be able to get the devices working in a day or two.

@JeffSteinbok I don't need that account at the moment, but thanks for the offer.

**Comment by xirtamoen** [comment]
@twrecked Just performed those actions.  Hopefully you got the notifications on your side.

**Comment by twrecked** [comment]
I did. Thanks. Now I just need to work out what it all means!

**Comment by JeffSteinbok** [comment]
@twrecked - Upgrading will wipe the **shared** cameras from a non-migrated account I expect. Oddly, with me, when I upgraded, my wife's upgraded too (I share to her).  The whole thing is rather strange and I'm quite disappointed with Arlo.

Good luck.

**Comment by twrecked** [comment]
@xirtamoen I'm getting there I promise :) It's getting late here but can you trigger a door open/close again and I'll check in first thing tomorrow? I got some of the logs last time but I realised I needed to force the backend to `sse` to catch all them.

I blame _Arlo_,  it's telling me one thing but the web client is acting in another way...

**Comment by xirtamoen** [comment]
Done! Thanks!

**Comment by twrecked** [comment]
Thanks. Can you do another? I needed to change my config a little more.

**Comment by xirtamoen** [comment]
Yup just did it again.

**Comment by twrecked** [comment]
Yay - I got it this time. Just to check, you went from closed to open?

```json
{ "action": "is",
  "from": "XXXXXXXXX",
  "properties": {"contactState": True},
  "resource": "sensors/XXXXXXXXX",
  "transId": "XXXXXXXXX!XXXXXXXXX!XXXXXXXXX"}
```

I should be able to get something to test later today or tomorrow.

**Comment by xirtamoen** [comment]
I went from closed to open ands then from open to closed.   I also triggered a different state on the security hub.  I went from Standby to Arm Away back to Standby.

**Comment by twrecked** [comment]
Can you give 0.7.4b0 a try. It has initial support for the sensor. I'm not sure all the sensor states will work correctly, I took a guess at how they worked, but open/close should be good.

![sensors](https://user-images.githubusercontent.com/47094394/215658261-57e6b29a-762b-49a2-b8d9-8dfe5ea70a81.png)

You will need to modify you configuration to get this to work. You can start with the following:

```yaml
# Your Arlo main configuration, this turns on the new api and forces the event updates to work
aarlo:
  ...your current config..
  backend: sse
  mode_api: v3
```

```yaml
# Your Arlo binary sensor configuration (these are supported by the sensor)
- platform: aarlo
  monitored_conditions:
  - motion
  - contact
  - light
  - leak
  - tamper
```

```yaml
# Your Arlo binary sensor configuration (these are supported by the sensor)
- platform: aarlo
  monitored_conditions:
  - battery_level
  - temperature
```

**Comment by xirtamoen** [comment]
@twrecked when I add the first two recommendations above I get the following.

Invalid config for [sensor.aarlo]: value must be one of ['air_quality', 'battery_level', 'captured_today', 'humidity', 'last_capture', 'recent_activity', 'signal_strength', 'temperature', 'total_cameras'] @ data['monitored_conditions'][10]. Got 'contact'
value must be one of ['air_quality', 'battery_level', 'captured_today', 'humidity', 'last_capture', 'recent_activity', 'signal_strength', 'temperature', 'total_cameras'] @ data['monitored_conditions'][11]. Got 'light'
value must be one of ['air_quality', 'battery_level', 'captured_today', 'humidity', 'last_capture', 'recent_activity', 'signal_strength', 'temperature', 'total_cameras'] @ data['monitored_conditions'][12]. Got 'leak'
value must be one of ['air_quality', 'battery_level', 'captured_today', 'humidity', 'last_capture', 'recent_activity', 'signal_strength', 'temperature', 'total_cameras'] @ data['monitored_conditions'][13]. Got 'tamper'
value must be one of ['air_quality', 'battery_level', 'captured_today', 'humidity', 'last_capture', 'recent_activity', 'signal_strength', 'temperature', 'total_cameras'] @ data['monitored_conditions'][9]. Got 'motion'. (See ?, line ?).

How do I give 0.7.4b0 a try?  I don't see where I can install it in HACS.

**Comment by twrecked** [comment]
Sorry, I made a mistake with the config explanation.

These are valid for the `binary sensor` configuration:

```yaml
- platform: aarlo
  monitored_conditions:
  - motion
  - contact
  - light
  - leak
  - tamper
```

And these are for the `sensor` configuration:
```yaml
- platform: aarlo
  monitored_conditions:
  - battery_level
  - temperature
```


The latest release should appear automatically under the _HACS_ plugin. Mine is showing an Arlo Camera update and the new version number.

**Comment by xirtamoen** [comment]
Thanks.  Now I am getting these and HACS did update me to newest/latest release.

Invalid config for [binary_sensor.aarlo]: value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][6]. Got 'contact'
value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][7]. Got 'light'
value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][8]. Got 'leak'
value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][9]. Got 'tamper'. (See ?, line ?).

**Comment by twrecked** [comment]
Did you restart? Because light is good. Here is my config I used for testing:

```yaml
- platform: aarlo
  monitored_conditions:
  - motion
  - sound
  - ding
  - cry
  - connectivity
  - contact
  - light
  - leak
  - tamper
```

**Comment by xirtamoen** [comment]
I did restart and still getting those errors.

Invalid config for [binary_sensor.aarlo]: value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][6]. Got 'contact'
value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][7]. Got 'light'
value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][8]. Got 'leak'
value must be one of ['connectivity', 'cry', 'ding', 'motion', 'sound'] @ data['monitored_conditions'][9]. Got 'tamper'. (See ?, line ?).

**Comment by twrecked** [comment]
Can you run this command from the directory you have your Home Assistant configuration in?

```sh
grep -r "Open/Close" custom_components/aarlo/
```

Can you paste the output here. You can use [backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)  to stop the output from being formated.

**Comment by xirtamoen** [comment]
Hi it came back with nothing.  

root@debian:/usr/share/hassio/homeassistant# grep -r "Open/Close" custom_components/aarlo/
root@debian:/usr/share/hassio/homeassistant#

**Comment by twrecked** [comment]
I don't think you code upgraded. Can you try again from HACS?

And thinking about, this is a better check:

```sh
grep -r __version__ custom_components/aarlo/
```

Which gives
```
custom_components/aarlo/pyaarlo/__init__.py:__version__ = "0.7.4b0"
custom_components/aarlo/__init__.py:__version__ = "0.7.4b0"
```
on my system.

**Comment by xirtamoen** [comment]
I copied the new custom_components folder over and see this now.

root@debian:/usr/share/hassio/homeassistant# grep -r "Open/Close" custom_components/aarlo/
grep: custom_components/aarlo/__pycache__/binary_sensor.cpython-310.pyc: binary file matches
custom_components/aarlo/binary_sensor.py:    "contact": ["Open/Close", "opening", CONTACT_STATE_KEY, [], None],
root@debian:/usr/share/hassio/homeassistant#

I also get this now as well.

grep: custom_components/aarlo/__pycache__/__init__.cpython-310.pyc: binary file matches
grep: custom_components/aarlo/pyaarlo/__pycache__/__init__.cpython-310.pyc: binary file matches
custom_components/aarlo/pyaarlo/__init__.py:__version__ = "0.7.4b0"
custom_components/aarlo/__init__.py:__version__ = "0.7.4b0"

**Comment by xirtamoen** [comment]
What was the name of the sensor when you tested against it?  I am not able to find Garage Door sensor under entities.

**Comment by twrecked** [comment]
I got ```binary_sensor.aarlo_motion_garage_door_sensor```.

**Comment by xirtamoen** [comment]
Interesting that sensor isn't showing up for me.

**Comment by twrecked** [comment]
Can you send the logs again? I'll take a look.

**Comment by xirtamoen** [comment]
[home-assistant.log (2).zip](https://github.com/twrecked/hass-aarlo/files/10562494/home-assistant.log.2.zip)
Here you go.  Thanks!

**Comment by twrecked** [comment]
I can see the hub in the trace but not the sensor. Can you check it's still being shared?

**Comment by twrecked** [comment]
And can you paste your binary sensor configuration? I think you found an unrelated bug.

**Comment by xirtamoen** [comment]
I realized that I didn't share out the sensor to the account I created for the Arlo config in Home Assistant.     So now I am seeing binary_sensor.aarlo_open_close_garage_door_sensor.   I assume this is the one I should be using. 

Here is my configuration for my binary sensor.
binary_sensor:
    - platform: aarlo
      monitored_conditions:
      - motion
      - sound
      - ding
      - cry
      - connectivity
      - motion
      - contact
      - light
      - leak
      - tamper

**Comment by twrecked** [comment]
That's the sensor.

And you have `motion` twice in your `monitored_conditions` list.

**Comment by xirtamoen** [comment]
Thanks for pointing that out!  I removed it but still having an issue monitoring the opening and closing with the arlo sensor that comes with the security hub.  Should I be able to arm the security hub through Home Assistant?   It isn’t allow me to do that even though the entity shows up.

**Comment by twrecked** [comment]
Can you give 0.7.4b1 a go? You'll need to specify the new api in your config:

```yaml
aarlo:
  ...
  mode_api: v3
```

That should be all you need to do. If you find you're missing events then set the backend to sse.

```yaml
aarlo:
  ...
  mode_api: v3
  backend: sse
```

**Comment by xirtamoen** [comment]
Thanks!  I am now able to get events when the garage door sensor goes is open or closed.

**Comment by twrecked** [comment]
Can you arm/disarm the hub?

**Comment by xirtamoen** [comment]
No, I am not able to do that.  Are you able to?  I still have it shared out to you.

**Comment by twrecked** [comment]
I haven't tried to alter your alarm. I'll give it a try here.

**Comment by xirtamoen** [comment]
You are able to do it!  How are you doing?

**Comment by twrecked** [comment]
You have to use this device: `alarm_control_panel.aarlo_home`; it's the location control, you can't access the hub directly in the new API.

**Comment by xirtamoen** [comment]
Mine shows up as alarm_control_panel.aarlo_arlo_security_hub.  What card are you using to do the arming of the security hub?

**Comment by twrecked** [comment]
Does your shared account have admin access or access to your home location? If it does can you send me another encrypted log. 

I'm not seeing any locations being given to you in the log and you can only arm/disarm with the location.

**Comment by twrecked** [comment]
I had to leave the computer so I'll look at the logs in a minute.

If you log into the Arlo web interface from the shared account does it look ok?

**Comment by twrecked** [comment]
There are no locations in the log. How did the Arlo web page look?

In the mean time I'll double check the ordering here.

**Comment by xirtamoen** [comment]
The Arlo web page looks fine.  Is there something I should be looking for?   I can see my devices and interact with them through my shared account.

**Comment by twrecked** [comment]
I'm not sure why it's not working. But what I'll do at this end is re-arrange some of the calls so they more line up with the Arlo web page and I'll double check the information we pass in, that might cause it to work differently.

In the meantime, does your shared account have more than one location? I have 2, your shared one and one it created when I migrated the account. I can see them at the top:

![homes](https://user-images.githubusercontent.com/47094394/216507773-7b93a5df-6ef1-43b0-bd43-df6b0410638d.png)

I f you only have one you could try creating a second one. It may 'trick' it into working. 

And this is the bit of the log showing the issue:

```
2023-02-02 16:38:46.703 DEBUG (SyncWorker_1) [pyaarlo] _refresh_locations
2023-02-02 16:38:46.886 WARNING (SyncWorker_1) [pyaarlo] No locations returned from /hmsdevicemanagement/users/ZZZZZZZZZZ/locations
```

**Comment by xirtamoen** [comment]
I do have two locations showing.  They both have the same name though.  Could that be the issue?

**Comment by twrecked** [comment]
I don't believe so but you could try renaming one of them, maybe not the shared one.

I've found a few pieces I can tweak in the code so I'll try and get that out later.

**Comment by twrecked** [comment]
Can you try 0.7.4b2. If it doesn't work can you attach a log.

Sorry this is taking so long but _Arlo_ doesn't publish an API so we have to work it all out ourselves.

**Comment by xirtamoen** [comment]
I did update to 0.7.4b2 and it still isn't changing for me.  Trust me I know that it can take some time to get some new working especially since Arlo isn't publishing the API for us to work with.

**Comment by twrecked** [comment]
Turns out there are 2 other people seeing the same issue. Rather than paste in the comment, I added instructions on how to get to the packets here:
https://github.com/twrecked/hass-aarlo/issues/687#issuecomment-1416165839

**Comment by xirtamoen** [comment]
@twrecked  sorry it has taken me so long.  I was out of town and just got back.    This is the URL I found from the packet you referred to in the comment you listed above.

https://myapi.arlo.com/hmsweb/v2/users/emergency/locations?eventId=FE!70344702-74b2-41b0-9265-2c644514c9cc&time=1676161814813

**Comment by twrecked** [comment]
So, try this:

- update to the latest 0.7 release
- make sure your shared account has the new interface
- add this to your configuration:

```yaml 
aarlo:
  ...
  save_session: False
```

And restart it. There might be a credential caching issue.
