### ISSUE TITLE
Web Socket help required

### ISSUE THREAD

**Issue by allenrong88** [twrecked/hass-aarlo#69]
Hi,

Is there anyone who can explain how to use the web socket mentioned in the wiki PLS?

What I am trying to achieve is to get url of the lastest video captured while motion is detected and send it to me via telegram.

Not sure whether it is feasible.

Any suggestion welcomed!

Thank you

**Comment by twrecked** [comment]
What environment/language are you hoping to capture the image in?

**Comment by allenrong88** [comment]
I am on Hass.io actually. All my automation was done by yaml and node-red (notification only). Thx

**Comment by twrecked** [comment]
I don't use node-red but I do use the websocket api from the aarlo-glance card. A quick look about and I found this:

https://community.home-assistant.io/t/camera-snapshots-from-node-red/108715

It looks like there is an "API" call you should be able to use and that will return the image to you.

**Comment by allenrong88** [comment]
Thanks for your reply.

Any tutorial around using API within YAML instead of NodeRed?

**Comment by twrecked** [comment]
I have no idea, I tend to do most complicated things through AppDaemon.

The Home Assistant Community is probably a good place to start.

**Comment by twrecked** [comment]
Not a bug with aarlo. See previous comment.
