### ISSUE TITLE
WIll not start since latest update

### ISSUE THREAD

**Issue by hssmith76** [twrecked/hass-aarlo#693]
I just updated teh aarlo component as per HACS update and now the arlo component will not load?

Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/aarlo/__init__.py", line 270, in async_setup
    arlo = await hass.async_add_executor_job(login, hass, conf)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 405, in login
    arlo = PyArlo(
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 240, in __init__
    self._refresh_locations()
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 338, in _refresh_locations
    sharedLocations = locationData.get("sharedLocations", [])
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by twrecked** [comment]
Can you revert the version for now, I'll push a fix later.

**Comment by hssmith76** [comment]
Actually just tried that and still has the error - has been working fine for ages before that. If useful HACS was updated at the same time, not sure if related?
________________________________

**Comment by twrecked** [comment]
The same error? 

I'm asking because the `_refresh_locations` code only appears in the new code.

**Comment by hssmith76** [comment]
Actually not 100% sure. I tried re-downloading it (0.7.2b13) in HACS and restarted but afterwards HACS still saying version 0.7.3 downloaded and not sure how to check with more certainty or force the reversion?

**Comment by Justbob56** [comment]
Getting the same error after updating just now.

**Comment by Justbob56** [comment]
And this if it helps...

Logger: homeassistant.setup
Source: setup.py:359
First occurred: 3:24:33 PM (4 occurrences)
Last logged: 3:24:33 PM

Unable to prepare setup for platform aarlo.binary_sensor: Unable to set up component.
Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
Unable to prepare setup for platform aarlo.camera: Unable to set up component.

**Comment by twrecked** [comment]
Can you try 0.7.3.1? It should catch the error.

**Comment by hssmith76** [comment]
Downloaded 0.7.3.1. Working again, thank you.



Sent from my Galaxy



-------- Original message --------
From: Steve Herrell ***@***.***>
Date: 27/01/2023 22:19 (GMT+00:00)
To: twrecked/hass-aarlo ***@***.***>
Cc: hssmith76 ***@***.***>, Author ***@***.***>
Subject: Re: [twrecked/hass-aarlo] WIll not start since latest update (Issue #693)


Can you try 0.7.3.1? It should catch the error.

**Comment by Justbob56** [comment]
Same here! Thanks!
