### ISSUE TITLE
Advice on the release of new versions

### ISSUE THREAD

**Issue by elax46** [twrecked/hass-aarlo#710]
I noticed that there is a massive beta phase going on. I advise you to release the various beta versions as [pre releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) in this way only those who want to install these betas do it and it is not released to all users

**Comment by twrecked** [comment]
Noted.

And the betas are probably going to happening for a week or two more - _Arlo_ is changing things about on me...
