### ISSUE TITLE
Being logged out of Arlo App

### ISSUE THREAD

**Issue by cgms** [twrecked/hass-aarlo#713]
I've setup Arlo on HASS with a seperate account and using 2FA effectively. However as soon as I go to my Arlo android app to look at an alert, or see why I didn't get called on a doorbell ring, the app logs me out. If I disable Arlo on HASS then it stays logged in.

Does Arlo have some weird setting where only 1 account can be polling at a time? I'm not a fan of Arlo anyway, but this is bonkers.

**Comment by twrecked** [comment]
You should be able to use 2 accounts without them tripping over each other.

One problem is _Aarlo_ could be re-using old credentials if you tried your non-shared account on it. Add the following to your config and try again:

```yaml
aarlo:
  save_session: False
```

**Comment by cgms** [comment]
That worked, creds must have been cached somewhere as I had uninstalled a couple of times and removed from config, but all good now, thanks for the help.
