### ISSUE TITLE
Issue with Essentials Battery Doorbell AVD2001

### ISSUE THREAD

**Issue by sambarlick** [twrecked/hass-aarlo#735]
I'm having an issue with 2 of the entities provided by the integration.

The first one is binary_sensor.aarlo_motion_front_door which never changes. The other one is sensor.aarlo_recent_activity_front_door which also doesn't change state.

I originally was using a seperate Arlo user for the integration but switched to the main user which has the Arlo pro subscription. Still no change in states for those 2 entities.

All other entities work.

The issue with binary_sensor.aarlo_motion_front_door has been an ongoing issue since I first started using the integration and I did report it a while ago, with no response, unfortunately.

Sam

**Comment by twrecked** [comment]
Can you provide the version information - Arlo and Home Assistant - and your Arlo related configuration.

**Comment by sambarlick** [comment]
Home Assistant version 2023.4.0.
Arlo integration is the latest I can download v0.7.4b9.

aarlo:
  username: my Arlo account username 
  password: my Arlo account password 
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com:993
  tfa_username: my email address 
  tfa_password: yzxumbryolebzess

**Comment by sambarlick** [comment]
Thanks for your reply @twrecked and sorry I accidentally closed the issue.

**Comment by twrecked** [comment]
Try adding this to you aarlo configuration:

```yaml
aarlo:
  ...
  refresh_devices_every: 2
  stream_timeout: 120
  request_timeout: 15
  reconnect_every: 60
  backend: sse
```

The web interface was designed to be interactive so we need to keep _kicking_ it.

**Comment by sambarlick** [comment]
That worked, thank you!

Which Arlo account should I use? The main one of the one I created for this integration?

**Comment by twrecked** [comment]
I don't understand the question. By _kicking it_ I meant that's what the new configuration items do, they periodically reconnect the component in the background. If it's working now you shouldn't need to do anything.

**Comment by sambarlick** [comment]
Sorry for the confusion, I ment because I have 2 accounts the main Arlo account and a sub account I created for Home assistant. Which account should I use for the subscription only features that the web UI provides.

I went back to the Arlo sub account and the subscription only features still work.

Thanks again for your help.
