### ISSUE TITLE
Wired doorbell won't update

### ISSUE THREAD

**Issue by dtc064** [twrecked/hass-aarlo#737]
I have the wired doorbell that I'm trying to set up with Aarlo.  I am able to successfully connect to my Arlo account using 2FA.  When I restart Home Assistant, it will load up Aaarlo, and provide updated data regarding things like the snapshot and "Last Front doorbell" activity date and time.  However, after that initial loading of data, nothing will update.  Aarlo (Home Assistant integration) isn't registering when motion is detected, updating the snapshot, or updating any of the associated information such as "Last Front doorbell" or recent activity.  Everything seems to be working fine through the regular Arlo app, as I can connect to my doorbell and am receiving notifications appropriately through its app.  I have tried both the SSE and MQTT backends, as well as not listing a backend at all.  I read somewhere that it works better with Gmail instead of outlook, so I tried both accounts to log in.  None of this has seemed to matter.

When I review the logs, the integration sems to start up correctly, but later I see: 
[pyaarlo] sseclient-error=StopIteration
[pyaarlo] fetching device list after ev-reconnect

Those errors will continue to repeat throughout the logs.  Below is my current config setup.  Any help you can provide would be really appreciated!

aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret gmail_username
  tfa_password: !secret gmail_app_password
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 60
  backend: sse
  db_motion_time: 30
  packet_dump: True

#Arlo integration setup
camera:
  - platform: aarlo

binary_sensor:
- platform: aarlo
  monitored_conditions:
  - sound
  - ding
  - connectivity
  - motion
  
sensor:
- platform: aarlo
  monitored_conditions:
  - total_cameras
  - last_capture
  - recent_activity
  - captured_today
  - battery_level
  - signal_strength

switch:
- platform: aarlo
  snapshot: True
  doorbell_silence: True

**Comment by dtc064** [comment]
I don't know if this is actually relevant, but while looking through a bunch of the files on File Editor via Home Assistant, I noticed that the aarlo.pickle and session.pickle files both say "'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte" when I open them.  Other files I open have normal looking code.  I was wondering if this could be contributing to my errors, or this is normal and expected.  I also enabled verbose debugging if that would be helpful.

**Comment by twrecked** [comment]
I got a lot of `StopIteration` errors at my end, about 12-15 a day on average, it's just the backend dropping the connection. You might lose an _Arlo_ event while we reconnect but it's not the reason you're not seeing door bell events.

The strange bytes in the _aarlo_ files is fine, it's a binary format used by _Python_.

Can you turn on [basic debug](https://github.com/twrecked/hass-aarlo#basic-debug) and look at the logs generated? Look for events generated with the door bell name in them. If you want, you can upload them here, you can use [this webpage](https://pyaarlo-tfa.appspot.com/) to encrypt the logs so only I can see them.

**Comment by dtc064** [comment]
Thanks for being willing to help me with this!  I'm out of town but will be able to get those logs to you ASAP next week.

**Comment by dtc064** [comment]
I turned on basic debug and looked through the logs, but don't see any obvious events being triggered by the doorbell.  It seems like a lot of StopIteration notifications followed by everything resetting itself.  I've attached a copy of the encrypted logs here.  I rebooted the system after adding basic debug around 11AM, and went outside to trigger the motion sensor on the doorbell myself at 1:23pm and 1:25pm.  Both times, I received notifications from the Arlo app that motion had been detected but never saw anything show up on Home Assistant.  Thanks again for looking into this.

[HA_arlo_logs.txt](https://github.com/twrecked/hass-aarlo/files/11480426/HA_arlo_logs.txt)

**Comment by twrecked** [comment]
I might have an idea. I'm seeing this in the log:

```
2023-05-15 11:09:59.342 DEBUG (SyncWorker_6) [pyaarlo] NO ping to A8CXXXXXXXXX
```

I think we should be pinging the device. I think without the ping it might not send events. I'll push a possible fix later.

**Comment by twrecked** [comment]
Can you try the beta 13 build? It might have fixed the issue.

**Comment by dtc064** [comment]
I just tried the beta 13 build.  It fixed most of the integration for me.  It now correctly identifies when there is motion, adjusts the "Recent Activity Front doorbell" variable, and the header on the video stream correctly changes to "Recording" and then "recently active."  However, the actual video stream itself does not update to show the new recording, and the "Last Front doorbell" variable which shows the time that it last detected motion isn't updating.  These are definitely less important to me than the motion detection was but would be amazing if they worked too.  I've attached a copy of the logs from the beta 13 build.  Thanks for your quick work on this!

[home-assistant_2023-05-17T21-32-41.067Z.log](https://github.com/twrecked/hass-aarlo/files/11502662/home-assistant_2023-05-17T21-32-41.067Z.log)

**Comment by twrecked** [comment]
I'm not seeing `mediaUploadNotifications` happening. So, there are a couple of things we can try:

- change the back end to `mqtt`
- add the following to your `aarlo` config, it will force a library reload:
```yaml
  ...
  media_retry:
  - 5
  - 15
  - 25
```

**Comment by dtc064** [comment]
Mqtt didn't work for me, but adding media_retry fixed it!  Thanks so much for all of your help and hard work with this project!
