### ISSUE TITLE
problem after update 

### ISSUE THREAD

**Issue by leoni1986** [twrecked/hass-aarlo#750]
Hi I recive this message:
Error: unable to read mode, try forcing v2
If error persists you might need to change config and restart. 
what i can do ? i try to reset the password of map but i 'm not sure i it the problem... if i try to connect to arlo login on web i recive the message logout why anthoter device... and i suppose the login is ok.. but i don't see any camera

**Comment by twrecked** [comment]
Can you post your config?

**Comment by leoni1986** [comment]
I re-install the HACS, and now work.... thanks

**Comment by twrecked** [comment]
Glad to hear it's going again. There were some header changes at the _Arlo_ end that might have caused you issues.
