### ISSUE TITLE
ocapi-app.arlo.com Access Denied

### ISSUE THREAD

**Issue by daveyijzermans** [twrecked/hass-aarlo#752]
Hi,

I almost can't imagine the amount of work you must be putting into this integration to keep it working with Arlo's ever changing servers. So first and foremost, thanks for all your efforts!

Unfortunately, when restarting Home Assistant just this night, the integration will not authenticate anymore. I've ruled out 2FA and MQTT errors by experimenting with `mqtt_host` and `mqtt_hostname_check` options. I also reverted to `backend: sse` but the logs showed:

```
Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:495 
Integration: aarlo (documentation, issues) 
First occurred: 01:13:00 (5 occurrences) 
Last logged: 01:16:59

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed
unable to connect to Arlo: attempt=5,sleep=240,error=authentication failed
```

and then I saw this:

```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:165 
Integration: aarlo (documentation, issues) 
First occurred: 01:12:56 (20 occurrences) 
Last logged: 01:16:59

body-error=JSONDecodeError
authentication failed
```

So I've enabled debug logs and now I see that I'm hitting an access denied error when accessing the API endpoint ocapi-app.arlo.com.

```
2023-05-18 01:24:07.426 DEBUG (SyncWorker_1) [pyaarlo] request-text=<!DOCTYPE html>
<html lang="en-US">
<head>*snip*
</head>
<body>

...

<div class="cf-error-description">
<p>You do not have access to ocapi-app.arlo.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
</div>

...

<p>Error code: 1020</p>
<p>Ray ID: 7c8f9cb1fadab6fa</p>
<p>Country: *snip*</p>
<p>Data center: ams06</p>
<p>IP: *snip*</p>
<p>Timestamp: 2023-05-17 23:24:07 UTC</p>
</div>
 
...

</html>
```

Have you seen this before? Is the API being rate limited or just down in my country? I've tried visiting this page using 4G and a VPN in a different country but I also get the Access Denied there. Is Arlo taking steps to deny 3rd party access?

I truly hope there's something I'm just doing wrong, but I can't confirm until I can find if others are affected as well.

Kind regards,

Davey.

**Comment by twrecked** [comment]
This is the _cloudflare_ stuff. Your connection is even getting to _Arlo_.

You're on the latest version? If so, can you turn on [basic logging](https://github.com/twrecked/hass-aarlo#basic-debug) and upload some [encrypted](https://pyaarlo-tfa.appspot.com/) logs?

**Comment by daveyijzermans** [comment]
I'm running version v0.7.4b12

Attached some logs, although it doesn't say much more than it hitting Cloudflare

[logs.txt](https://github.com/twrecked/hass-aarlo/files/11503522/logs.txt)

Anything from [your suggestions here](https://github.com/twrecked/hass-aarlo#cloud-flare) I should try? Although there is no mention of the CloudflareChallengeError in the logs.

**Comment by twrecked** [comment]
As for the suggestions, possibly, Cloudflare is a pain to deal with...

Some things to try:

- delete the files in `.aarlo`, they will be named something like this:
```
$ ls .aarlo
aarlo.pickle  session.pickle
```

- are you any good with an editor? You can try a newer version of the `cloudscraper` code. Edit this file `custom_components/aarlo/manifest.json`, and change this line from:

```
"requirements": ["unidecode","cloudscraper>=1.2.64", "paho-mqtt"],
```

To

```
"requirements": ["unidecode","cloudscraper>=1.2.71", "paho-mqtt"],
```

Notice the 71 in the version number. I'll push this change as an update later.

- Can you try logging into the _Arlo_ camera website with the account you use for _HA_. I had one person earlier who needed to log in to upgrade.

- If this doesn't work can you turn on [verbose debug](https://github.com/twrecked/hass-aarlo#verbose-debug) and upload some logs.

**Comment by bjia56** [comment]
Hey there - I'm the developer for the Arlo plugin over on the [Scrypted](https://github.com/koush/scrypted) project.

We also had users report the same login 403 returned by Cloudflare. Unfortunately it seems to be unclear who's affected and who isn't, and not sure what changed on Cloudflare's side. It might end up being a temporary fix, but I had some luck with [this method](https://scrapeops.io/web-scraping-playbook/how-to-bypass-cloudflare/#option-1-send-requests-to-origin-server) and doing just the auth portion of Arlo directly against IPs - just wanted to share in case haas-arlo wants to consider something similar.

**Comment by twrecked** [comment]
@bjia56 Thanks, I really appreciate the information, I'll look into it.

**Comment by daveyijzermans** [comment]
Fortunately for me, but unfortunately for the debug process, I woke up to a 2FA notification today, so it seems that it has resolved itself. It now says in the log `newish sessions, re-using` so maybe there was something with my old sessions. Sorry for the bother!

**Comment by twrecked** [comment]
Glad it's working again, my current best guess is:

- _Arlo_ updated their back end
- the component needed to log in again, the log in failed
- it kept failing
- _cloudflare_ locked you out
- you updated the component but were still locked out
- eventually the _cloudflare_ cleared

It'll probably keep going now until they make another change...
