### ISSUE TITLE
Error authentication 

### ISSUE THREAD

**Issue by blair287** [twrecked/hass-aarlo#754]
This has been running for about a year no issues at all but today when I had to restart HA I started getting this error

This error originated from a custom integration.

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:495
Integration: aarlo (documentation, issues)
First occurred: 08:39:25 (3 occurrences)
Last logged: 08:40:18

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed

The component will not restart. I've tested the arlo account I have set up for HA and can login no issues at all on my phone but HA just keep generating this error running tje latest version on HACs

**Comment by twrecked** [comment]
What was it in the end?

**Comment by uwskier** [comment]
Also interested in this answer.  I've been using this integration for years but suddenly in the past few days I can't get authentication to work at all.  Have tried a number of things, including setting up tfa on my gmail, trying a different gmail with a new Arlo acct, etc.

**Comment by uwskier** [comment]
aaannndddd, it just sortof started working on its own again...  Wonder if the Arlo servers were having a bout of indigestion.
