### ISSUE TITLE
Cloudflare error 1020, error visiting ocapi-app.arlo.com

### ISSUE THREAD

**Issue by gfawkes66** [twrecked/hass-aarlo#760]
I rebooted HA today for the first time in a few weeks and found AARLO wouldn't login to arlo.

This seems similar to #752 by the way.

i turned on debugging and see this in the logs -

         <div class="cf-error-description">
            <p>You do not have access to ocapi-app.arlo.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
         </div>

and -
<p>Error code: 1020</p>
<p>Ray ID: xxxxxxxxxxxxxxxx</p>
<p>Country: GB</p>
<p>Data center: lhr10</p>
<p>IP: 92.xx.xx.xx</p>
<p>Timestamp: 2023-06-08 12:47:26 UTC</p>

what i tried:-
i tried visiting the ocapi-app.arlo.com in my desktop browser, this also returns the 1020 as a webpage
I speculated as per #752 that my ip was blocked, so i opened ocapi-app.arlo.com on my iphone browser whilst NOT connected to wifi (ie 4g), this gave the same 1020 error.
no account info was passed in either case. interesting that i used 2 different networks.

i have a pihole and i see call made by the arlo app to myapi.arlo.com and ocapi.arlo.com amongst others but not ocapi-app, so i wonder if this means something? or is just a red herring?

Does someone with a bigger brain have some thoughts?

Thanks.

**Comment by henrithiesen** [comment]
Hi,
I have the same problem since this morning.


//Henri

**Comment by twrecked** [comment]
Try with a different user agent, mine started to fail until I forced the agent to `linux`.

**Comment by gfawkes66** [comment]
thanks for the suggestion. 
i tried adding user_agent: linux and restarting but unfortunately the issue persists.

**Comment by twrecked** [comment]
Can you try the 0.7.b14 update?

**Comment by gfawkes66** [comment]
I tried the 0.7.b14 update and am still getting the same cloudflare error 1020 - 

            <p>You do not have access to ocapi-app.arlo.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>

**Comment by gfawkes66** [comment]
Well as if by magic, the error 1020 seems to have stopped all by itself. it came and went overnight, and this morning, i am consistently getting imap login attempts.

The problem now seems to be now that the new email i want is in the inbox at the beginning of the process (old id check)
here, id no 45 is the latest email but has been flagged as an old one.

Thanks.

2023-06-09 09:02:58.761 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: starting
2023-06-09 09:02:59.542 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: old-ids=[b'20 21 23 25 26 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45']
2023-06-09 09:02:59.543 DEBUG (SyncWorker_2) [pyaarlo] starting auth with email
2023-06-09 09:03:00.035 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: checking
2023-06-09 09:03:00.036 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: retry-every=3,up-to=150
2023-06-09 09:03:03.123 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: new-ids=[b'20 21 23 25 26 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45']
2023-06-09 09:03:03.124 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: no change in emails
2023-06-09 09:03:06.211 DEBUG (SyncWorker_2) [pyaarlo] 2fa-imap: new-ids=[b'20 21 23 25 26 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45']

**Comment by twrecked** [comment]
It usually comes back. I think if you make too many wrong requests it locks you IP address.

As for the email, that's very odd and a new one. The code works like this:

- look at 2fa choices, pick email if there
- take a snapshot of the email inbox
- send in the authentication request
- take another snapshot of inbox, see what has changed
- if something has changed see if it's the email we're looking for

The email shouldn't be sent until we send in the request. I'm not sure what is happening with you. Can you give it a few minutes and try again? Maybe there are limiting the number of emails they send.

**Comment by gfawkes66** [comment]
Hi, i worked around the issue by using the push to app.

Im quite happy to try some troubleshooting/retry but after changing back the config it doesn't go through the 2FA on reboot - presumably there is a session token somewhere.

If you let me know how to remove the session token ill try it again.

Just one question - when you say 'look at 2fa choices, pick email if there' - is that checking the account on arlo.com or a local check?

Thanks.

**Comment by twrecked** [comment]
Look in `.aarlo`, there will be some pickle files in there, delete `session.pickle`.

As for your question about `look at 2fa choices, pick email if there`, to be honest there's a bit of both. The code looks at your 2fa preference and if you choose email it sees if your _Arlo_ account has the same option. If the accounr does it will try to use email to get the code.

**Comment by gfawkes66** [comment]
OK some success.

i removed the .pickle and after reboot was faced with the cloudflare 1020 error as before. When the 1020 errors stopped and aarlo tried to login again, i was faced with the same issue. The email appeared in my outlook inbox about 5 seconds after being sent but was not being picked up/ seen by the imap process. Anyway, I switched to a gmail account and it worked straight away.

Interesting that i had a load of 1020 errors again after reboot.

I guess you could say the lesson here is to understand the process. Thanks for all the help. Closing the ticket.
