### ISSUE TITLE
How to change arlo account

### ISSUE THREAD

**Issue by johnnybhuang** [twrecked/hass-aarlo#765]
Hey team, got this going last night pretty easily so we'll done team.
1 question. I created a second account as recommended but after adding the 2nd account to my main it couldn't see any devices (I have Arlo Pro 2). In the end, I just got it going on my main account for now. Since then I've tried to get it logging in using my 2nd account but it seems that even if I update the configuration.yaml file with different arl username/ pass and 2fa settings it just keeps auth as my main account... I've tried restarting HA, even got rid of Aarlo and reinstalled it.

How do I change the account aarlo uses?

**Comment by johnnybhuang** [comment]
I also turned on debugging and see that aarlo is indeed still authenticating using my main account despite my updating the configuration.yaml file.  I see in there the token has an expiry of 14 days total so unless someone can help me force a re-auth attempt, I might have to wait another 2 weeks for the current token to expire before I can try and get it to use my 2nd account.

**Comment by twrecked** [comment]
You just have to delete the token, look in `.aarlo` where your configuration is, there will be a file called `session.pickle`.

**Comment by johnnybhuang** [comment]
perfect thanks!!  it ended up having to renew the token after 2 weeks anyway so the new config then took affect.  thanks mate! love your work!
