### ISSUE TITLE
Turn camera off

### ISSUE THREAD

**Issue by johnnybhuang** [twrecked/hass-aarlo#766]
Team, I used to use Smartthings to automated turning on and off the Arlo Pro 2 cameras based on if I was home or not. I found turning them off (as opposed to disarming) was much better for battery life.
Is there a way I can turn the camera off via Aarlo?

**Comment by twrecked** [comment]
Does the `camera.turn_off` service not work?

**Comment by johnnybhuang** [comment]
ah perfect.  I didn't see that Service.  thank you!
