### ISSUE TITLE
b17 - services disarmed / armed_away no longer work

### ISSUE THREAD

**Issue by herveaurel** [twrecked/hass-aarlo#774]
Hello, with the latest version b17 everything works fine except the services to arm and disarm my Arlo doorbell alarm.
In the logs I see this:

This error is from a custom integration

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:712
Integration: Arlo Camera Support (docs, issues)
First occurred: 10:55:59 (2 occurrences)
Last logged: 10:58:15

Failed to set mode.

**Comment by twrecked** [comment]
I have a fix, I'd commented out a line to get the new _Arlo_ headers working and forgot to add it back. I'll push it later.

See here: https://github.com/twrecked/pyaarlo/issues/121#issuecomment-1623646276

**Comment by herveaurel** [comment]
> I have a fix, I'd commented out a line to get the new _Arlo_ headers working and forgot to add it back. I'll push it later.
> 
> 
> 
> See here: https://github.com/twrecked/pyaarlo/issues/121#issuecomment-1623646276
> 
> 

a very big thank you for all the work! because without this deposit, our Arlo devices would be incompatible with HA!

**Comment by ninjazx06** [comment]
YES! b18 WORKED!
@twrecked THANK YOU!

**Comment by Phoenix-DH** [comment]
I still get the auth error.

**Comment by twrecked** [comment]
@Phoenix-DH Can you encrypt some debug logs and upload them. I'll take a look. 

Also, one guy found that changing the `cloudscraper` parameters to this helped fix his issue. On line 854 of `background.py`:

```python
            # change this
            self._session = cloudscraper.create_scraper()
            # to this
            self._session = cloudscraper.create_scraper(ecdhCurve='secp384r1')
```

**Comment by herveaurel** [comment]
B18 : Perfect ! 😍

**Comment by ynazar1** [comment]
B18 can confirm arm/disarm working and B17 fixed auth...  

@tbrown65 : Make sure you can log in first on browser/phone. You've got something else going on probably, like missing 2fa or something.

I've got phone set up to send push to and had to login on the phone with home assistant account first before it started reliably sending push notifications to it (arlo's backend is notoriously bad about it). 

My configs... 


```aarlo:
  username: !secret arlo.user
  password: !secret arlo.pass
  refresh_devices_every: 2
  stream_timeout: 120
  refresh_modes_every: 1
  reconnect_every: 30
  request_timeout: 120
  packet_dump: false
  backend: sse
  mqtt_hostname_check: False
  tfa_source: push
  tfa_type: PUSH```
