### ISSUE TITLE
Custom Updater is dead, please support HACS

### ISSUE THREAD

**Issue by rafuz** [twrecked/hass-aarlo#79]
Custom Updater is deprecated, please convert AARLO to [HACS ](https://github.com/custom-components/hacs), it would be really nice!

**Comment by twrecked** [comment]
I'm going to set up HACS on my system but if anybody has it all ready running you can try this branch, it should support the integration format:

  https://github.com/twrecked/hass-aarlo/tree/HACS

**Comment by jwillaz** [comment]
I set up HACS, and it appears that you can only add Custom Repos via their master branch (doesn't accept paths to other branches).

**Comment by twrecked** [comment]
I didn't get chance to set up HACS yet - hopefully tonight - but I was hoping I could just add a line to a file and give it a try before I created a PR for the HACS code.

I guess I'll generate the HACS request and then work on any issues on my end.

**Comment by twrecked** [comment]
So far so good. I merged the HACS branch into master, added https://github.com/twrecked/hass-aarlo as a custom repository and it seems to be working.

The only problem is I need to split out the custom card into a second repository to get that working.

I'll create a PR request to add me in as a default.

**Comment by twrecked** [comment]
And you can use https://github.com/twrecked/lovelace-hass-aarlo for the plugin repository. But we aware, the card name has changed.

**Comment by twrecked** [comment]
aarlo is now in the HACS.

**Comment by jwillaz** [comment]
This is awesome - works great!  Thanks @twrecked !

**Comment by twrecked** [comment]
Fixed by #90
