### ISSUE TITLE
Turn Cameras on/off?

### ISSUE THREAD

**Issue by tue-nielsen** [twrecked/hass-aarlo#801]
Hi,

is it possible to simply turn cameras on/off?

used this feature with smartthings currently.

so when i am home my indoor cameras is turned off, so that they do not record and/or use battery
when i leave they are turned back on

this will extend battery life a lot

**Comment by twrecked** [comment]
https://www.home-assistant.io/integrations/camera/

We should support the `turn_off` and `turn_on` services.

**Comment by shupershuff** [comment]
> https://www.home-assistant.io/integrations/camera/
> 
> We should support the `turn_off` and `turn_on` services.

In a similar vein, is it possible to arm/disarm cameras using this add-on?

**Comment by tue-nielsen** [comment]
I can confirm it is possible to turn camera on/off using this integration. 

Also you can change modes of each camera. 
i believe this is what you mean by arm/disarm. 
you can also change to custom modes which is very neat. 
for example i have a mode on my outdoor cameras where it records but do not send a push message. I use this when i arrive at home and stay home.
