### ISSUE TITLE
Thumbnails broken after a day or two

### ISSUE THREAD

**Issue by jxlarrea** [twrecked/hass-aarlo#81]
After a day or two, the camera thumbnails do not show up in the lovelace cards and instead a broken image placeholder appears. When this happens, there is no way to click on the thumbnail/snapshot to start a camera stream.

A full HA restart solves the issue until it happens again.

I did try using the `refresh_devices_every` option, thinking that a device refresh might fix the problem but no luck.

**Comment by rccoleman** [comment]
I’ve noticed that, too. One by one, my thumbnails seem to drop out and become broken links until I restart home Assistant. The remaining ones still work. I was down to one from five before the last update. I was planning to find applicable logs before creating a new issue, but wanted speak up here.

**Comment by jxlarrea** [comment]
Since it happened once again, figured I would upload a screenshot of the issue:

[https://i.imgur.com/dTeHUCg.jpg](https://i.imgur.com/dTeHUCg.jpg)

Again restarting HA fixes the problem until it happens again.

**Comment by jxlarrea** [comment]
@twrecked have you had a chance to check this issue? In my limited understanding on HA and Python, it seems that `websocket_snapshot_image` in `camera.py` throws an exception with the message `"image_fetch_failed"`.  Also, all aarlo related automations stop working when this issue occurs. Perhaps the event stream goes down and does not reconnect for some reason? Maybe the API token gets invalidated after a while? Or if the internet connection goes down, the component stops attempting to reconnect?

**Comment by twrecked** [comment]
I'll get chance in a day or two. I've been away from my computer traveling for a week or two.

**Comment by twrecked** [comment]
I have an idea what this. I try to reload thumbnails once a day and that piece is failing.

**Comment by twrecked** [comment]
I'm testing a fix in this branch: https://github.com/twrecked/hass-aarlo/tree/thumbnail-fix

I'll need to leave it running over night to see if it works.

**Comment by jxlarrea** [comment]
Great! I will wait for the fix to be pushed into the master branch along with the other couple of issues already fixed.

**Comment by twrecked** [comment]
Fixed by #88
