### ISSUE TITLE
Include component in HACS

### ISSUE THREAD

**Issue by pichlerralf** [twrecked/hass-aarlo#82]
Lots of people are currently changing from custum_updater to the new HACS, which is much more user friendly.

So i am opening an issue here because surely not only me would love to see your component is included into HACS (Home Assistant Community Store):
https://github.com/custom-components/hacs

Thanks very much in advance!

P.S.: thanks very much for providing such a great component for HA!

Regards,
Ralf Pichler

**Comment by cbfreeborn** [comment]
I would definitely second that request.

**Comment by twrecked** [comment]
I'm planning on doing I'm just away from my computer for the next week.

**Comment by ryanwinter** [comment]
HACS would be nice, although replacing the existing arlo component would be the best end result.

**Comment by twrecked** [comment]
Duplicate of #79
