### ISSUE TITLE
Battery missing from Aarlo cameras

### ISSUE THREAD

**Issue by Avatar1976** [twrecked/hass-aarlo#827]
Hi Twrecked,
I recently upgraded to v0.8.1a3 and the cameras came across perfectly along with an all cameras control.
To test the new configuration flow I then deleted my imported configuration which included save_session and a few other things.
After adding my arlo account back through the configuration flow, I notice the all cameras control is now missing and controls and the battery is missing from each camera.
Could this be related to the session.pickle?
Any help much appreciated as always. Cameras seem to be working otherwise BTW.

**Comment by twrecked** [comment]
I think I know what this is. I think I forget to configure the options correctly. Try the "configure" button on the Integration screen and follow the screens through.

**Comment by twrecked** [comment]
If it works they should all come back immediately.

**Comment by Avatar1976** [comment]
> I think I know what this is. I think I forget to configure the options correctly. Try the "configure" button on the Integration screen and follow the screens through.
> 
> edit: none of the sensors will have been enabled by default

Yes from what I can see there is no way of getting the sensors back if you delete your config and attempt to add it back again. If your config existed in a previous version it comes across fine though.
Did try deleting config and commenting out sensors and main arlo config areas from configuration.yaml but even adding back then through the config flow only it still fails to create sensors.

**Comment by twrecked** [comment]
Firstly, there is a bug and the sensors should appear. I'll fix that and I'll push a fix later.

But you should have been able to get them back by configuring the integration, I tried it just and all my devices reappeared. Click `CONFIGURE` and choose the entries you want from the screens following.

![Screenshot from 2023-11-02 09-04-46](https://github.com/twrecked/hass-aarlo/assets/47094394/a1fcaa3a-effe-48ab-ae80-f40185789e68)

**Comment by twrecked** [comment]
Should be fixed by #828 and available in the `alpha.4`

**Comment by Avatar1976** [comment]
> Should be fixed by #828 and available in the `alpha.4`

Great thanks Twrecked updated and submitted through the series of config screens and all back and working now.

**Comment by twrecked** [comment]
And thanks for braving the alpha build, it's appreciated!
