### ISSUE TITLE
Automation change mode

### ISSUE THREAD

**Issue by rossmarkflo** [twrecked/hass-aarlo#830]
Might be a total noob question, but I struggle with automations...

My goal:
When entering Geo zone, set ARLO mode to HOME and when leaving set to AWAY via automations.

The Geo zones are easy, but I don't seem to be able to understand how to set the ARLO modes... I can do that in the dashboard with a simple button but fail to understand how to implement this in an automation.

Further - can this be done per camera as well? I think I saw this, but I am a bit stuck...

What I had so far is below, but I am not clear on how to submit the DATA part: 

service: aarlo.alarm_set_mode
data:
  entity_id: automation.arlo_home

**Comment by rossmarkflo** [comment]
OK - found how to set them.. 

action:
  - service: alarm_control_panel.alarm_arm_away
    data: {}
    target:
      entity_id: alarm_control_panel.aarlo_location_home

The question that remains, since I had to update to the new panel, how do I set aarlo_location_standby ? This seems to be the only way to have a third state activated, that I prefer to use after sunset and before sunrise.. outdoor cameras around the permitter active, not the inhouse.. 

Is there a way?

**Comment by Diplo95** [comment]
Hi @rossmarkflo 
I'm totally new in Aarlo too !!
Could you give me your code for a simple button o, dashboard to change arlo mode ? I can't figure out how to do that simple thing !!
Thx

**Comment by rossmarkflo** [comment]
There is a Dashboard CARD available, called ALARM PANEL - that allows you change modes..

As for the automations, the third mode in the new ARLO Control Panel is simply called DISARMed

Therefor the three modes are:

This plugin Dash Card - This plugin Automation - Arlo App 
======================================
Away - alarm_control_panel.alarm_arm_away - Arm Away
Home - alarm_control_panel.alarm_arm_home - Arm Home
Disarmed - alarm_control_panel.alarm_disarm - Standby

**Comment by rossmarkflo** [comment]
Closing this - as my questions here are answered
