### ISSUE TITLE
alarm_control_panel.aarlo_home card does not update state

### ISSUE THREAD

**Issue by Pete118** [twrecked/hass-aarlo#832]
Hi,

I don't know why, but since yesterday the card does not work as expected. The card works afte restart of HA for a little time. Then the function of the button is still workingbut does not update the state. So if I click deactivate, the Arlo cams are deactivated but the state of the card does nt update. So it is immpossibleto activate the cams over the card. If i restartr ha it works again for a short time. Any ideas? I am on version 0.7.4

**Comment by twrecked** [comment]
Can you post your aarlo config here?
