### ISSUE TITLE
External js dependency in aarlo-glance

### ISSUE THREAD

**Issue by ryanwinter** [twrecked/hass-aarlo#84]
The following PR removes the external js dependency for LitElement.

https://github.com/twrecked/hass-aarlo/pull/83

**Comment by ryanwinter** [comment]
I noticed there is still an additional dependency on hls.js which is included in the Home Assistant webpack.

**Comment by twrecked** [comment]
I've just brought in your pull request. Is it ok to close this one?

**Comment by ryanwinter** [comment]
Yes, thanks!

**Comment by twrecked** [comment]
Fixed by #83
