### ISSUE TITLE
Camera stream never stops when playing from Lovelace card on touch screen devices

### ISSUE THREAD

**Issue by jxlarrea** [twrecked/hass-aarlo#85]
Unless I'm missing something, there is no way to stop a camera stream when playing from the provided custom Lovelace `aarlo-glance.js` card on a touch screen device. 

Seems like the `<video>` element in the card does not properly respond to a touch event (tap) to stop the stream, only allowing to pause the stream but not actually stopping it. 

It works properly on desktop using mouse / click events.

**Comment by jxlarrea** [comment]
Fixed it by adding to the video tag template:

`on-tap="${(e) => { this.stopStream(this._cameraId); }}"`

I would submit a pull request and push the fix myself but I don't know how any of this Github stuff works.

**Comment by twrecked** [comment]
I'll add that in. Thanks!

**Comment by twrecked** [comment]
I'm testing a fix in this branch: https://github.com/twrecked/hass-aarlo/tree/thumbnail-fix

I'll need to leave it running over night to see if it works.

**Comment by twrecked** [comment]
Fixed in #88
