### ISSUE TITLE
No Connection to Arlo - Authentication failed 

### ISSUE THREAD

**Issue by hendrikwolf79** [twrecked/hass-aarlo#852]
Nothing was changed but the connection to arlo failed.

Restarting the system didn't fix the problem.
Reinstalling didn't help either.

v0.8.1a10

Logger: pyaarlo
Source: custom_components/aarlo/__init__.py:406
Integration: Arlo Camera Support ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 10:52:14 (108 occurrences)
Last logged: 11:06:48

session start failed
body-error=JSONDecodeError
authentication failed

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:420
Integration: Arlo Camera Support ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 10:52:22 (12 occurrences)
Last logged: 11:06:48

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed

[aarlo config.txt](https://github.com/twrecked/hass-aarlo/files/13761451/aarlo.config.txt)
[aarlo_log.txt](https://github.com/twrecked/hass-aarlo/files/13762001/aarlo_log.txt)

**Comment by hendrikwolf79** [comment]
I solved the problem by creating a new account and switching to the newer interface.

**Comment by petepall** [comment]
@hendrikwolf79 Can you provide some more details on what you did and what you mean with newer interface?
