### ISSUE TITLE
v0.8.1a10 - Arlo Baby cannot change modes

### ISSUE THREAD

**Issue by collse** [twrecked/hass-aarlo#868]
not sure how to provide more information, as everything else works fine just the baby itself does not allow to change any modes.

interestingly, previously I believe this was handled through a duplicate base being presented, not sure if if those were more independent?

Logger: pyaarlo
Source: custom_components/aarlo/alarm_control_panel.py:344
Integration: Arlo Camera Support ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 11:16:50 (3 occurrences)
Last logged: 11:22:00

Nursery: mode disarmed is unrecognised
Nursery: mode home is unrecognised

**Comment by collse** [comment]
not much in the errors when debugging:

"2024-01-23 09:38:03.186 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=alarm_control_panel, service=alarm_arm_home, service_data=entity_id=alarm_control_panel.aarlo_nursery>
2024-01-23 09:38:03.188 DEBUG (SyncWorker_11) [custom_components.aarlo.alarm_control_panel] Nursery set mode to home
2024-01-23 09:38:03.188 WARNING (SyncWorker_11) [pyaarlo] Nursery: mode home is unrecognised"

as if it doesnt properly register as a base but as a "camera" maybe?

**Comment by twrecked** [comment]
It may not be reading the modes correctly. Did your Arlo upgrade the new location based one?

**Comment by collse** [comment]
sorry, was travelling - not sure I understand the question

the upgrade moved the configurations if that is the question - this is what shows in HA
![SCR-20240128-cql](https://github.com/twrecked/hass-aarlo/assets/5358625/3c1109d2-317f-4779-a95e-d2777cd1165f)
![SCR-20240128-cpx](https://github.com/twrecked/hass-aarlo/assets/5358625/a738ef98-bc2e-41b1-850e-c4a2f1f183b7)
![SCR-20240128-cpb](https://github.com/twrecked/hass-aarlo/assets/5358625/92ab3220-3a25-468a-b622-582eb23bf83f)
![SCR-20240128-coq](https://github.com/twrecked/hass-aarlo/assets/5358625/7b392990-ea1e-449b-a52d-bbb9fd12743a)

**Comment by collse** [comment]
gave it another shot, changing config/arrlo.yaml to include: 
mode_api: v2

allows me to change the modes again but now additional errors show up

> Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:205
Integration: Alarm Control Panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 09:27:20 (4 occurrences)
Last logged: 09:27:20

FORMAT_NUMBER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
FORMAT_TEXT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.TEXT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

> Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 09:27:17 (4 occurrences)
Last logged: 09:27:20

TEMP_CELSIUS was used from bestway, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/cdpuk/ha-bestway/issues
TEMP_FAHRENHEIT was used from bestway, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/cdpuk/ha-bestway/issues
TEMP_CELSIUS was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment]
Is this all working now? I fixed the deprecated errors in 0.8 as well.

**Comment by collse** [comment]
it is Steve - thanks

**Comment by twrecked** [comment]
Thanks for the update.

It's just somebody else is seeing a similar issue so I'm trying to get as much information as possible.
