### ISSUE TITLE
TEMP_CELSIUS will be deprecated next year

### ISSUE THREAD

**Issue by shupershuff** [twrecked/hass-aarlo#872]
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 23 January 2024 at 18:15:39 (2 occurrences)
Last logged: 23 January 2024 at 18:15:40

TEMP_CELSIUS was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment]
It's fixed in the alpha-11 branch.
