### ISSUE TITLE
2 Deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by Flifette** [twrecked/hass-aarlo#874]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1194
Integration: Lumière ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 16:57:48 (3 occurrences)
Last logged: 16:57:48

Entity None (<class 'custom_components.aarlo.light.ArloNightLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT|19: 23> and color modes, please create a bug report at https://github.com/twrecked/hass-aarlo/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity None (<class 'custom_components.aarlo.light.ArloSpotlight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 1> and color modes, please create a bug report at https://github.com/twrecked/hass-aarlo/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

AND 

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 16:57:48 (1 occurrences)
Last logged: 16:57:48

Entity None (<class 'custom_components.aarlo.media_player.ArloMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|PLAY_MEDIA|PLAY|SHUFFLE_SET: 49725>, please create a bug report at https://github.com/twrecked/hass-aarlo/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by umbex** [comment]
HI, adding these deprecations as well:


Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:205
Integration: Alarm Control Panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 12:56:29 (4 occurrences)
Last logged: 12:56:29

FORMAT_NUMBER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
FORMAT_TEXT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.TEXT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

Logger: homeassistant.components.alarm_control_panel.const
Source: helpers/deprecation.py:205
Integration: Alarm Control Panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 12:56:29 (4 occurrences)
Last logged: 12:56:29

SUPPORT_ALARM_ARM_AWAY was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_ARM_HOME was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_ARM_NIGHT was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
SUPPORT_ALARM_TRIGGER was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment]
Should be fixed in 0.8
