### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by unecc** [twrecked/hass-aarlo#877]
Hi to all, aarlo, after update ask me to remove -platform

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/2208e444-d5a6-4535-a585-dbc878f91751)

So i've to remove all part of

camera:
  platform: aarlo

or only - platform: aarlo?

it will be 
camera:

hass give me error for rebooting 
Avvisi di configurazione
Invalid config for 'binary_sensor' at configuration.yaml, line 56: required key 'platform' not provided
Invalid config for 'switch' at configuration.yaml, line 62: required key 'platform' not provided
Invalid config for 'alarm_control_panel' at configuration.yaml, line 31: required key 'platform' not provided

**Comment by unecc** [comment]
Please help me

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/6dce6302-d8dd-4887-b4bd-37070f95e5fd)
![image](https://github.com/twrecked/hass-aarlo/assets/134554559/0d58380e-62cf-41f9-aeb1-0ee946f49bda)


aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  tfa_host: 'imap.gmail.com'
  tfa_username: !secret GV_USER
  tfa_password: !secret GV_PASS 


alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
#    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8

camera:
  - platform: aarlo
  
media_player:
  platform: aarlo

sensor:
  - platform: aarlo
    monitored_conditions:
      - total_cameras
      - last_capture
      - recent_activity
      - captured_today
      - battery_level
      - signal_strength
#      - object_type #forse non funziona
#      - object_region #forse non funziona

binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - ding
#      - connectivity
switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10

**Comment by twrecked** [comment]
This is basic Home Assistant config stuff and not Arlo specific. You don't need those entries they are now kept in the integration settings.

Try commenting them out. You can do one section at a time if you want. Something like this:

```yaml
#aarlo:
#  host: https://my.arlo.com/
#  username: !secret arlo_username
#  password: !secret arlo_password
#  mqtt_host: mqtt-cluster-z1.arloxcld.com
#  tfa_host: 'imap.gmail.com'
#  tfa_username: !secret GV_USER
#  tfa_password: !secret GV_PASS

#switch:
# platform: aarlo
#  siren: True
#  all_sirens: True
#  snapshot: True
#  doorbell_silence: True
#  siren_volume: 1
#  siren_duration: 10
```

You can also make sure the config is correct by checking `Developer Tools -> YAML -> Check Configuration`.

**Comment by unecc** [comment]
Tanks very much now i've no errors and arlo camera works. but i've an other problem NEVER SOLVED.
When i want ARM (and DISARM) ARLO with aarlo integration, i click but nothing happens

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/19a5951f-bda9-476c-b6e5-26408aaa177c)





THIS IS RIGHT AND WORKS

aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  tfa_host: 'imap.gmail.com'
  tfa_username: !secret GV_USER
  tfa_password: !secret GV_PASS

**Comment by twrecked** [comment]
I'm going to need logs for that one. 

See [here](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#verbose-debug) to turn on verbose debugging and [here](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#online) on how to encrypt it.

**Comment by unecc** [comment]
It's really difficut for me because my english is really poor and translation is bad for my motherlanguage.

Can help these pictures?

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/64ef0930-e4f2-4cd5-b578-9d68af79031d)
![image](https://github.com/twrecked/hass-aarlo/assets/134554559/43ef11f6-11bd-4352-a2bc-3bbf1442c233)

**Comment by unecc** [comment]
aarlo change STATUS when i activate it from arlo app 
![image](https://github.com/twrecked/hass-aarlo/assets/134554559/5517afac-cad0-40e4-8441-34b18956f3c9)

i can ONLY disarm from home assistant aarlo.

i can't ACTIVATE IT!

**Comment by twrecked** [comment]
Good to hear!

Sorry for not replying quicker but my "real" job needed attention.

**Comment by unecc** [comment]
don't worry twrecked you are always gentle.

I've create a boolean switch with 2 scripts (arm /disarm) and used states of panel
