### ISSUE TITLE
no sensors after upgrade to 0.8.1, no config screens other than arm/disarm

### ISSUE THREAD

**Issue by colesadam** [twrecked/hass-aarlo#878]
Did fresh install of 0.7.4.2 after being unable to get past cloudflare issue in 0.8.1, minimal authentication/2fa setup and then upgraded to 0.8.1. Cameras and base stations all imported but no sensors created. According to docs these sensors should now be set up in integration configuration screens but this is all I get when I click on configure button?

![image](https://github.com/twrecked/hass-aarlo/assets/7858928/88395185-ff12-49a5-baba-0380b58c8eca)

**Comment by twrecked** [comment]
And if you click `submit`?

**Comment by colesadam** [comment]
well duh :) Maybe I expected a continue button or next or something.

**Comment by twrecked** [comment]
I hear you. This piece is controlled by _Home Assistant_ and I find it a little confusing in places. If I get time I'll try and see what I can do but I think other components work the same.

I hope all the sensors work now.

**Comment by colesadam** [comment]
They do thanks @twrecked :)
