### ISSUE TITLE
Lovelace module aarlo-glance.js broken in release v0.5

### ISSUE THREAD

**Issue by jxlarrea** [twrecked/hass-aarlo#89]
Something broke the Lovelace card module in release v0.5. 

Thumbnails do show up but when attempting to start a stream, nothing happens. On desktop, the timer shows as 0:00 and no playback occurs, only displaying the thumbnail.  On mobile, a broken image placeholder shows up on top of the thumbnail and no playback occurs. 

https://i.imgur.com/hy3KllY.png

https://i.imgur.com/SrIU3ci.png

When refreshing the the HA interface (F5) the status of the cameras do show up as "Streaming".

**Comment by twrecked** [comment]
I shall take a look here. Any logs coming out?

**Comment by jxlarrea** [comment]
@twrecked 

`https://xxxxxx.xxx/local/aarlo-glance.js?v=0.6:745:17 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "aarlo-glance" has already been used with this registry`

**Comment by twrecked** [comment]
It's to do with the litElement upgrades. The `_didRender` method has been deprecated.

Can you try this card file - with the `.txt` extension removed.

[aarlo-glance.js.txt](https://github.com/twrecked/hass-aarlo/files/3395147/aarlo-glance.js.txt)

**Comment by jxlarrea** [comment]
Yep, that card worked properly.

**Comment by twrecked** [comment]
Thanks, I'll regenerate 0.5...

**Comment by twrecked** [comment]
Fixed and release updated.
