### ISSUE TITLE
Doorbell camera not visible

### ISSUE THREAD

**Issue by chicknlil** [twrecked/hass-aarlo#891]
Hey there!

Running v0.8.1.a11, and it seems to be going smoothly, but I'm having one strange little issue as I add new Arlo devices to my system (I'm consolidating from several brands to just Arlo). I just added an Arlo Video Doorbell 2K (2nd Gen- AVD4001)​, and while I've got a bunch of sensors available, I don't have the camera.

![image](https://github.com/twrecked/hass-aarlo/assets/100124187/cbe0a03d-f0ce-45e9-bb74-a2e5ddbfa6c1)

Camera has detected motion for sure (thank you neighbors going back and forth to their car) but yeah, nothing in HA.

Much obliged to any tips/suggestions you can offer!

**Comment by twrecked** [comment]
I need to add camera support for it. With doorbells you need to tell them they have camera support.

You might not have a base station for it as well. Does it connect directly to the wifi?

**Comment by chicknlil** [comment]
> I need to add camera support for it. With doorbells you need to tell them they have camera support.
> 
> You might not have a base station for it as well. Does it connect directly to the wifi?

It connects directly to wifi, yes.

Is there anything I can do to help you with the camera support? You will probably need to direct me how to get the information you need, but I'd be happy to do so.

**Comment by twrecked** [comment]
This should be working on the latest 0.8 build.

**Comment by chicknlil** [comment]
Yep, this is working as expected now, thank you!
