### ISSUE TITLE
TEMP_CELSIUS was used from aarlo,

### ISSUE THREAD

**Issue by clinds34** [twrecked/hass-aarlo#896]
FYI - This is a new warning coming up in my logs...guess there is some time to fix but thought I would log it. 

WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from aarlo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment]
Should be fixed in 0.7 and 0.8
