### ISSUE TITLE
Deprecated helper to stop working in 2024.9

### ISSUE THREAD

**Issue by clinds34** [twrecked/hass-aarlo#897]
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/aarlo/camera.py, line 315: hass.components.websocket_api.async_register_command(, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by twrecked** [comment]
Should be fixed in 0.7 and 0.8
