### ISSUE TITLE
Turning Cameras Off Individually

### ISSUE THREAD

**Issue by dforsyth-xag** [twrecked/hass-aarlo#898]
Hi Steve, 

This is more a feature question or request (is there a better place to put these?).

I'd like to have a set of buttons on one of my dashboards that toggles turning each individual camera on and off (or disable/enable). Is this possible in the current build?

I know I can change the mode, just wondering if you can do so at an individual level. 

Cheers in advance

**Comment by twrecked** [comment]
These should work:
  https://www.home-assistant.io/integrations/camera/#service-turn_off
  https://www.home-assistant.io/integrations/camera/#service-turn_on

**Comment by dforsyth-xag** [comment]
Works like a charm - as always, thanks Steve!
