### ISSUE TITLE
I can’t get the new version installed

### ISSUE THREAD

**Issue by middelkoopmail** [twrecked/hass-aarlo#899]
I am not the most technical guy, already excuses if i have dumb questions.

I tried installing the 0.8

In the configuration screen
- in the first 2 fields, i added the username and password for Arlo.com website (i checked with a browser, they are correct)

In the 2fa fields, i filled the email address of a gmail account where the 2fa is getting in
I filled the app password from gmail for this account (removed the spaces from the pwd)

- The 2fa is sending an email to a separate gmail account (i checked, and the email from Arlo arrives with a 6 digit code in it)

I filled in imap.gmail.com in the last field.

After pressing submit: it takes a loong time (like 5 minutes) before the screen is back, and says: Success.
But directly the entry which it creates in the overview of Aarlo, is red. And says: 
Needs attention, Aarlo for ‘’correct emailadres’’. No devices or entities. 
Red examination marker and message: Failed to setup

I also get an error message notification in home assistant, see below.
Any clue?

Error: general-error=gaierror
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyaarlo/backend.py", line 526, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/socket.py", line 828, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart

**Comment by twrecked** [comment]
Try the `sse` backend.

Create or modify `aarlo.yaml`, it should be in the same directory as your main _Home Assistant_ configuration.:

```yaml
version: 1
aarlo:
  ... keep your original config if it has some
  backend: sse
```

**Comment by middelkoopmail** [comment]
@twrecked Hi Steve, that worked, thanks!

is there also some documentation or forum, where i can find out how i can:
- when the doorbell sees motion -> start recording for 1 minute
Does it record than to the standard Arlo (website), or can i point it to a local storage in my home assistant (in fact, bypassing the Arlo monthly subscription)

**Comment by hufkens** [comment]
I have the same issue and followed most of the fixes here but I still het the error:

`socket.gaierror: [Errno -2] Name does not resolve`

I have added the `/homeassistant/aarlo.yaml` file and it contains

```
version: 1
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: push
  tfa_type: push
  backend: sse
  mqtt_host: mqtt-cluster-z1.arloxcld.com
```

I added the last entry because I also found that here. Any ideas?
