### ISSUE TITLE
Base Station doesn't change state

### ISSUE THREAD

**Issue by Chief-NL** [twrecked/hass-aarlo#906]
Since yesterday morning, my Arlo buttons do not update anymore and do not show the correct state of my Base Station and doorbell. However, the automations are still switching the alarm from "Disarmed" to "Away" and back as they should, I can see them turned on or off in the Arlo app. 

Nothing is reporting any issues or malfunction as far as I can see. Anyone have any idea?

![image](https://github.com/twrecked/hass-aarlo/assets/156446441/41b67ba1-61e7-4dde-bad9-b657b5f79632)

**Comment by tanderson1973** [comment]
What was the fix?
