### ISSUE TITLE
No Cameras Appearing - 1.5.1

### ISSUE THREAD

**Issue by jarrah31** [twrecked/hass-aarlo#91]
It may be something I've done, but after a couple of months without an Arlo camera, I resurrected my aarlo setup to use a new Arlo Q camera last night. Unfortunately no camera entity is appearing in HA, and after enabling packet_dump, all I see in the log file is:
```
$ cat packets.dump
{'status': 'connected'}
{'status': 'connected'}
```
The only entity I have is:
![image](https://user-images.githubusercontent.com/3072303/61387965-08afe880-a8af-11e9-9196-47667ea94c0a.png)

I had previously removed the aarlo entries in custom_components so it was a fresh install. Seeing the message about using 1.5.1, I did the following in my old hass-aarlo repo:
```
$ git pull
$ git fetch origin tag v0.5.1
$ git describe --tags
v0.5.1-6-g9a54fee
$ ./install go /home/user/docker/homeassistant

Have I used the right version? I'll try the older 0.4 this evening as well.

Thanks.

**Comment by twrecked** [comment]
Turn on some debug too. That will really let you know what's happening: Add this to configuration.yaml:

``` yaml
logger:
  default: info
  logs:
    pyaarlo: debug
```

**Comment by jarrah31** [comment]
ahh thanks, i had tried the following because I couldn't find any info on debugging in the repo.
```
custom_components.aarlo: debug
```
will try pyaarlo instead.

**Comment by jarrah31** [comment]
doh, looks like I was using an old account! Sorry about that, I didn't update my secrets file with the new details... :)
