### ISSUE TITLE
Problem with OS 12.1 / SV 2024.04.0 / Core 2024.4.2

### ISSUE THREAD

**Issue by Victor0815** [twrecked/hass-aarlo#911]
I have some problems in Operation System 12.1 after the Update today

![image](https://github.com/twrecked/hass-aarlo/assets/32401917/13922251-6cb5-4e04-aa85-01d1d07c4023)

![image](https://github.com/twrecked/hass-aarlo/assets/32401917/1415bcbd-ed34-4c8b-af45-26be2170c5c4)

**Comment by twrecked** [comment]
Can you try the fix here: #871
