### ISSUE TITLE
Integration broke after updating Home Assistant to 2024.4.2

### ISSUE THREAD

**Issue by jincollingo** [twrecked/hass-aarlo#912]
Some log entries:

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:716
integration: aarlo ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 8:24:14 PM (3046 occurrences)
Last logged: 9:31:42 PM

general-error=gaierror Traceback (most recent call last): File "/config/custom_components/aarlo/pyaarlo/backend.py", line 497, in _mqtt_main self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60) File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 914, in connect return self.reconnect() ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1044, in reconnect sock = self._create_socket_connection() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/socket.py", line 828, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ socket.gaierror: [Errno -2] Name does not resolve

**Comment by Mosshill** [comment]
Haves the same issue although I rolled back and it same with last backup as well.

Error: general-error=gaierror
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 497, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/socket.py", line 828, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart.

**Comment by Mosshill** [comment]
Looking at issues reported in  [#904] so removed the old 0.7 integration from HAC's. 
Then also edited my /homeassistant/configuration.yaml  and remove all my aarlo login and setup from this.
In /homeassistant/scenes.yaml removed any aarol item I had created.
Reboot and was no longer getting issues.

Using the info in [#871] created the aarlo.yaml and added the backend info.
Used HAC and installed the a 0.8 version, then added this integration the usual way via devices and services, filled in the data.

user - arlo user
password  - arlo.ha passsword
type -imap

tfa_host: imap.gmail.com:993
tfa_username: xxxxxxxx@gmail.com
tfa_password: app password

Back working.....

**Comment by jincollingo** [comment]
Answered here --> https://github.com/twrecked/hass-aarlo/issues/904#issuecomment-2045240527

Simply add the line "backend: sse" in the aarlo section of your configuration.yaml if running version 0.7

Thanks!
