### ISSUE TITLE
Binary_sensor.aarlo_motion_* stuck to "Clear"

### ISSUE THREAD

**Issue by Beppuz81** [twrecked/hass-aarlo#913]
Hi, I use hass-arlo integration (version 0.8.1.beta.14) with 20 cameras synced with three different hubs connected to my network.
The integration with HomeAssistant works and I can view all the cameras, arm/disarm the alarms, read the battery and the signal level of each camera.

I have only one problem: **HomeAssistant can't see any changes of the binary_sensor.aarlo_motion_*** . 

All the camera's motion sensors are stuck to "Clear" even if I walk in front of them. 

This means that I cannot use these sensors to create automations with HomeAssistant and I must use Arlo APP to set the behaviour of the alarm. In this way, if I arm Arlo through HomeAssistant or with Arlo App and I walk in front of the camera, the alarm is triggered and the sirens work. 

What can I do to solve this problem?

**Comment by twrecked** [comment]
Sorry, just to clarify. You aren't seeing motion detection unless you arm the alarms?

**Comment by Beppuz81** [comment]
No, I can't see any changes of the motion binary sensors at all in Home Assistant

**Comment by twrecked** [comment]
Can you upgrade to _b15_.  It fixes back end detection. If you have modified `aarlo.yaml` can you comment out the following values if set:

```
    #backend: sse
    #mqtt_hostname_check: false
```

If that doesn't work. Can you check the following:

- Make sure your _Home Assistant_ _Arlo_ account has admin access enabled.
- Stop _Home Assistant_ temporarily and log in to the _Arlo_ [website](https://my.arlo.com/#/home) using your _Home Assistant Arlo_ account and see if you get motion detection notifications on that.

**Comment by Beppuz81** [comment]
Thank you @twrecked. 
I solved commenting backend: sse in the aarlo.yaml file. 
Now everything works!
