### ISSUE TITLE
aarlo Component Setup Error

### ISSUE THREAD

**Issue by jacoqq** [twrecked/hass-aarlo#914]
Hi, 
After last update (2024.4.3) my arlo integration stop working. I've got something like this in notifications:

> Error: general-error=gaierror
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 497, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/socket.py", line 828, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve
If error persists you might need to change config and restart.
> 

> The following integrations and platforms could not be set up:
    [aarlo](https://github.com/twrecked/hass-aarlo/blob/master/README.md) ([Show logs](https://huta3.pl/config/logs?filter=aarlo))
    aarlo.binary_sensor ([Show logs](https://huta3.pl/config/logs?filter=aarlo.binary_sensor))
    aarlo.sensor ([Show logs](https://huta3.pl/config/logs?filter=aarlo.sensor))
    aarlo.switch ([Show logs](https://huta3.pl/config/logs?filter=aarlo.switch))
    aarlo.media_player ([Show logs](https://huta3.pl/config/logs?filter=aarlo.media_player))
    aarlo.camera ([Show logs](https://huta3.pl/config/logs?filter=aarlo.camera))
Please check your config and [logs](https://huta3.pl/config/logs).

> 

I'm not sure what he want from me. 
Can someone please help ?

**Comment by dgoodman036** [comment]
I had same issue, came across this fix by @collse , so added backend: see and reloaded, all working now! thanks.

**Comment by jacoqq** [comment]
Yes, working now. I owe you a beer :)

**Comment by twrecked** [comment]
This error has popped up a lot. Would anybody be willing to try the _b15_ release and see if it fixes their original issue. I recently noticed that _Arlo_ will tell me the host name and type of server to connect to for events, this code will use that information if you set `backend` to `auto`. 

If anyone is feeling brave, update to _b15_, comment out these lines from `aarlo.yaml` and restart _Home Assistant_.

```
    #backend: sse
    #mqtt_hostname_check: false
```

If you turn on `pyaarlo` debugging you will see a message like this telling you what the software is trying to do:

```
2024-04-21 10:21:18.119 DEBUG (SyncWorker_6) [pyaarlo] back=mqtt;url=mqtt-cluster-z1.arloxcld.com:8883
```

Interestingly, if you remove the `user_agent` it uses MQTT, if you set `user_agent` to `linux` it uses SSE.
