### ISSUE TITLE
Deprecated in Home Assistant Core 2025.3

### ISSUE THREAD

**Issue by adnansarajlic** [twrecked/hass-aarlo#918]
Logger: homeassistant.components.light
Källa: components/light/__init__.py:917
integration: Lampa (dokumentation, ärenden)
Inträffade först: 21:18:28 (1 händelser)
Senast loggade: 21:18:28

light.aarlo_kamera (<class 'custom_components.aarlo.light.ArloSpotlight'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/twrecked/hass-aarlo/issues

**Comment by MankiniChykan** [comment]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1272
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: April 28, 2024 at 17:44:52 (13 occurrences)
Last logged: April 28, 2024 at 17:44:58

None (<class 'custom_components.aarlo.light.ArloNightLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
None (<class 'custom_components.aarlo.light.ArloSpotlight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
None (<class 'custom_components.aarlo.light.ArloFloodLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/twrecked/hass-aarlo/issues
None (<class 'custom_components.localtuya.light.LocaltuyaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/rospogrigio/localtuya/issues

**Comment by twrecked** [comment]
They are fixed in 0.8 which will be taken out of beta soon.
