### ISSUE TITLE
Installation Arlo/Aarlo doen't work

### ISSUE THREAD

**Issue by Steafn14** [twrecked/hass-aarlo#920]
Hello - I'm Stefan and brand new in the Home-Assistand / GitHub community.
I have added add home, after shot down from Gigaset system the new Home-Assitant.
All components are working fine and I was able to add different devices from different suppliers to HA.

What doesn't work is the set-up for "Arlo".
I have downloaded the actual version  v0.81.b15 - using the iPhone virtual interface to implement in HA.
Installation from "app" works fine, but when I come to the step , enter the mail address it doesn't work.
Normally I use the gmx mailaccount  and password to sign in to Arlo app. I have added the 2fa in the Arlo app and set up an Gmail adresse and opened a 2nd Arlo account with own password for login. 
Now I come to the point, where I didn't understand what I'm doing wrong, what's the problem and would be great if someone can support.

Thanks in advance

Stefan

**Comment by twrecked** [comment]
Firstly, can you log into your _Arlo_ account on the official [Arlo website](https://my.arlo.com/#/home) using your _Home Assistant_ account.

- Are the cameras you have shared appearing?
- Make sure you have an email address set up for 2fa. Go to `Settings -> Profile -> Two Step Verification`. Make sure you have an email address set up for verification. I use the one I login with.

**Comment by twrecked** [comment]
You need a separate account use Arlo in Home Assistant. You need to share the cameras you want to use in Home Assistant with that account. This is an Arlo limitation. For example, for me I might have these accounts:

joe.public@gmail.com; I use with the Arlo app on my phone.
joe.public+ha@gmail.com; I use this account to login to home assistant.

When I log into the Arlo with `joe.public@gmail.com` I go to `Settings -> Grant Access` to the cameras I want to share with `joe.public+ha@gmail.com`.

When I say login to the Arlo website with the Home Assistant account I mean I use `joe.public+ha@gmail.com`.

**Comment by Steafn14** [comment]
Sorry for disturbing

That’s the setting I use
@gmx is the normal standard account and @gmail the one I use for HA.
GMX allowed full access to gmail account


And I have installed: v0.8.1.b15
So I do not know what to do.


Steve Herrell ***@***.***> schrieb am Fr. 26. Apr. 2024 um
15:05:

**Comment by twrecked** [comment]
And when you login to Arlo with the gmail account; what do you see?

**Comment by Steafn14** [comment]
I can see the full screen with 5 cameras, but not the base station
In the setting I see - GMX is use for 2fa but I can not give control from
gmail account to GMX account - it is just a „friend“ how has access

Steve Herrell ***@***.***> schrieb am Fr. 26. Apr. 2024 um
18:32:

**Comment by Steafn14** [comment]
And also same error message I get - 2fa startup failed:(

stefan schulter ***@***.***> schrieb am Fr. 26. Apr. 2024
um 18:35:

**Comment by twrecked** [comment]
To get the base stations you need to give the shared account admin access.

As for the config. Delete and recreate the integration:

Username: the gmail address
Password: the password for the Arlo account

2fa type: imap
2fa host: your gmx imap server
2fa username: your gmx email address
2fa password: your gmx password

**Comment by Steafn14** [comment]
Perfect - now it worked - so now I have just to implement the function to
get the video shown - thanks for the great support!!!
(Give me a hint, when you know what I want tondo :) )

Steve Herrell ***@***.***> schrieb am Fr. 26. Apr. 2024 um
19:38:

**Comment by verocauto** [comment]
Please i need help i'm having the same problem
