### ISSUE TITLE
Add list of supported devices

### ISSUE THREAD

**Issue by jangerbauer** [twrecked/hass-aarlo#921]
Logging this as an issue, however it is really more of a request.

Would it be possible to provide a list of supported devices?  The documentation states that "base stations, cameras, lights and doorbells" are supported, however does that include _all_ types and versions of these devices?  For example, are both wired and wireless cameras supported?  Asking because I own Arlo Pro 4 wireless cameras -- I don't want to start down the path of installing this integration, only to find out my cameras are not supported.  Appreciate any thoughts or consideration to this request.

**Comment by collse** [comment]
I seem to remember that may have existed in the past but. I am not 100% sure - but pretty much all devices as their subclass are supported and if not @twrecked can help to support it - obviously he doesnt own all devices so it is difficult to test.

on testing it out - it is a pretty straight forward process, doesnt take long to configure and you will see if all your devices are supported or not and if not supply information of what isnt and @twrecked helps sorting it out - like he did with my Arla Baby back in the days

**Comment by twrecked** [comment]
To add to/clarify to what @collse said.

We've never really had a list of supported devices. The way the web interfaces works is everything is presented to us as either a camera or base station or alarm but the API to use the individual cameras are identical. What does change is features available per camera - does it have a light, a siren etc... so I sometimes have to alter the code for that.

But if you can use a device on the official web site you can use it inside the integration.

**Comment by jangerbauer** [comment]
Thanks all for the visibility on this.  Will close this out as answered / resolved.

**Comment by twrecked** [comment]
I've been working on tidying the docs and this seemed like something I could add.

https://github.com/twrecked/hass-aarlo/tree/doc-updates#supported-devices

I need double check the names and to flesh out the notes piece but I think the list is mostly complete.

**Comment by jangerbauer** [comment]
This look great!  I think this will be super helpful for anyone interested in implementing this component.
