### ISSUE TITLE
Running the remove_old script

### ISSUE THREAD

**Issue by codypet** [twrecked/hass-aarlo#93]
How do I go about running the remove_old script if I want to migrate over to HACS?  I really don't want to mess things up.  I had previously installed the old version of Aarlo manually?  Could I just delete the old custom components and be good?

**Comment by twrecked** [comment]
Yes. You can delete the `custom_components/aarlo` directory by hand. You could also rename it.

**Comment by twrecked** [comment]
Closing because I answered the question. I'm assuming everything is working well.
