### ISSUE TITLE
Custom Aarlo Glance Card Broken After 0.8 Update

### ISSUE THREAD

**Issue by M3Power95** [twrecked/hass-aarlo#934]
Upon completing the transition from 0.7.4.2 to 0.8.1, the custom:aarlo-glance-card card stopped working. In addition, I couldn't find the battery status entity anymore that I was using for other dashboard items. Reverted back to the traditional setup for now. 

My setup: Hosting a HAOS vm on Proxmox:

HAOS Core 2024.5.0
Supervisor 2024.04.4
OS 12.2
Frontend 20240501.0

Glance code that broke: 

type: custom:aarlo-glance
entity: camera.my_arlo_camera
name: Arlo Left Front
show:
  - motion
  - sound
  - library
  - snapshot
  - battery level
  - signal_strength
  - capture_today
  - image_date
top_title: true
top_status: true
top_date: true
image_click: play

I think the new integration took away some of the sensors listed above that were setup in my config.yaml but I'm not sure how or if I could re-use whatever new entity or sensor in this custom glance card with the new way it's integrated, so please pardon my ignorance. I am new to HA.

**Comment by twrecked** [comment]
It really shouldn't have removed any of the sensors. I'm guessing it failed to login.

Can you paste the contents of `aarlo.yaml` here.

**Comment by M3Power95** [comment]
> It really shouldn't have removed any of the sensors. I'm guessing it failed to login.
> 
> Can you paste the contents of `aarlo.yaml` here.

Does that get created on the update, so I'd have to retry it? Don't have an aarlo.yaml initially in my config directory now that I've reverted back.

**Comment by M3Power95** [comment]
> It really shouldn't have removed any of the sensors. I'm guessing it failed to login.
> 
> Can you paste the contents of `aarlo.yaml` here.

I think I may have actually just fixed my own issue. Did the update again, and everything seems to work. However I was getting repair noticed for unused yaml configurations. Basically it's the old aarlo code in my config.yaml file that it's telling me to get rid of. I actually just commented those items out so the notices would go away. This time I didn't do that, and everything seems to be working. Attached a picture of the repair notices I'm getting from HA.


![Aarlo Config](https://github.com/twrecked/hass-aarlo/assets/166347006/7fd1dea8-0c56-4c36-9d6f-e238d58d5bb3)

**Comment by twrecked** [comment]
The repair notices are a warning. It's because the integration doesn't use the configuration in the yaml files any more, it has been move into the `.storage` directory. It's safe to ignore but I would comment them out for now and delete them later when everything looks good.

As to why it didn't work, I think maybe it didn't login. I have an idea how to fix that on an upgrade, I might have to trash the saved credentials. 

Glad it's working now. You should be able to see all your devices grouped on the Integrations --> Aarlo page now. And you should have an `aarlo.yaml` file now. It's where all the stranger Aarlo configuration has to go.

**Comment by M3Power95** [comment]
> As to why it didn't work, I think maybe it didn't login. I have an idea how to fix that on an upgrade, I might have to trash the saved credentials.
> 
> Glad it's working now. You should be able to see all your devices grouped on the Integrations --> Aarlo page now.

Yea so I commented it out this time and everything seems to be working. So weird because I literally tried this update about 5 time last night, and each time it broke the glance card. So maybe you're right about the login, because I didn't do anything differently this time around I don't think. 

If you trash the saved credentials for future updates, will we have to log back in when we install an update? Noticed that restoring backups breaks some other integrations I have, and it's typically the authentication tokens.

In any case, thank you for your help, and all you do to make this work!

**Comment by twrecked** [comment]
You won't notice if I delete the session details - it happens automatically after 2 weeks anyway. The integration has all the information it needs to login without bothering you. It just allows the integration to bypass the cloud flare stuff as much as possible.
