### ISSUE TITLE
Essential Indoor Gen 2 not visible

### ISSUE THREAD

**Issue by AndreaCCIE** [twrecked/hass-aarlo#935]
Hi there, as you might already know, the Essential Indoor Camera Gen 2 (VMC3060) does not show up in the integration.
In the beginning, I thought it was because these cameras don't connect to the Smart Hub (VMB5000) yet, but then I noticed that my doorbell Gen 2 (AVD3001A) doesn't connect as well, but it's in the integration and works as expected.

**Comment by twrecked** [comment]
There is no reason it doesn't show up. _Arlo_ sends the integration a list of cameras and we use them without checking the model numbers.

Can you make sure you've shared the camera? Does it appear on the _Arlo_ web page when you use your _Home Assistant_ account on it?

If not, can you turn on debug and capture it for me?

**Comment by AndreaCCIE** [comment]
Sorry, I’m stupid 😂

**Comment by twrecked** [comment]
No you're not. This thing has a lot of moving parts to it. Glad it working now.

Do those cameras support siren or have audio detection? I'm probably not fulling supporting them just yet.

**Comment by AndreaCCIE** [comment]
Strangely, I replaced the Gen 1 doorbell with the Gen 2, and it was shared automatically in the Arlo app. That's why I completely forgot about that.
The new cameras have audio and sirens. It's not a big deal to me if not supported, as I have an MQTT switch controlling a more powerful siren. Here's what's exposed in the integration:

![Screenshot 2024-05-04 at 10 51 20](https://github.com/twrecked/hass-aarlo/assets/48698293/50cc8bf2-983e-4e7d-8686-edafa1c3e98e)

**Comment by twrecked** [comment]
I never use the sirens but some one might... one more question:

Does it have a battery, the gen 1 didn't?

**Comment by AndreaCCIE** [comment]
If you are talking about the Essential Indoor, it doesn't have a battery while the Essential Outdoor does. Both doorbells, 1st and 2nd Gen, have a battery, but mines are constantly pugged to the 16V.

https://www.arlo.com/en_gb/essential-range
