### ISSUE TITLE
Way to save media in new update?

### ISSUE THREAD

**Issue by tenumars** [twrecked/hass-aarlo#940]
Hello,

In the old 0.7.x versions, there was an availability to configure a path to save recordings to. I do not see that in the new 0.8 version. Is there a way to add it in the config.yml file or some other way? thanks.

**Comment by twrecked** [comment]
Yes. Look at `/config/arlo.yaml`, it should be created on upgrade, and add it there.

https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#coming-from-earlier-versions
https://github.com/twrecked/hass-aarlo/blob/master/README-advanced.md#saving-media
