### ISSUE TITLE
Error Streaming AARLO-GLANCE

### ISSUE THREAD

**Issue by Gianni2020** [twrecked/hass-aarlo#943]
ARLO Integration V. 0.8.1.2
Registratore: homeassistant.components.stream.stream.camera.aarlo_XXXXX
Fonte: components/stream/__init__.py:448
Integrazione: Stream (documentazione, problemi)
Prima occorrenza: 11:30:43 (14 occorrenze)
Ultima registrazione: 11:52:24

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsps://arlostreaming………

**Comment by twrecked** [comment]
What is in your `/config/aarlo.yaml` file.

What is your card configuration?

**Comment by Gianni2020** [comment]
Thank you,
I solved it by restarting Arlo System

**Comment by twrecked** [comment]
Good to hear.
