### ISSUE TITLE
Arlo HA cant get it to work

### ISSUE THREAD

**Issue by henrithiesen** [twrecked/hass-aarlo#952]
Hi tried remove backend: sse from my aarlo.yaml but dosent seem to fix it for me. Its broken since last update 0.8. 

Kind regards//Henri

**Comment by twrecked** [comment]
Can you post [some debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#enabling-debug) logs. I'll see what is going on.

**Comment by petepall** [comment]
@twrecked, yesterday I opened a ticket related to the Aarlo not working anymore. After you suggestion around the removal of the backend entry I now get Aarlo to work but it seems that now home assistant is rebooting every 10 minutes and I keep getting the following entry in the log:

2024-05-21 20:13:41.330 ERROR (ArloEventStream) [pyaarlo] general-error=HTTPError
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyaarlo/backend.py", line 593, in _sse_main
self._event_client = SSEClient(
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 55, in __init__
self._connect()
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 74, in _connect
self.resp.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe

**Comment by twrecked** [comment]
Away from computer. Look here for now:

https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#configuration

Maybe force it to mqtt

**Comment by petepall** [comment]
Followed your recommendation to force the MQTT and this seems to resolve the error.

# This forces the MQTT backend
  backend: mqtt
  # These might also be needed
  mqtt_hostname_check: false
  mqtt_host: mqtt-cluster-z1.arloxcld.com

**Comment by twrecked** [comment]
Glad it's working. The new version should be able to detect and choose the correct back end.
