### ISSUE TITLE
Entity camera.aarlo_xxx unavailible

### ISSUE THREAD

**Issue by compoundbow83** [twrecked/hass-aarlo#957]
hello,
I installed the Arlo integration via Hacs.

the configuration works fine and I see to devices in Home Assistant.

All entities work fine except the  camera.aarlo_xxx. This is not available.

This means I don't have a picture from my camera in Home Assistant.

What am I doing wrong?

**Comment by twrecked** [comment]
I'm not fully understanding the issue. Everything is working but one camera is missing?

First go onto [the Arlo webpage](https://my.arlo.com/#/home) with your _Home Assistant_ _Aarlo_ account and see if the camera is there.

What kind of camera is this? Did you give admin access to your _Home Assistant_ _Aarlo_ account

**Comment by compoundbow83** [comment]
Sorry, I expressed myself incorrectly. Both cameras are displayed as devices in the Home Assistant.

Entities such as: B. Battery, movement, etc. displayed correctly.

But no image is shown to me on both cameras

When I log in to the Arlo webpage or app, I can see both camera images.

They are both VMC4030.

**Comment by twrecked** [comment]
What are you using to display the camera?

**Comment by compoundbow83** [comment]
I can't use anything to view the camera because the camera entity is not available.

<img width="321" alt="Bildschirmfoto 2024-05-26 um 14 41 19" src="https://github.com/twrecked/hass-aarlo/assets/74456101/10a22076-b21c-42f6-aabf-d589ac41a4f9">

**Comment by twrecked** [comment]
I'm not sure what is going on here. We'll start with the camera status:

Go to `Developer Tools ->  STATES` and enter your camera name. Can you post the status here.

**Comment by compoundbow83** [comment]
here it is:

camera.aarlo_mini_teichMini Teich | unavailable | restored: true friendly_name: Mini Teich supported_features: 3
-- | -- | --

[camera.aarlo_mini_teich](http://homeassistant.local:8123/developer-tools/state#)
Mini Teich
unavailable	restored: true
friendly_name: Mini Teich
supported_features: 3

**Comment by twrecked** [comment]
I'm sorry but it's debug time.  Can you [enable debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#enabling-debug) and [encrypt it](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#encrypting-the-output) and attach it to this bug report.

**Comment by compoundbow83** [comment]
> I'm sorry but it's debug time. Can you [enable debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#enabling-debug) and [encrypt it](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#encrypting-the-output) and attach it to this bug report.

Hier the encrpted logs
[enrypted_log.txt](https://github.com/twrecked/hass-aarlo/files/15458292/enrypted_log.txt)

I hope this is what you need.

I see to errors in the logs regarding arlo:

Error adding entity camera.aarlo_mini_teich for domain camera with platform aarlo
Error adding entity camera.aarlo_hof for domain camera with platform aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1359, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/camera.py", line 502, in extra_state_attributes
    (ATTR_TIME_ZONE, self._camera.timezone),
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/device.py", line 331, in timezone
    return self.base_station.timezone
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timezone'



and 

Could not find any base stations for device Mini Teich
Could not find any base stations for device Hof


But in the Arlo App I can see both camera streams.

**Comment by twrecked** [comment]
This is familiar. 

Can I double check, you did check "Allow Access Rights" for the shared account? That is the normal reason the base station doesn't appear.

**Comment by compoundbow83** [comment]
This makes me really uncomfortable now. I thought I checked that. But unfortunately the setting was actually disabled.

Thank you

**Comment by twrecked** [comment]
Glad it's going! And it's not unheard of for _Arlo_ to forget some settings.
