### ISSUE TITLE
Custom element not found: aarlo_glance

### ISSUE THREAD

**Issue by adieball** [twrecked/hass-aarlo#958]
I tried everything I could find, including the tips from the issues here or the FAQ, no success. 
Installed aarlo and aarlo lovelance via HACS
aarlo itself is working fine.

/hacsfiles/lovelace-hass-aarlo/hass-aarlo.js?hacstag=1972451790261 in in the ressources

But when I add a custom card with:

```
type: custom:aarlo_glance
entity: camera.aarlo_garten
```

I just get back: `Custom element not found: aarlo_glance
`
Files installed at:

```
➜  ~ find / -name \*aarlo\*                                             
/homeassistant/.aarlo
/homeassistant/.aarlo/aarlo.pickle
/homeassistant/www/community/lovelace-hass-aarlo
/homeassistant/www/community/lovelace-hass-aarlo/hass-aarlo.js
/homeassistant/www/community/lovelace-hass-aarlo/hass-aarlo.js.gz
/homeassistant/custom_components/aarlo
```

**Comment by twrecked** [comment]
Can you try `type: custom:aarlo-glance`, note the hyphen not an underscore.

**Comment by adieball** [comment]
aaarrgghh, I'm an idiot, it was the underscore.
so sorry to bother you
