### ISSUE TITLE
Motion sensor status shown as unknown for the all in one sensors (MS1001), while the correct status shown in the debug logs

### ISSUE THREAD

**Issue by aviveis** [twrecked/hass-aarlo#960]
aarlo version: 0.8.1.2
HA versiob: 2024.5.5

Everything is connected and working properly (cameras, all in one sensors), except for the motion status shown for the all in one sensors - MS1001. The motion status for the cameras is shown correctly.

For example: Motion Kitchen Door Sensor (binary_sensor.aarlo_motion_kitchen_door_sensor) shown as Unknown.

However, when enabling debugging for Aarlo, the events are recorded properly:
2024-06-02 10:41:18.230 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.binary_sensor] callback:Motion Kitchen Door Sensor:motionState:True
2024-06-02 10:41:30.763 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.binary_sensor] callback:Motion Kitchen Door Sensor:motionState:False

**Comment by twrecked** [comment]
I can see the problem; the code isn't handing the event type correctly. I'll try a fix here.

**Comment by twrecked** [comment]
Should be fixed by #961 in the latest release.

**Comment by aviveis** [comment]
Thank you very much for the quick turnaround! Downloaded 0.8.1.3 and now I can see the motion sensor status
