### ISSUE TITLE
Alarm aarlo

### ISSUE THREAD

**Issue by pakystanoo** [twrecked/hass-aarlo#962]
I have a problem I can no longer activate the motion alarm
![Screenshot_20240606_235829_Home Assistant](https://github.com/twrecked/hass-aarlo/assets/169154452/f966c646-8edb-4d9e-92ac-651bcdf07a5e)

**Comment by twrecked** [comment]
Look at your Alarm setting - see [here](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#alarm-setting-screen).

You need to make sure the code value is `no code needed`. The reason I did this was because at the time I couldn't get it to accept a blank entry...

**Comment by HtownTexans** [comment]
> Look at your Alarm setting - see [here](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#alarm-setting-screen).
> 
> You need to make sure the code value is `no code needed`. The reason I did this was because at the time I couldn't get it to accept a blank entry...

I've done this but still get the same error.

**Comment by twrecked** [comment]
Ahhh... I really need to figure out how to make that first one blank and only allow the boxes if it's not blank.

Anyway; glad it's going.
