### ISSUE TITLE
 Arming requires a code but none was given for alarm_control_panel.aarlo

### ISSUE THREAD

**Issue by Spiff1** [twrecked/hass-aarlo#963]
Updated Homeassistant to Core: 2024.6.1: Supervisor 2024.06.0 Operating System: 12.3 and Aarlo 0.8.1.3
One of those upgrades has bricked the possibility to use the alarm panel together with Aarlo. My guess is Core 2024.6.1 is the cause. When trying to arm Arlo I get this error message:  Arming requires a code but none was given for alarm_control_panel.aarlo....
What code? and where do I enter it?

Not sure how to solve this, any suggestions?

Thanks
/Peter

**Comment by twrecked** [comment]
Can you check here #962 

You need to make sure the code is "no code needed" and uncheck the "code required" boxes.

Did you go from 0.7 aarlo to 0.8?

**Comment by Spiff1** [comment]
Thank you, how simple it was to fix. Now it works again. Thank you very much!

**Comment by twrecked** [comment]
Sorry it broke. 

Did you upgrade from 0.7 or was this from 0.8?

**Comment by Spiff1** [comment]
This time I upgraded from 0.8.1.2 (I think), I have used 0.8.x.x a while and it broke at the last update.
