### ISSUE TITLE
Since 2024.6.1: Arming requires a code but none was given for alarm_control_panel

### ISSUE THREAD

**Issue by Phoenix-DH** [twrecked/hass-aarlo#964]
Hi,

since updatimg HA to the latest version 2024.6.1 I hwt the following error:

Arming requires a code but none was given for alarm_control_panel.aarlo_buddy

I am not able to change the state anymore.

**Comment by Phoenix-DH** [comment]
OMG… after updsting, the checkboxes to need a code have been enabled automatically.

Unchecked… Working.

**Comment by unecc** [comment]
thanks works disabling it
