### ISSUE TITLE
Keeps disconnecting

### ISSUE THREAD

**Issue by Wes910** [twrecked/hass-aarlo#973]
I can get the setup up and running but it will shortly afterward become unavailable until I delete the integration and re-login

HA 2024.7.2
Arlo integration 0.8.1.4
arlo essential 2 cameras wifi and arlo secure

[arlo.txt](https://github.com/user-attachments/files/16197378/arlo.txt)

**Comment by twrecked** [comment]
You did find a bug in the reload code; which I will fix.

But what are you trying to do before that? I saw a lot of streams trying to be connected.

**Comment by Wes910** [comment]
I just set it up following this video https://www.youtube.com/watch?v=Z3kk5N7VaCM&lc=Ugz8Yur20CHSq0dKi9Z4AaABAg.A5lHMJE80W8A5oQdZ4_9iE

I ended up giving on the Arlo's and returned them and went with unifi cameras
