### ISSUE TITLE
Where is the password defined for the arlo account?

### ISSUE THREAD

**Issue by shupershuff** [twrecked/hass-aarlo#974]
I've enabled Debug mode to see why the username and PW is being refused.
To my surprise I found that the password in the log is different to what I have in secrets.yaml.

I also discovered from reading recent issues on this GitHub that config is now stored in aarlo.yaml instead of config.yaml so moved config there. Despite what I put into either aarlo.yaml or config.yaml, the password being used is a password I've long since changed that isn't stated in any of my .yaml files. So at the moment I have no idea where it's pulling the password from, hoping someone can help me!

There also doesn't seem to be anyway to edit the account details from the integration screen
![image](https://github.com/user-attachments/assets/e386c3ca-d0e5-4d59-bae6-6f5a61ad1186)

**Comment by shupershuff** [comment]
Didn't find out where the PW was stored or how to change it but deleting the Integration Entry and recreating it seemed to work.

**Comment by twrecked** [comment]
Sorry; was busy at work. For future reference, it's stored in `.storage/core.config_entries` and this is now handled by the Home Assistant integration.
