### ISSUE TITLE
2Fa error

### ISSUE THREAD

**Issue by unecc** [twrecked/hass-aarlo#982]
Hi i'm sure that user and password of ARLO and GMAIL IMAP are ok... but integration doesn't works. What's wrong?

![image](https://github.com/user-attachments/assets/ee79a275-a24c-44c8-8d94-faaf4f11b521)

Registratore: custom_components.aarlo
Fonte: custom_components/aarlo/__init__.py:442
Integrazione: Arlo Camera Support (documentazione, problemi)
Prima occorrenza: 17:02:43 (1 occorrenze)
Ultima registrazione: 17:02:43

unable to connect to Arlo: stopping retries, too may failures
---------------------------

Registratore: custom_components.aarlo
Fonte: custom_components/aarlo/__init__.py:422
Integrazione: Arlo Camera Support (documentazione, problemi)
Prima occorrenza: 17:02:43 (1 occorrenze)
Ultima registrazione: 17:02:43

unable to connect to Arlo: attempt=4,sleep=120,error=login failed: 2fa: startup failed
-----------------

Registratore: pyaarlo
Fonte: custom_components/aarlo/__init__.py:408
Integrazione: Arlo Camera Support (documentazione, problemi)
Prima occorrenza: 17:02:42 (5 occorrenze)
Ultima registrazione: 17:02:43

body-error=KeyError
error in new response={'meta': {'code': 400, 'error': 9204, 'message': 'Browser is not trusted'}}
imap connection failedb'[ALERT] Application-specific password required: https://support.google.com/accounts/answer/185833 (Failure)'
login failed: 2fa: startup failed

**Comment by twrecked** [comment]
It's telling you the issue; you need to use an application specific password. Follow the link it gives you.

**Comment by unecc** [comment]
thankyou twrecked. Solved
