### ISSUE TITLE
New Arlo App stops Home Assistant from Arming and Disarming Cameras

### ISSUE THREAD

**Issue by jeprice77** [twrecked/hass-aarlo#985]
I purchased 3 new Arlo cameras and when I set them up, the application said I needed to upgrade my account and app to the latest version.  I did that and now Home Assistant no longer works when trying to arm and disarm the cameras.  Everything worked fine before this, but it appears Arlo has changed something in my account such that Home Assistant no longer works.  I contacted Arlo to see how to revert back to the older app, but they informed me I cannot roll back once it's been updated.  They plan on pushing their new app globally at some point anyway.   It appears that only the arming and disarming is broken, signal strength, spotlights, motion detection, etc. all seem to be working fine.

**Comment by twrecked** [comment]
See [here](https://github.com/twrecked/hass-aarlo/issues/975#issuecomment-2257305928).

You get a new location entry that controls everything.

**Comment by jeprice77** [comment]
I found the other alarm panel control mentioned and I am able to arm/disarm all the cameras.  If I am reading the posts correctly, you can no longer arm/disarm a single camera?  The new control does all cameras at once.  I was previously able to arm/disarm particular cameras.
Thanks,

**Comment by twrecked** [comment]
You are reading the posts correctly. Arlo has stopped you controlling individual cameras.
