### ISSUE TITLE
One of nine cameras not showing up

### ISSUE THREAD

**Issue by Slapn** [twrecked/hass-aarlo#99]
Hiya.

So... I've got 9 Arlo cameras across three hubs, and two security lights, on their little hub thingummies.

All 9 cameras function on both the Arlo app and the website. I've stuck the aarlo integration on (initially v4 - now v5.1), and it's fantastic... APART from the fact that one camera simply refuses to turn up.

I've stuck debug logging on - and it looks to interrogate the list of devices. See attached. There's a camera not mentioned there - attached to the 'Snug Base Station' hub, and with a serial number 52M1837LAA5C7 - that doesn't look to be mentioned in the output at all. 

It's a bit of a mystery to me at the moment - have you any idea what might be going on?

[pyaarlo.txt](https://github.com/twrecked/hass-aarlo/files/3435258/pyaarlo.txt)
[arlo_cameras](https://user-images.githubusercontent.com/29757453/61944288-45f23580-af95-11e9-8cc7-253eaf5d52ee.png)

Best Regards,

Jules

**Comment by Slapn** [comment]
OK. My idiocy - for some reason, the camera wasn't marked as 'Grant Access' to Home Assistant. I'm betting that's the problem. I'll close this issue, and sorry for bothering you.

**Comment by twrecked** [comment]
No worries. And glad it was an easy fix!

**Comment by jayofdoom** [comment]
@JulesAKT thanks for posting your solution -- I just had this exact same problem! This is the reason my new cameras were missing from hass-aarlo.
