### ISSUE TITLE
v0.8.1.6 High battery drain with VMC2050A

### ISSUE THREAD

**Issue by Kolbi** [twrecked/hass-aarlo#992]
I expected with my VM2050A cameras high battery drain since version v0.8.1.6 - like 1% every 15 minutes.

Reverting to v0.8.1.5 didn't solved the issue for me. Curious because it was not an issue till I updated to v0.8.1.6....

 My other cameras VMC2030A are not affected.

Any idea how to help in finding the issue?

https://github.com/twrecked/hass-aarlo/issues/979

**Comment by twrecked** [comment]
I broke the back end, sorry. I'll take a look.

**Comment by Kolbi** [comment]
Is it possible that the issue is here: https://github.com/twrecked/pyaarlo/blob/master/pyaarlo/base.py#L21 that MODEL_ESSENTIAL_OUTDOOR_GEN2_HD is missing there?

**Comment by twrecked** [comment]
That's it! I missed that one.

**Comment by Kolbi** [comment]
Thanks a lot.

And now I also see why rolling back to v0.8.1.5 didn't helped:
["pyaarlo>=0.8.0.9"](https://github.com/twrecked/hass-aarlo/blob/b1d81b061c623aa00e6ecabba04ed4954fdfbcb3/custom_components/aarlo/manifest.json#L16) >= :) and bug was introduced in pyaarlo 0.8.0.10 :) and it always uses the latest version.

**Comment by Kolbi** [comment]
So more or less no new hass-aarlo release is needed just reinstall latest v0.8.1.6 and it should grap pyaarl 0.8.0.11 - but I have seen you were faster and released hass-aarlo v0.8.1.7.

**Comment by Kolbi** [comment]
Yeah makes it easier for rolling back. But for updated backend you need to release a new hass-aarlo version but should be done anyway to inform about updates and so on.

Should be fixed with https://github.com/twrecked/hass-aarlo/releases/tag/v0.8.1.7

I will have a look into it and close the issue then I can confirm that it is working again.
